/**
 * Wiring: editor -> DSL -> intent graph -> Rust core -> viewport.
 *
 * The script runs here in the webview rather than in an embedded interpreter,
 * because the webview already has a very good JavaScript engine and the script
 * does no geometry — it only builds a graph. Everything expensive happens in
 * Rust.
 */

import "./style.css";
import * as backend from "./backend";
import { EditorView, basicSetup } from "codemirror";
import { StateEffect, StateField } from "@codemirror/state";
import { Decoration, type DecorationSet } from "@codemirror/view";
import { javascript } from "@codemirror/lang-javascript";
import { oneDark } from "@codemirror/theme-one-dark";
import * as dsl from "./dsl";
import { Shape } from "./dsl";
import { label as projectLabel, loadProjects, readProject } from "./projects";
import { suggestVertexSelector, verticesFromEdges, type VertexPoint } from "./entities";
import { selectorLinter } from "./selector-lint";
import { treatmentHover as treatmentHoverTooltip, type TreatmentHoverSource } from "./treatment-hover";
import type { TreatmentNode } from "./treatment-info";
import { instrumentTreatmentCalls, sourceOffset, treatmentAtCursor, treatmentCallRange } from "./source-link";
import { Viewport, type SectionPlane, type TargetVertex } from "./viewport";

interface Report {
  units: string;
  bounds: { min: Vec3; max: Vec3 };
  size: Vec3;
  framing_bounds: { min: Vec3; max: Vec3 };
  mass: { volume_mm3: number; area_mm2: number; centroid: Vec3 };
  mesh: {
    vertices: number;
    triangles: number;
    resolution_mm: number;
    watertight: boolean;
    non_manifold_edges: number;
  };
  tags: string[];
  live_nodes: number;
  total_nodes: number;
}

interface Vec3 {
  x: number;
  y: number;
  z: number;
}

interface Evaluated {
  positions: number[];
  normals: number[];
  indices: number[];
  /** Logical edge curves. Omitted in mesh-preview mode. */
  edges: EdgeCurve[];
  /** Face and edge counts. Null in mesh-preview mode, where the question does
   *  not apply — which is different from the answer being zero. */
  topology: { faces: number; edges: number } | null;
  backend: "implicit" | "brep";
  report: Report;
  timings: {
    lower_and_mesh_ms: number;
    normals_ms: number;
    kernel_ms: number;
  };
}

interface BuiltGraph {
  graph: dsl.Doc;
  source: string;
  treatments: dsl.TreatmentSource[];
}

interface TargetPreview {
  node: number;
  edges: EdgeCurve[];
  vertices: TargetVertex[];
  /** Tags whose live edge set is exactly this target, from the kernel. */
  provenance?: string[];
}

/** A visible B-rep edge. `id` is valid only for this evaluated result. */
interface EdgeCurve {
  id: string;
  points: number[][];
  center: [number, number, number];
  direction: [number, number, number] | null;
  length_mm: number;
  /** Ephemeral source node when this final edge was generated by a treatment. */
  treatment_node?: number;
}

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;


const statusEl = $("status");
const errorEl = $("error");
const reportEl = $("report");
const depthInput = $<HTMLInputElement>("depth");
const depthValue = $("depth-value");
const backendSelect = $<HTMLSelectElement>("backend");
const sectionAxis = $<HTMLSelectElement>("section-axis");
const sectionAt = $<HTMLInputElement>("section-at");
const sectionAtValue = $("section-at-value");
const sectionFlip = $<HTMLButtonElement>("section-flip");
const edgeInspector = $("edge-inspector");
const entityInspectorTitle = $("entity-inspector-title");
const edgeIdEl = $("edge-id");
const edgeDetailEl = $("edge-detail");
const edgeOriginEl = $("edge-origin");
const edgeSelectorEl = $("edge-selector");
const copyEdgeSelector = $<HTMLButtonElement>("copy-edge-selector");
const mcpEl = $("mcp");
const targetPreviewEl = $("target-preview");
const targetPreviewName = $("target-preview-name");
const targetPreviewDetail = $("target-preview-detail");

let visibleEdges: EdgeCurve[] = [];
let visibleVertices: VertexPoint[] = [];
let hoveredEdge: EdgeCurve | undefined;
let selectedEdge: EdgeCurve | undefined;
let hoveredVertex: VertexPoint | undefined;
let selectedVertex: VertexPoint | undefined;
let suggestedSelector: string | undefined;

const viewport = new Viewport($("viewport"), {
  onHover: (edge) => {
    hoveredEdge = edge;
    updateEntityInspector();
    highlightTreatmentForEdge(edge);
  },
  onSelect: (edge) => {
    selectedEdge = edge;
    updateEntityInspector();
    focusTreatmentForEdge(edge);
  },
  onVertexHover: (vertex) => {
    hoveredVertex = vertex;
    updateEntityInspector();
    if (vertex) highlightTreatmentForEdge(undefined);
  },
  onVertexSelect: (vertex) => {
    selectedVertex = vertex;
    updateEntityInspector();
    if (vertex) focusTreatmentForEdge(undefined);
  },
});
// Handle for poking at the scene from the console during development.
(window as unknown as Record<string, unknown>).__viewport = viewport;

/** Whether the camera has been framed on this part yet. */
let framed = false;
/** The last graph that evaluated cleanly, kept for export. */
let lastGraph: dsl.Doc | null = null;
let lastSource = "";
let lastTreatments: dsl.TreatmentSource[] = [];
let targetPreviewRequest = 0;
/** A clicked treatment keeps its authored chain visible after pointer-leave. */
let pinnedTreatment: dsl.TreatmentSource | undefined;

/** A viewport hover marks source without moving the editor cursor or scroll. */
const setTreatmentHover = StateEffect.define<{ from: number; to: number } | undefined>();
const treatmentHover = StateField.define<DecorationSet>({
  create: () => Decoration.none,
  update(decorations, transaction) {
    for (const effect of transaction.effects) {
      if (effect.is(setTreatmentHover)) {
        return effect.value
          ? Decoration.set([Decoration.mark({ class: "cm-treatment-hover" }).range(effect.value.from, effect.value.to)])
          : Decoration.none;
      }
    }
    return decorations.map(transaction.changes);
  },
  provide: (field) => EditorView.decorations.from(field),
});

// ---------------------------------------------------------------- the editor

/**
 * What the hover tooltip is allowed to know.
 *
 * Annotated and declared separately so the editor's type does not depend on
 * an extension that reads the editor back.
 */
const hoverSource: TreatmentHoverSource = {
  // Only for a document that still matches the evaluated graph. Hovering
  // half-typed source must not report the last part's counts.
  treatmentAt: (pos) => {
    const source = editor.state.doc.toString();
    if (source !== lastSource) return undefined;
    const treatment = treatmentAtCursor(editor.state, source, lastTreatments, pos);
    return treatment && { node: treatment.node, method: treatment.source?.method };
  },
  nodeAt: (node) => lastGraph?.nodes[node] as TreatmentNode | undefined,
  callRange: (node) => treatmentRange(lastTreatments.find((t) => t.node === node)),
  resolve: resolveTarget,
};

// Handle for poking at the tooltip during development, alongside `__editor`
// and `__viewport`.
(window as unknown as Record<string, unknown>).__hoverSource = hoverSource;

const editor = new EditorView({
  // Empty until the project folder answers. The document is loaded from disk
  // rather than compiled in, so there is nothing to show synchronously.
  doc: "",
  parent: $("editor"),
  extensions: [
    basicSetup,
    javascript(),
    oneDark,
    treatmentHover,
    // Selector syntax is marked as you type. Everything else — whether the
    // selector resolves, and to how many edges — waits for the evaluation
    // below, because only the kernel knows.
    selectorLinter,
    treatmentHoverTooltip(hoverSource),
    EditorView.updateListener.of((v) => {
      if (v.docChanged) {
        clearTargetPreview();
        pinnedTreatment = undefined;
        schedule();
      }
      if (v.selectionSet) previewTreatmentAtCursor();
    }),
  ],
});
// Match the viewport's developer-console handle above. The desktop smoke test
// uses this to place CodeMirror's normal selection deterministically; its
// assertions still cover the real selection listener, Tauri IPC request, and
// returned viewport overlay.
(window as unknown as Record<string, unknown>).__editor = editor;

// ------------------------------------------------------------ the eval cycle

let timer: number | undefined;
let running = false;
let dirty = false;

/**
 * Re-evaluate shortly after typing stops.
 *
 * Short enough to feel live, long enough that a burst of keystrokes is one
 * evaluation rather than twenty.
 */
function schedule() {
  window.clearTimeout(timer);
  timer = window.setTimeout(run, 350);
}

async function run() {
  if (running) {
    // Coalesce: remember that something changed and pick it up on the way out.
    dirty = true;
    return;
  }
  running = true;
  dirty = false;

  setStatus("evaluating", "busy");

  try {
    const built = buildGraph(editor.state.doc.toString());

    const depth = Number(depthInput.value);
    const result = await backend.evaluate<Evaluated>(built.graph, depth, backendSelect.value);

    lastGraph = built.graph;
    lastSource = built.source;
    lastTreatments = built.treatments;
    // Resolved targets belong to one graph. A cached count that outlived the
    // edit that changed it would be a confident wrong answer.
    resolvedTargets.clear();
    show(result);
    previewTreatmentAtCursor();
    clearError();
    const ms =
      result.backend === "brep"
        ? result.timings.kernel_ms
        : result.timings.lower_and_mesh_ms + result.timings.normals_ms;
    setStatus(`${result.report.mesh.triangles.toLocaleString()} tris · ${ms} ms`);
  } catch (e) {
    showError(e);
    setStatus("failed", "failed");
  } finally {
    running = false;
    if (dirty) schedule();
  }
}

/**
 * Run a script and flatten what it returns.
 *
 * The DSL is injected as named parameters rather than as globals, so a script
 * cannot accidentally depend on anything the page happens to have lying around.
 */
function buildGraph(source: string): BuiltGraph {
  const api = { ...dsl } as Record<string, unknown>;
  const names = Object.keys(api);

  let fn: (...args: unknown[]) => unknown;
  try {
    const executable = instrumentTreatmentCalls(editor.state, source);
    fn = new Function(...names, `${executable}\n//# sourceURL=parcad-editor.js`) as (...args: unknown[]) => unknown;
  } catch (e) {
    throw new Error(`the script did not parse:\n${(e as Error).message}`);
  }

  const result = fn(...names.map((n) => api[n]));
  if (!(result instanceof Shape)) {
    throw new Error(
      "the script must return a shape.\n" +
        "End it with something like:  return body.cut(hole)",
    );
  }
  const treatments: dsl.TreatmentSource[] = [];
  return { graph: dsl.build(result, treatments), source, treatments };
}

function show(result: Evaluated) {
  const { report } = result;
  visibleEdges = normalizeEdges(result.edges);
  visibleVertices = verticesFromEdges(visibleEdges);

  viewport.setGeometry(
    {
      positions: new Float32Array(result.positions),
      normals: new Float32Array(result.normals),
      indices: new Uint32Array(result.indices),
      edges: visibleEdges,
    },
    report.bounds,
  );

  // Frame once, then leave the camera alone — nothing is more irritating than a
  // view that resets itself every time you change a number.
  if (!framed) {
    viewport.frameAll(report.bounds);
    framed = true;
  }

  // The plane's travel is the part's own extent, so the slider covers exactly
  // the cuts that can show anything and no more.
  sectionBounds = report.bounds;
  retuneSection();

  const { size, mass, mesh } = report;
  const dead = report.total_nodes - report.live_nodes;
  const linkedEdges = visibleEdges.filter((edge) => treatmentForEdge(edge)).length;
  const linkedMethods = [...new Set(
    visibleEdges
      .map(treatmentForEdge)
      .filter((treatment): treatment is dsl.TreatmentSource => !!treatment)
      .map((treatment) => `.${treatment.source?.method ?? treatment.kind}`),
  )];
  // "resolution" means different things per backend and the difference matters:
  // a grid spacing is where samples were taken, a deflection is a bound on how
  // far the result can be from the truth. Label them apart.
  const tol =
    result.backend === "brep"
      ? `within <b>${mesh.resolution_mm.toFixed(3)}</b> mm of the true surface`
      : `at <b>${mesh.resolution_mm.toFixed(3)}</b> mm grid`;

  reportEl.innerHTML = [
    `<b>${fmt(size.x)} × ${fmt(size.y)} × ${fmt(size.z)}</b> mm`,
    `volume <b>${fmt(mass.volume_mm3)}</b> mm³ · area <b>${fmt(mass.area_mm2)}</b> mm²`,
    result.topology
      ? `topology <b>${result.topology.faces}</b> faces · <b>${result.topology.edges}</b> edges`
      : "",
    `mesh <b>${mesh.triangles.toLocaleString()}</b> tris ${tol} ` +
      (mesh.watertight
        ? `<span class="ok">watertight</span>`
        : `<span class="warn">NOT watertight — ${mesh.non_manifold_edges} bad edges</span>`),
    report.tags.length ? `tags ${report.tags.join(", ")}` : "no tags",
    linkedEdges
      ? `<span class="ok">source links <b>${linkedEdges}</b> final curves → ${linkedMethods.join(", ")}</span>`
      : lastTreatments.length
        ? "<span class=\"warn\">source links: no final treatment curves are available</span>"
        : "source links — no edge treatments",
    dead > 0 ? `<span class="warn">${dead} unused nodes</span>` : "",
  ]
    .filter(Boolean)
    .join("<br>");
}

/**
 * Keep the browser-only development artifact usable until it is regenerated.
 * The desktop worker always returns the metadata-rich form; older artifacts
 * contain bare polylines and can still be hovered, just without a direction.
 */
function normalizeEdges(edges: EdgeCurve[]): EdgeCurve[] {
  if (!Array.isArray(edges) || edges.length === 0 || !Array.isArray(edges[0])) return edges;

  return (edges as unknown as number[][][]).map((points, index) => {
    const center: [number, number, number] = [0, 0, 0];
    let length = 0;
    for (let i = 0; i < points.length; i++) {
      for (let axis = 0; axis < 3; axis++) center[axis] += points[i][axis];
      if (i > 0) length += Math.hypot(
        points[i][0] - points[i - 1][0],
        points[i][1] - points[i - 1][1],
        points[i][2] - points[i - 1][2],
      );
    }
    for (let axis = 0; axis < 3; axis++) center[axis] /= points.length;
    return { id: `edge@${index}`, points, center, direction: null, length_mm: length };
  });
}

/** Clear an in-flight or displayed source-to-viewport target preview. */
function clearTargetPreview() {
  targetPreviewRequest++;
  viewport.setTargetPreview([]);
  targetPreviewEl.hidden = true;
}

/**
 * Exact targets already resolved for the current graph, keyed by node.
 *
 * The cursor preview and the hover tooltip ask the same question of the same
 * node, and the answer costs a worker round trip that rebuilds the treatment's
 * child. Cleared whenever a new graph evaluates.
 */
const resolvedTargets = new Map<number, Promise<TargetPreview>>();

function resolveTarget(node: number): Promise<TargetPreview> {
  const cached = resolvedTargets.get(node);
  if (cached) return cached;

  const pending = backend.inspectEdgeTarget<TargetPreview>(lastGraph, node).then(
    (preview) => {
      if (preview.node !== node) throw new Error("the worker returned a different treatment");
      return preview;
    },
  );
  // A failed resolve is not cached: the next hover should ask again rather
  // than repeat a stale failure after the model is fixed.
  pending.catch(() => resolvedTargets.delete(node));
  resolvedTargets.set(node, pending);
  return pending;
}

/** Resolve and highlight the treatment call under the editor cursor. */
async function previewTreatmentAtCursor() {
  const request = ++targetPreviewRequest;
  const source = editor.state.doc.toString();
  const treatment =
    source === lastSource
      ? treatmentAtCursor(editor.state, source, lastTreatments, editor.state.selection.main.head)
      : undefined;
  if (!treatment || !lastGraph) {
    if (request === targetPreviewRequest) clearTargetPreview();
    return;
  }

  viewport.setTargetPreview([]);
  targetPreviewEl.hidden = false;
  targetPreviewName.textContent = `.${treatment.source!.method} input target`;
  targetPreviewDetail.textContent = "resolving exact target…";

  try {
    const preview = await resolveTarget(treatment.node);
    if (request !== targetPreviewRequest) return;
    const vertices = preview.vertices ?? [];
    viewport.setTargetPreview(normalizeEdges(preview.edges), vertices);
    targetPreviewName.textContent = vertices.length > 0
      ? `.${treatment.source!.method} input corner and edges`
      : `.${treatment.source!.method} input edges`;
    const entities = [
      vertices.length > 0 && `${vertices.length} selected corner${vertices.length === 1 ? "" : "s"}`,
      `${preview.edges.length} selected edge${preview.edges.length === 1 ? "" : "s"}`,
    ].filter(Boolean);
    targetPreviewDetail.textContent = entities.join(" · ");
  } catch {
    if (request !== targetPreviewRequest) return;
    clearTargetPreview();
  }
}

/** Show the hovered B-rep entity's temporary ID and a semantic selector. */
function updateEntityInspector() {
  const vertex = hoveredVertex ?? selectedVertex;
  if (vertex) {
    edgeInspector.hidden = false;
    // Say which of the two states this is. A click pins the entity and the
    // panel then stays after the pointer leaves; without the label the pinned
    // panel is indistinguishable from a hover that has not caught up yet.
    entityInspectorTitle.textContent = hoveredVertex ? "vertex inspector" : "vertex inspector · selected";
    edgeIdEl.textContent = vertex.id;
    edgeDetailEl.textContent = `(${vertex.point.map(fmt).join(", ")}) mm · ${vertex.degree} incident edge${vertex.degree === 1 ? "" : "s"}`;
    edgeOriginEl.hidden = true;
    suggestedSelector = suggestVertexSelector(vertex, visibleVertices);
    edgeSelectorEl.textContent = suggestedSelector
      ? `vertices: ${suggestedSelector}`
      : "no unique directional vertex selector";
    copyEdgeSelector.textContent = "copy vertex selector";
    copyEdgeSelector.disabled = !suggestedSelector;
    copyEdgeSelector.title = suggestedSelector
      ? "Copy a selector for shape.vertices(…); it is re-resolved on each evaluation"
      : "Add a stronger directional condition after changing the model";
    return;
  }

  const edge = hoveredEdge ?? selectedEdge;
  if (!edge) {
    edgeInspector.hidden = true;
    edgeOriginEl.hidden = true;
    suggestedSelector = undefined;
    return;
  }

  edgeInspector.hidden = false;
  entityInspectorTitle.textContent = hoveredEdge ? "edge inspector" : "edge inspector · selected";
  edgeIdEl.textContent = edge.id;
  const direction = edge.direction ? ` · ${directionLabel(edge.direction)}` : "";
  edgeDetailEl.textContent = `${fmt(edge.length_mm)} mm${direction}`;
  const treatment = treatmentForEdge(edge);
  edgeOriginEl.hidden = !treatment;
  if (treatment) {
    const method = treatment.source?.method ?? treatment.kind;
    edgeOriginEl.textContent = `from .${method}(…) · click to lock code`;
  }
  suggestedSelector = suggestEdgeSelector(edge, visibleEdges);
  edgeSelectorEl.textContent = suggestedSelector
    ? `selector: ${suggestedSelector}`
    : "no unique directional selector";
  copyEdgeSelector.textContent = "copy selector";
  copyEdgeSelector.disabled = !suggestedSelector;
  copyEdgeSelector.title = suggestedSelector
    ? "Copy a selector for shape.edges(…); it is re-resolved on each evaluation"
    : "Add a stronger directional condition, or use a future point/adjacency selector";
}

/** The source call whose exact builder history generated this final edge. */
function treatmentForEdge(edge: EdgeCurve): dsl.TreatmentSource | undefined {
  return edge.treatment_node === undefined
    ? undefined
    : lastTreatments.find((treatment) => treatment.node === edge.treatment_node);
}

/** Mark the source call for a final edge without stealing keyboard focus. */
function highlightTreatmentForEdge(edge: EdgeCurve | undefined) {
  const treatment = edge && editor.state.doc.toString() === lastSource
    ? treatmentForEdge(edge)
    : undefined;
  if (!treatment && pinnedTreatment) return;
  const range = treatmentRange(treatment);
  editor.dispatch({ effects: setTreatmentHover.of(range) });
  if (range && !rangeIsVisible(range)) {
    editor.dispatch({ effects: EditorView.scrollIntoView(range.from, { y: "center" }) });
  }
}

function rangeIsVisible(range: { from: number; to: number }): boolean {
  const start = editor.coordsAtPos(range.from);
  const end = editor.coordsAtPos(range.to);
  const pane = editor.scrollDOM.getBoundingClientRect();
  return !!start && !!end && start.top >= pane.top && end.bottom <= pane.bottom;
}

/** Select and reveal a treatment call after its generated edge is clicked. */
function focusTreatmentForEdge(edge: EdgeCurve | undefined) {
  if (!edge || editor.state.doc.toString() !== lastSource) {
    clearPinnedTreatment();
    return;
  }
  const treatment = treatmentForEdge(edge);
  const range = treatmentRange(treatment);
  if (!treatment?.source || !range) {
    clearPinnedTreatment();
    return;
  }

  const start = sourceOffset(lastSource, treatment.source.line, treatment.source.column);
  if (start === undefined) return;
  pinnedTreatment = treatment;
  editor.dispatch({
    selection: { anchor: start, head: start + treatment.source.method.length },
    effects: [
      setTreatmentHover.of(range),
      EditorView.scrollIntoView(start, { y: "center" }),
    ],
  });
}

function treatmentRange(treatment: dsl.TreatmentSource | undefined) {
  return treatment?.source
    ? treatmentCallRange(editor.state, lastSource, treatment.source)
    : undefined;
}

function clearPinnedTreatment() {
  pinnedTreatment = undefined;
  editor.dispatch({ effects: setTreatmentHover.of(undefined) });
}

function directionLabel(direction: [number, number, number]): string {
  const components = direction.map(Math.abs);
  const index = components.indexOf(Math.max(...components));
  return `|${["X", "Y", "Z"][index]}`;
}

/**
 * Derive the shortest `>X`, `<Y`, `|Z` conjunction that identifies this
 * currently visible edge. It is a convenience for the inspector, not a hidden
 * ID: if the geometry later becomes ambiguous, the B-rep evaluator refuses.
 */
function suggestEdgeSelector(edge: EdgeCurve, all: EdgeCurve[]): string | undefined {
  if (all.length === 0) return undefined;
  const axes = ["X", "Y", "Z"] as const;
  const terms: string[] = [];
  const epsilon = 1e-4;

  if (edge.direction) {
    const axis = edge.direction.map(Math.abs).indexOf(Math.max(...edge.direction.map(Math.abs)));
    if (Math.abs(edge.direction[axis]) >= 0.999) terms.push(`|${axes[axis]}`);
  }
  for (let axis = 0; axis < 3; axis++) {
    const values = all.map((candidate) => candidate.center[axis]);
    const maximum = Math.max(...values);
    const minimum = Math.min(...values);
    if (Math.abs(edge.center[axis] - maximum) <= epsilon) terms.push(`>${axes[axis]}`);
    if (Math.abs(edge.center[axis] - minimum) <= epsilon) terms.push(`<${axes[axis]}`);
  }

  const matches = (candidate: EdgeCurve, term: string) => {
    const axis = axes.indexOf(term[1] as (typeof axes)[number]);
    if (term[0] === "|") {
      return candidate.direction !== null && Math.abs(candidate.direction[axis]) >= 0.999;
    }
    const values = all.map((other) => other.center[axis]);
    const extreme = term[0] === ">" ? Math.max(...values) : Math.min(...values);
    return Math.abs(candidate.center[axis] - extreme) <= epsilon;
  };

  const selected: string[] = [];
  let candidates = all;
  while (candidates.length > 1) {
    const currentCount = candidates.length;
    const next = terms
      .filter((term) => !selected.includes(term))
      .map((term) => ({ term, candidates: candidates.filter((candidate) => matches(candidate, term)) }))
      .filter(({ candidates: remaining }) => remaining.length > 0 && remaining.length < currentCount)
      .sort((a, b) => a.candidates.length - b.candidates.length)[0];
    if (!next || next.candidates.length >= candidates.length) break;
    selected.push(next.term);
    candidates = next.candidates;
  }

  return candidates.length === 1 && selected.length > 0 ? selected.join(" and ") : undefined;
}

copyEdgeSelector.addEventListener("click", async () => {
  if (!suggestedSelector || !navigator.clipboard) return;
  try {
    await navigator.clipboard.writeText(suggestedSelector);
    setStatus(`copied ${suggestedSelector}`);
  } catch {
    setStatus("could not copy selector", "failed");
  }
});

const fmt = (v: number) =>
  Math.abs(v) >= 1000 ? v.toFixed(0) : v.toFixed(2).replace(/\.00$/, "");

function setStatus(text: string, cls = "") {
  statusEl.textContent = text;
  statusEl.className = `status ${cls}`;
}

function showError(e: unknown) {
  errorEl.textContent = e instanceof Error ? e.message : String(e);
  errorEl.hidden = false;
  // Leave the last good geometry on screen. A broken edit mid-typing should not
  // blank the viewport.
}

function clearError() {
  errorEl.hidden = true;
  errorEl.textContent = "";
}

// ------------------------------------------------------------------- chrome

depthInput.addEventListener("input", () => {
  depthValue.textContent = depthInput.value;
  schedule();
});

// ------------------------------------------------------------------ section

/** The part's extent, so the plane can only travel where there is material. */
let sectionBounds: { min: Vec3; max: Vec3 } | undefined;
/** Which half survives. Chosen from the camera when an axis is picked; the flip
 *  button is the override, and it sticks until the axis changes again. */
let sectionKeep: "below" | "above" = "below";

/**
 * Re-fit the slider to the current part, keeping the plane where it was.
 *
 * Both halves matter. Re-fitting is what makes one slider work for a 6 mm part
 * and a 600 mm one; keeping the position is what stops a section jumping to the
 * middle of the part on every keystroke, which is the difference between a
 * usable section and one you have to re-aim after every edit.
 */
function retuneSection() {
  const axis = sectionAxis.value as "" | "x" | "y" | "z";
  const enabled = axis !== "" && sectionBounds !== undefined;

  sectionAt.disabled = !enabled;
  sectionFlip.disabled = !enabled;
  if (!enabled) {
    sectionAtValue.textContent = "";
    viewport.setSection(undefined);
    return;
  }

  const min = sectionBounds!.min[axis];
  const max = sectionBounds!.max[axis];
  sectionAt.min = String(min);
  sectionAt.max = String(max);
  // A hundred steps across the part: fine enough to walk a plane through a
  // 2 mm wall, coarse enough that dragging it is not a slideshow.
  sectionAt.step = String(Math.max((max - min) / 100, 1e-4));

  const at = Math.min(Math.max(Number(sectionAt.value), min), max);
  sectionAt.value = String(at);
  sectionAtValue.textContent = `${at.toFixed(1)} mm`;

  const plane: SectionPlane = { axis, atMm: at, keep: sectionKeep };
  viewport.setSection(plane);
}

sectionAxis.addEventListener("change", () => {
  // A fresh axis starts in the middle of the part, where a section is most
  // likely to cross something worth seeing — the same default the kernel picks
  // when an agent names an axis and no position.
  if (sectionBounds && sectionAxis.value !== "") {
    const axis = sectionAxis.value as "x" | "y" | "z";
    sectionAt.value = String((sectionBounds.min[axis] + sectionBounds.max[axis]) / 2);
    // Open it facing the camera. Keeping the near half instead puts the cut on
    // the far side of the material, which looks exactly like no section at all.
    sectionKeep = viewport.keepFacingCamera(axis);
  }
  retuneSection();
});
sectionAt.addEventListener("input", retuneSection);
sectionFlip.addEventListener("click", () => {
  sectionKeep = sectionKeep === "below" ? "above" : "below";
  retuneSection();
});

backendSelect.addEventListener("change", () => {
  syncBackendUi();
  // A backend swap changes the geometry, not the part, so the camera stays.
  schedule();
});

/** B-rep meshes to a fixed deflection; its solid and triangle views have no grid. */
function syncBackendUi() {
  const brepMesh = backendSelect.value === "brep" || backendSelect.value === "preview";
  depthInput.disabled = brepMesh;
  depthInput.parentElement!.classList.toggle("disabled", brepMesh);
  depthInput.parentElement!.title = brepMesh
    ? "B-rep meshes to a fixed 0.01 mm deflection; there is no grid to coarsen"
    : "";
}
syncBackendUi();

// ---------------------------------------------------------------- MCP status

/**
 * Whether a model is on the third transport, refreshed on a timer.
 *
 * An agent reaches the same `service.rs` this window does and writes to the
 * same project folder, and nothing on screen would otherwise say so: the part
 * you are looking at can be replaced under you by a caller you cannot see.
 *
 * Everything shown here is measured — a request that arrived, a tool that was
 * called — which is why an idle client is reported with the age of its last
 * call rather than as a flat "connected". A client that was killed cannot say
 * goodbye, and claiming it is still there would be the confident wrong answer
 * this codebase refuses everywhere else.
 */
const MCP_POLL_MS = 4000;
/** Below this, the last call is recent enough to call the agent active. */
const MCP_ACTIVE_SECS = 20;

async function pollMcp() {
  let mcp: backend.McpStatus;
  try {
    mcp = await backend.mcpStatus();
  } catch {
    // The host answers this window's every other call too, so a failure here is
    // not an MCP fact and must not be shown as one.
    mcpEl.hidden = true;
    return;
  }

  const chip = mcpChip(mcp);
  mcpEl.hidden = false;
  mcpEl.className = `mcp ${chip.tone}`;
  mcpEl.textContent = chip.text;
  mcpEl.title = chip.detail;
}

/** One status, as the three things the chip shows. */
function mcpChip(mcp: backend.McpStatus): { text: string; tone: string; detail: string } {
  const idle = mcp.idle_secs;
  const working = idle !== null && idle < MCP_ACTIVE_SECS;

  // The chip says connected or not; the session count stays in the tooltip,
  // where there is room to say what it means. A client that reconnects opens a
  // second session and the endpoint cannot tell that from a second client, so
  // "3 sessions" on the chip would read as three agents.
  let text = "MCP";
  let tone = "";
  if (mcp.clients > 0) {
    text = working ? "MCP connected · working" : `MCP connected · idle ${age(idle!)}`;
    tone = working ? "busy" : "live";
  } else if (idle !== null) {
    text = `MCP last call ${age(idle)} ago`;
  }

  const lines = [
    mcp.clients > 0
      ? `${mcp.clients} open session${mcp.clients === 1 ? "" : "s"} — a client that reconnects opens another`
      : "no agent connected",
    `endpoint ${mcp.url}`,
  ];
  if (mcp.client) lines.push(`client ${mcp.client}`);
  if (mcp.tool_calls === 0) {
    lines.push("no tool calls yet");
  } else {
    const calls = `${mcp.tool_calls} tool call${mcp.tool_calls === 1 ? "" : "s"}`;
    lines.push(mcp.last_tool ? `${calls}, last ${mcp.last_tool}` : calls);
  }
  lines.push("An agent writes to the same project folder this window reads.");

  return { text, tone, detail: lines.join("\n") };
}

function age(seconds: number): string {
  if (seconds < 60) return `${Math.round(seconds)}s`;
  if (seconds < 3600) return `${Math.round(seconds / 60)}m`;
  return `${Math.round(seconds / 3600)}h`;
}

pollMcp();
window.setInterval(pollMcp, MCP_POLL_MS);

// The picker lists parcad's project folder rather than anything compiled in,
// so a part saved by hand or by an agent shows up here on the next load.
const picker = $<HTMLSelectElement>("example");

picker.addEventListener("change", async (e) => {
  const name = (e.target as HTMLSelectElement).value;
  try {
    const source = await readProject(name);
    editor.dispatch({ changes: { from: 0, to: editor.state.doc.length, insert: source } });
    framed = false;
    clearError();
  } catch (err) {
    showError(err);
    setStatus("could not open the project", "failed");
  }
});

/**
 * Fill the picker and open a part.
 *
 * Evaluation is deliberately not started before this resolves: running the
 * empty document would report "the script must return a shape", which is true
 * and useless as a first impression.
 */
async function start() {
  setStatus("loading projects", "busy");
  let projects;
  try {
    projects = await loadProjects();
  } catch (e) {
    showError(e);
    setStatus("failed", "failed");
    return;
  }

  for (const name of projects.names) {
    const option = document.createElement("option");
    option.value = name;
    option.textContent = projectLabel(name);
    picker.append(option);
  }
  picker.title = `Parts in ${projects.directory}`;

  if (!projects.initial) {
    setStatus("no projects");
    showError(
      new Error(
        `parcad's project folder is empty:\n  ${projects.directory}\n` +
          "Put a .js part in it, or write one here and save it.",
      ),
    );
    return;
  }

  picker.value = projects.initial;
  const source = await readProject(projects.initial);
  editor.dispatch({ changes: { from: 0, to: editor.state.doc.length, insert: source } });
  run();
}

// Draggable split between editor and viewport.
{
  const splitter = $("splitter");
  const pane = $("editor-pane");
  let dragging = false;

  splitter.addEventListener("pointerdown", (e) => {
    dragging = true;
    splitter.setPointerCapture(e.pointerId);
  });
  splitter.addEventListener("pointermove", (e) => {
    if (!dragging) return;
    const pct = (e.clientX / window.innerWidth) * 100;
    pane.style.width = `${Math.min(75, Math.max(15, pct))}%`;
  });
  splitter.addEventListener("pointerup", (e) => {
    dragging = false;
    splitter.releasePointerCapture(e.pointerId);
  });
}

// Cmd-S exports rather than saving a page nobody wants. Cmd-Shift-S writes
// STEP, which needs the B-rep kernel whatever the viewport is currently showing
// — a mesh cannot be turned into exact surfaces after the fact.
window.addEventListener("keydown", async (e) => {
  if (!(e.metaKey || e.ctrlKey) || e.key.toLowerCase() !== "s") return;
  e.preventDefault();
  if (!lastGraph) return;

  const step = e.shiftKey;
  setStatus(step ? "exporting STEP" : "exporting STL", "busy");
  try {
    const name = step
      ? await backend.exportStep(lastGraph)
      : await backend.exportStl(lastGraph, Number(depthInput.value), backendSelect.value);
    setStatus(`exported ${name}`);
    clearError();
  } catch (err) {
    showError(err);
    setStatus("export failed", "failed");
  }
});

start();
