/**
 * Wiring: editor -> DSL -> intent graph -> Rust core -> viewport.
 *
 * The script runs here in the webview rather than in an embedded interpreter,
 * because the webview already has a very good JavaScript engine and the script
 * does no geometry — it only builds a graph. Everything expensive happens in
 * Rust.
 */

import "./style.css";
import * as backend from "./backend";
import { EditorView, basicSetup } from "codemirror";
import { undo } from "@codemirror/commands";
import { StateEffect, StateField } from "@codemirror/state";
import { Decoration, type DecorationSet } from "@codemirror/view";
import { javascript } from "@codemirror/lang-javascript";
import { oneDark } from "@codemirror/theme-one-dark";
import * as dsl from "./dsl";
import { Shape } from "./dsl";
import { describeProjects, label as projectLabel, partAt } from "./projects";
import { mountProjectBrowser } from "./project-browser";
import { suggestVertexSelector, verticesFromEdges, type VertexPoint } from "./entities";
import { selectorLinter } from "./selector-lint";
import { treatmentHover as treatmentHoverTooltip, type TreatmentHoverSource } from "./treatment-hover";
import type { TreatmentNode } from "./treatment-info";
import { instrumentTreatmentCalls, sourceOffset, treatmentAtCursor, treatmentCallRange } from "./source-link";
import { Viewport, type SectionPlane, type TargetVertex } from "./viewport";

/**
 * One evaluation, as the host measured it.
 *
 * The same object, field for field, that an agent gets back from MCP's
 * `evaluate_part`: `service.rs` builds exactly one of these per evaluation and
 * every transport serialises it. Nothing here may compute a measurement of its
 * own — this window and a model looking at the same part have to be reading the
 * same numbers, and the only way to guarantee that is to have one producer.
 *
 * Millimetres throughout. Triples are `[x, y, z]`.
 */
interface EvaluationSnapshot {
  units: string;
  size: [number, number, number];
  bounds_min: [number, number, number];
  bounds_max: [number, number, number];
  volume_mm3: number;
  area_mm2: number;
  centroid: [number, number, number];
  /** Exact-kernel counts. Absent for the implicit backend and for a mesh
   *  preview, where the question does not apply — different from zero. */
  faces?: number;
  topological_edges?: number;
  triangles: number;
  resolution_mm: number;
  watertight: boolean;
  non_manifold_edges: number;
  tags: string[];
  treatments: { node: number; op: string; amount_mm: number; continuity?: string }[];
  /** Shapes the root never reaches. Absent when there are none. */
  unused_nodes?: number;
  backend: "implicit" | "brep";
  kernel_ms: number;
}

interface Vec3 {
  x: number;
  y: number;
  z: number;
}

interface Evaluated {
  positions: number[];
  normals: number[];
  indices: number[];
  /** Logical edge curves. Omitted in mesh-preview mode. */
  edges: EdgeCurve[];
  snapshot: EvaluationSnapshot;
  /** The implicit path's two halves. Kernel time is in the snapshot. */
  timings: {
    lower_and_mesh_ms: number;
    normals_ms: number;
  };
}

/** The snapshot's bounds in the shape the viewport and the section slider take. */
function boundsOf(snapshot: EvaluationSnapshot): { min: Vec3; max: Vec3 } {
  const v = ([x, y, z]: [number, number, number]) => ({ x, y, z });
  return { min: v(snapshot.bounds_min), max: v(snapshot.bounds_max) };
}

interface BuiltGraph {
  graph: dsl.Doc;
  source: string;
  treatments: dsl.TreatmentSource[];
}

interface TargetPreview {
  node: number;
  edges: EdgeCurve[];
  vertices: TargetVertex[];
  /** Tags whose live edge set is exactly this target, from the kernel. */
  provenance?: string[];
}

/** A visible B-rep edge. `id` is valid only for this evaluated result. */
interface EdgeCurve {
  id: string;
  points: number[][];
  center: [number, number, number];
  direction: [number, number, number] | null;
  length_mm: number;
  /** Ephemeral source node when this final edge was generated by a treatment. */
  treatment_node?: number;
}

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;


const statusEl = $("status");
const errorEl = $("error");
const reportEl = $("report");
const depthInput = $<HTMLInputElement>("depth");
const depthValue = $("depth-value");
const backendSelect = $<HTMLSelectElement>("backend");
const sectionAxis = $<HTMLSelectElement>("section-axis");
const sectionAt = $<HTMLInputElement>("section-at");
const sectionAtValue = $("section-at-value");
const sectionFlip = $<HTMLButtonElement>("section-flip");
const edgeInspector = $("edge-inspector");
const entityInspectorTitle = $("entity-inspector-title");
const edgeIdEl = $("edge-id");
const edgeDetailEl = $("edge-detail");
const edgeOriginEl = $("edge-origin");
const edgeSelectorEl = $("edge-selector");
const copyEdgeSelector = $<HTMLButtonElement>("copy-edge-selector");
const mcpEl = $("mcp");
const targetPreviewEl = $("target-preview");
const targetPreviewName = $("target-preview-name");
const targetPreviewDetail = $("target-preview-detail");

let visibleEdges: EdgeCurve[] = [];
let visibleVertices: VertexPoint[] = [];
let hoveredEdge: EdgeCurve | undefined;
let selectedEdge: EdgeCurve | undefined;
let hoveredVertex: VertexPoint | undefined;
let selectedVertex: VertexPoint | undefined;
let suggestedSelector: string | undefined;

const viewport = new Viewport($("viewport"), {
  onHover: (edge) => {
    hoveredEdge = edge;
    updateEntityInspector();
    highlightTreatmentForEdge(edge);
  },
  onSelect: (edge) => {
    selectedEdge = edge;
    updateEntityInspector();
    focusTreatmentForEdge(edge);
  },
  onVertexHover: (vertex) => {
    hoveredVertex = vertex;
    updateEntityInspector();
    if (vertex) highlightTreatmentForEdge(undefined);
  },
  onVertexSelect: (vertex) => {
    selectedVertex = vertex;
    updateEntityInspector();
    if (vertex) focusTreatmentForEdge(undefined);
  },
});
// Handle for poking at the scene from the console during development.
(window as unknown as Record<string, unknown>).__viewport = viewport;

/** Whether the camera has been framed on this part yet. */
let framed = false;
/** The last graph that evaluated cleanly, kept for export. */
let lastGraph: dsl.Doc | null = null;
let lastSource = "";
/** The last measurements, kept so a save can describe the part it saved. */
let lastSnapshot: EvaluationSnapshot | undefined;
let lastTreatments: dsl.TreatmentSource[] = [];
/**
 * Which part the geometry currently on screen belongs to.
 *
 * A failed build deliberately leaves the last good part rendered, so a broken
 * keystroke does not blank the viewport. That is only defensible while the
 * geometry is still *this* part's: if the first build after opening another one
 * fails, everything on screen — the solid, its volume, its watertightness —
 * describes a part the titlebar is no longer naming.
 */
let shownPath: string | undefined;
let targetPreviewRequest = 0;
/** A clicked treatment keeps its authored chain visible after pointer-leave. */
let pinnedTreatment: dsl.TreatmentSource | undefined;

/** A viewport hover marks source without moving the editor cursor or scroll. */
const setTreatmentHover = StateEffect.define<{ from: number; to: number } | undefined>();
const treatmentHover = StateField.define<DecorationSet>({
  create: () => Decoration.none,
  update(decorations, transaction) {
    for (const effect of transaction.effects) {
      if (effect.is(setTreatmentHover)) {
        return effect.value
          ? Decoration.set([Decoration.mark({ class: "cm-treatment-hover" }).range(effect.value.from, effect.value.to)])
          : Decoration.none;
      }
    }
    return decorations.map(transaction.changes);
  },
  provide: (field) => EditorView.decorations.from(field),
});

// ---------------------------------------------------------------- the editor

/**
 * What the hover tooltip is allowed to know.
 *
 * Annotated and declared separately so the editor's type does not depend on
 * an extension that reads the editor back.
 */
const hoverSource: TreatmentHoverSource = {
  // Only for a document that still matches the evaluated graph. Hovering
  // half-typed source must not report the last part's counts.
  treatmentAt: (pos) => {
    const source = editor.state.doc.toString();
    if (source !== lastSource) return undefined;
    const treatment = treatmentAtCursor(editor.state, source, lastTreatments, pos);
    return treatment && { node: treatment.node, method: treatment.source?.method };
  },
  nodeAt: (node) => lastGraph?.nodes[node] as TreatmentNode | undefined,
  callRange: (node) => treatmentRange(lastTreatments.find((t) => t.node === node)),
  resolve: resolveTarget,
};

// Handle for poking at the tooltip during development, alongside `__editor`
// and `__viewport`.
(window as unknown as Record<string, unknown>).__hoverSource = hoverSource;

const editor = new EditorView({
  // Empty until the project folder answers. The document is loaded from disk
  // rather than compiled in, so there is nothing to show synchronously.
  doc: "",
  parent: $("editor"),
  extensions: [
    basicSetup,
    javascript(),
    oneDark,
    treatmentHover,
    // Selector syntax is marked as you type. Everything else — whether the
    // selector resolves, and to how many edges — waits for the evaluation
    // below, because only the kernel knows.
    selectorLinter,
    treatmentHoverTooltip(hoverSource),
    EditorView.updateListener.of((v) => {
      if (v.docChanged) {
        // The titlebar's saved/unsaved mark is a fact about this keystroke, so
        // it cannot wait for the debounced evaluation below.
        showOpenPart();
        clearTargetPreview();
        pinnedTreatment = undefined;
        schedule();
      }
      if (v.selectionSet) previewTreatmentAtCursor();
    }),
  ],
});
// Match the viewport's developer-console handle above. The desktop smoke test
// uses this to place CodeMirror's normal selection deterministically; its
// assertions still cover the real selection listener, Tauri IPC request, and
// returned viewport overlay.
(window as unknown as Record<string, unknown>).__editor = editor;
// The undo *command*, beside the editor handle. The desktop e2e driver cannot
// reliably deliver a Cmd-Z keystroke to WKWebView (same limitation the bracket
// spec records for Cmd-F), and what the session suite asserts is not key
// delivery but history: an agent's edit must sit in the same undo history a
// user's own typing goes into, and this is that history's own command.
(window as unknown as Record<string, unknown>).__undo = () => undo(editor);

// ------------------------------------------------------------ the eval cycle

let timer: number | undefined;
let running = false;
let dirty = false;

/**
 * Re-evaluate shortly after typing stops.
 *
 * Short enough to feel live, long enough that a burst of keystrokes is one
 * evaluation rather than twenty.
 */
function schedule() {
  window.clearTimeout(timer);
  timer = window.setTimeout(run, 350);
}

async function run() {
  if (running) {
    // Coalesce: remember that something changed and pick it up on the way out.
    dirty = true;
    return;
  }
  running = true;
  dirty = false;

  setStatus("evaluating", "busy");

  // Tell the host what this window is showing, on the same debounce. Without
  // this an agent's get_session would report the last thing it wrote itself
  // rather than what the user has typed since. Fire and forget: geometry must
  // not wait on it, and pushing even a script that will fail to build below is
  // the point — a broken draft is still what is on screen.
  const source = editor.state.doc.toString();
  void backend.pushSession(openPath ?? null, source, viewerId).catch(() => {});

  try {
    const built = buildGraph(source);

    const depth = Number(depthInput.value);
    const result = await backend.evaluate<Evaluated>(built.graph, depth, backendSelect.value);

    lastGraph = built.graph;
    lastSource = built.source;
    lastTreatments = built.treatments;
    // Resolved targets belong to one graph. A cached count that outlived the
    // edit that changed it would be a confident wrong answer.
    resolvedTargets.clear();
    show(result);
    previewTreatmentAtCursor();
    clearError();
    const ms =
      result.snapshot.backend === "brep"
        ? result.snapshot.kernel_ms
        : result.timings.lower_and_mesh_ms + result.timings.normals_ms;
    setStatus(`${result.snapshot.triangles.toLocaleString()} tris · ${ms} ms`);
    void captureFirstThumbnail();
  } catch (e) {
    showError(e);
    setStatus("failed", "failed");
  } finally {
    running = false;
    if (dirty) schedule();
  }
}

/**
 * Run a script and flatten what it returns.
 *
 * The DSL is injected as named parameters rather than as globals, so a script
 * cannot accidentally depend on anything the page happens to have lying around.
 */
function buildGraph(source: string): BuiltGraph {
  const api = { ...dsl } as Record<string, unknown>;
  const names = Object.keys(api);

  let fn: (...args: unknown[]) => unknown;
  try {
    const executable = instrumentTreatmentCalls(editor.state, source);
    fn = new Function(...names, `${executable}\n//# sourceURL=parcad-editor.js`) as (...args: unknown[]) => unknown;
  } catch (e) {
    throw new Error(`the script did not parse:\n${(e as Error).message}`);
  }

  const result = fn(...names.map((n) => api[n]));
  if (!(result instanceof Shape)) {
    throw new Error(
      "the script must return a shape.\n" +
        "End it with something like:  return body.cut(hole)",
    );
  }
  const treatments: dsl.TreatmentSource[] = [];
  return { graph: dsl.build(result, treatments), source, treatments };
}

function show(result: Evaluated) {
  const snapshot = result.snapshot;
  shownPath = openPath;
  lastSnapshot = snapshot;
  visibleEdges = normalizeEdges(result.edges);
  visibleVertices = verticesFromEdges(visibleEdges);
  const bounds = boundsOf(snapshot);

  viewport.setGeometry(
    {
      positions: new Float32Array(result.positions),
      normals: new Float32Array(result.normals),
      indices: new Uint32Array(result.indices),
      edges: visibleEdges,
    },
    bounds,
  );

  // Frame once, then leave the camera alone — nothing is more irritating than a
  // view that resets itself every time you change a number.
  if (!framed) {
    viewport.frameAll(bounds);
    framed = true;
  }

  // The plane's travel is the part's own extent, so the slider covers exactly
  // the cuts that can show anything and no more.
  sectionBounds = bounds;
  retuneSection();

  const [sx, sy, sz] = snapshot.size;
  const dead = snapshot.unused_nodes ?? 0;
  const linkedEdges = visibleEdges.filter((edge) => treatmentForEdge(edge)).length;
  const linkedMethods = [...new Set(
    visibleEdges
      .map(treatmentForEdge)
      .filter((treatment): treatment is dsl.TreatmentSource => !!treatment)
      .map((treatment) => `.${treatment.source?.method ?? treatment.kind}`),
  )];
  // "resolution" means different things per backend and the difference matters:
  // a grid spacing is where samples were taken, a deflection is a bound on how
  // far the result can be from the truth. Label them apart.
  const tol =
    snapshot.backend === "brep"
      ? `within <b>${snapshot.resolution_mm.toFixed(3)}</b> mm of the true surface`
      : `at <b>${snapshot.resolution_mm.toFixed(3)}</b> mm grid`;

  reportEl.hidden = false;
  reportEl.innerHTML = [
    `<b>${fmt(sx)} × ${fmt(sy)} × ${fmt(sz)}</b> mm`,
    `volume <b>${fmt(snapshot.volume_mm3)}</b> mm³ · area <b>${fmt(snapshot.area_mm2)}</b> mm²`,
    snapshot.faces !== undefined
      ? `topology <b>${snapshot.faces}</b> faces · <b>${snapshot.topological_edges}</b> edges`
      : "",
    `mesh <b>${snapshot.triangles.toLocaleString()}</b> tris ${tol} ` +
      (snapshot.watertight
        ? `<span class="text-good">watertight</span>`
        : `<span class="text-bad">NOT watertight — ${snapshot.non_manifold_edges} bad edges</span>`),
    snapshot.tags.length ? `tags ${snapshot.tags.join(", ")}` : "no tags",
    linkedEdges
      ? `<span class="text-good">source links <b>${linkedEdges}</b> final curves → ${linkedMethods.join(", ")}</span>`
      : lastTreatments.length
        ? "<span class=\"text-bad\">source links: no final treatment curves are available</span>"
        : "source links — no edge treatments",
    dead > 0 ? `<span class="text-bad">${dead} unused nodes</span>` : "",
  ]
    .filter(Boolean)
    .join("<br>");
}

/**
 * Keep the browser-only development artifact usable until it is regenerated.
 * The desktop worker always returns the metadata-rich form; older artifacts
 * contain bare polylines and can still be hovered, just without a direction.
 */
function normalizeEdges(edges: EdgeCurve[]): EdgeCurve[] {
  if (!Array.isArray(edges) || edges.length === 0 || !Array.isArray(edges[0])) return edges;

  return (edges as unknown as number[][][]).map((points, index) => {
    const center: [number, number, number] = [0, 0, 0];
    let length = 0;
    for (let i = 0; i < points.length; i++) {
      for (let axis = 0; axis < 3; axis++) center[axis] += points[i][axis];
      if (i > 0) length += Math.hypot(
        points[i][0] - points[i - 1][0],
        points[i][1] - points[i - 1][1],
        points[i][2] - points[i - 1][2],
      );
    }
    for (let axis = 0; axis < 3; axis++) center[axis] /= points.length;
    return { id: `edge@${index}`, points, center, direction: null, length_mm: length };
  });
}

/** Clear an in-flight or displayed source-to-viewport target preview. */
function clearTargetPreview() {
  targetPreviewRequest++;
  viewport.setTargetPreview([]);
  targetPreviewEl.hidden = true;
}

/**
 * Exact targets already resolved for the current graph, keyed by node.
 *
 * The cursor preview and the hover tooltip ask the same question of the same
 * node, and the answer costs a worker round trip that rebuilds the treatment's
 * child. Cleared whenever a new graph evaluates.
 */
const resolvedTargets = new Map<number, Promise<TargetPreview>>();

function resolveTarget(node: number): Promise<TargetPreview> {
  const cached = resolvedTargets.get(node);
  if (cached) return cached;

  const pending = backend.inspectEdgeTarget<TargetPreview>(lastGraph, node).then(
    (preview) => {
      if (preview.node !== node) throw new Error("the worker returned a different treatment");
      return preview;
    },
  );
  // A failed resolve is not cached: the next hover should ask again rather
  // than repeat a stale failure after the model is fixed.
  pending.catch(() => resolvedTargets.delete(node));
  resolvedTargets.set(node, pending);
  return pending;
}

/** Resolve and highlight the treatment call under the editor cursor. */
async function previewTreatmentAtCursor() {
  const request = ++targetPreviewRequest;
  const source = editor.state.doc.toString();
  const treatment =
    source === lastSource
      ? treatmentAtCursor(editor.state, source, lastTreatments, editor.state.selection.main.head)
      : undefined;
  if (!treatment || !lastGraph) {
    if (request === targetPreviewRequest) clearTargetPreview();
    return;
  }

  viewport.setTargetPreview([]);
  targetPreviewEl.hidden = false;
  targetPreviewName.textContent = `.${treatment.source!.method} input target`;
  targetPreviewDetail.textContent = "resolving exact target…";

  try {
    const preview = await resolveTarget(treatment.node);
    if (request !== targetPreviewRequest) return;
    const vertices = preview.vertices ?? [];
    viewport.setTargetPreview(normalizeEdges(preview.edges), vertices);
    targetPreviewName.textContent = vertices.length > 0
      ? `.${treatment.source!.method} input corner and edges`
      : `.${treatment.source!.method} input edges`;
    const entities = [
      vertices.length > 0 && `${vertices.length} selected corner${vertices.length === 1 ? "" : "s"}`,
      `${preview.edges.length} selected edge${preview.edges.length === 1 ? "" : "s"}`,
    ].filter(Boolean);
    targetPreviewDetail.textContent = entities.join(" · ");
  } catch {
    if (request !== targetPreviewRequest) return;
    clearTargetPreview();
  }
}

/** Show the hovered B-rep entity's temporary ID and a semantic selector. */
function updateEntityInspector() {
  const vertex = hoveredVertex ?? selectedVertex;
  if (vertex) {
    edgeInspector.hidden = false;
    // Say which of the two states this is. A click pins the entity and the
    // panel then stays after the pointer leaves; without the label the pinned
    // panel is indistinguishable from a hover that has not caught up yet.
    entityInspectorTitle.textContent = hoveredVertex ? "vertex inspector" : "vertex inspector · selected";
    edgeIdEl.textContent = vertex.id;
    edgeDetailEl.textContent = `(${vertex.point.map(fmt).join(", ")}) mm · ${vertex.degree} incident edge${vertex.degree === 1 ? "" : "s"}`;
    edgeOriginEl.hidden = true;
    suggestedSelector = suggestVertexSelector(vertex, visibleVertices);
    edgeSelectorEl.textContent = suggestedSelector
      ? `vertices: ${suggestedSelector}`
      : "no unique directional vertex selector";
    copyEdgeSelector.textContent = "copy vertex selector";
    copyEdgeSelector.disabled = !suggestedSelector;
    copyEdgeSelector.title = suggestedSelector
      ? "Copy a selector for shape.vertices(…); it is re-resolved on each evaluation"
      : "Add a stronger directional condition after changing the model";
    return;
  }

  const edge = hoveredEdge ?? selectedEdge;
  if (!edge) {
    edgeInspector.hidden = true;
    edgeOriginEl.hidden = true;
    suggestedSelector = undefined;
    return;
  }

  edgeInspector.hidden = false;
  entityInspectorTitle.textContent = hoveredEdge ? "edge inspector" : "edge inspector · selected";
  edgeIdEl.textContent = edge.id;
  const direction = edge.direction ? ` · ${directionLabel(edge.direction)}` : "";
  edgeDetailEl.textContent = `${fmt(edge.length_mm)} mm${direction}`;
  const treatment = treatmentForEdge(edge);
  edgeOriginEl.hidden = !treatment;
  if (treatment) {
    const method = treatment.source?.method ?? treatment.kind;
    edgeOriginEl.textContent = `from .${method}(…) · click to lock code`;
  }
  suggestedSelector = suggestEdgeSelector(edge, visibleEdges);
  edgeSelectorEl.textContent = suggestedSelector
    ? `selector: ${suggestedSelector}`
    : "no unique directional selector";
  copyEdgeSelector.textContent = "copy selector";
  copyEdgeSelector.disabled = !suggestedSelector;
  copyEdgeSelector.title = suggestedSelector
    ? "Copy a selector for shape.edges(…); it is re-resolved on each evaluation"
    : "Add a stronger directional condition, or use a future point/adjacency selector";
}

/** The source call whose exact builder history generated this final edge. */
function treatmentForEdge(edge: EdgeCurve): dsl.TreatmentSource | undefined {
  return edge.treatment_node === undefined
    ? undefined
    : lastTreatments.find((treatment) => treatment.node === edge.treatment_node);
}

/** Mark the source call for a final edge without stealing keyboard focus. */
function highlightTreatmentForEdge(edge: EdgeCurve | undefined) {
  const treatment = edge && editor.state.doc.toString() === lastSource
    ? treatmentForEdge(edge)
    : undefined;
  if (!treatment && pinnedTreatment) return;
  const range = treatmentRange(treatment);
  editor.dispatch({ effects: setTreatmentHover.of(range) });
  if (range && !rangeIsVisible(range)) {
    editor.dispatch({ effects: EditorView.scrollIntoView(range.from, { y: "center" }) });
  }
}

function rangeIsVisible(range: { from: number; to: number }): boolean {
  const start = editor.coordsAtPos(range.from);
  const end = editor.coordsAtPos(range.to);
  const pane = editor.scrollDOM.getBoundingClientRect();
  return !!start && !!end && start.top >= pane.top && end.bottom <= pane.bottom;
}

/** Select and reveal a treatment call after its generated edge is clicked. */
function focusTreatmentForEdge(edge: EdgeCurve | undefined) {
  if (!edge || editor.state.doc.toString() !== lastSource) {
    clearPinnedTreatment();
    return;
  }
  const treatment = treatmentForEdge(edge);
  const range = treatmentRange(treatment);
  if (!treatment?.source || !range) {
    clearPinnedTreatment();
    return;
  }

  const start = sourceOffset(lastSource, treatment.source.line, treatment.source.column);
  if (start === undefined) return;
  pinnedTreatment = treatment;
  editor.dispatch({
    selection: { anchor: start, head: start + treatment.source.method.length },
    effects: [
      setTreatmentHover.of(range),
      EditorView.scrollIntoView(start, { y: "center" }),
    ],
  });
}

function treatmentRange(treatment: dsl.TreatmentSource | undefined) {
  return treatment?.source
    ? treatmentCallRange(editor.state, lastSource, treatment.source)
    : undefined;
}

function clearPinnedTreatment() {
  pinnedTreatment = undefined;
  editor.dispatch({ effects: setTreatmentHover.of(undefined) });
}

function directionLabel(direction: [number, number, number]): string {
  const components = direction.map(Math.abs);
  const index = components.indexOf(Math.max(...components));
  return `|${["X", "Y", "Z"][index]}`;
}

/**
 * Derive the shortest `>X`, `<Y`, `|Z` conjunction that identifies this
 * currently visible edge. It is a convenience for the inspector, not a hidden
 * ID: if the geometry later becomes ambiguous, the B-rep evaluator refuses.
 */
function suggestEdgeSelector(edge: EdgeCurve, all: EdgeCurve[]): string | undefined {
  if (all.length === 0) return undefined;
  const axes = ["X", "Y", "Z"] as const;
  const terms: string[] = [];
  const epsilon = 1e-4;

  if (edge.direction) {
    const axis = edge.direction.map(Math.abs).indexOf(Math.max(...edge.direction.map(Math.abs)));
    if (Math.abs(edge.direction[axis]) >= 0.999) terms.push(`|${axes[axis]}`);
  }
  for (let axis = 0; axis < 3; axis++) {
    const values = all.map((candidate) => candidate.center[axis]);
    const maximum = Math.max(...values);
    const minimum = Math.min(...values);
    if (Math.abs(edge.center[axis] - maximum) <= epsilon) terms.push(`>${axes[axis]}`);
    if (Math.abs(edge.center[axis] - minimum) <= epsilon) terms.push(`<${axes[axis]}`);
  }

  const matches = (candidate: EdgeCurve, term: string) => {
    const axis = axes.indexOf(term[1] as (typeof axes)[number]);
    if (term[0] === "|") {
      return candidate.direction !== null && Math.abs(candidate.direction[axis]) >= 0.999;
    }
    const values = all.map((other) => other.center[axis]);
    const extreme = term[0] === ">" ? Math.max(...values) : Math.min(...values);
    return Math.abs(candidate.center[axis] - extreme) <= epsilon;
  };

  const selected: string[] = [];
  let candidates = all;
  while (candidates.length > 1) {
    const currentCount = candidates.length;
    const next = terms
      .filter((term) => !selected.includes(term))
      .map((term) => ({ term, candidates: candidates.filter((candidate) => matches(candidate, term)) }))
      .filter(({ candidates: remaining }) => remaining.length > 0 && remaining.length < currentCount)
      .sort((a, b) => a.candidates.length - b.candidates.length)[0];
    if (!next || next.candidates.length >= candidates.length) break;
    selected.push(next.term);
    candidates = next.candidates;
  }

  return candidates.length === 1 && selected.length > 0 ? selected.join(" and ") : undefined;
}

copyEdgeSelector.addEventListener("click", async () => {
  if (!suggestedSelector || !navigator.clipboard) return;
  try {
    await navigator.clipboard.writeText(suggestedSelector);
    setStatus(`copied ${suggestedSelector}`);
  } catch {
    setStatus("could not copy selector", "failed");
  }
});

const fmt = (v: number) =>
  Math.abs(v) >= 1000 ? v.toFixed(0) : v.toFixed(2).replace(/\.00$/, "");

/**
 * The three things the status line can be, as colour.
 *
 * A lookup rather than a class name assembled from a string: the set is closed,
 * and Tailwind can only emit a utility it can see written out somewhere.
 */
const TONE = {
  "": "text-ink-dim",
  busy: "text-accent",
  failed: "text-bad",
} as const;

function setStatus(text: string, cls: keyof typeof TONE = "") {
  statusEl.textContent = text;
  statusEl.className = `font-mono text-small ${TONE[cls]}`;
}

function showError(e: unknown) {
  errorEl.textContent = e instanceof Error ? e.message : String(e);
  errorEl.hidden = false;
  // Leave the last good geometry on screen. A broken edit mid-typing should not
  // blank the viewport — but only while that geometry is still this part's.
  // Once another part is open, the solid and every measurement beside it
  // describe something the titlebar is no longer naming, and a stale volume
  // presented under a new name is the confident wrong answer this project
  // refuses to give.
  if (shownPath !== openPath) {
    discardShownPart();
  }
}

/** Drop the rendered part and everything measured from it. */
function discardShownPart() {
  shownPath = undefined;
  lastSnapshot = undefined;
  lastGraph = null;
  lastSource = "";
  lastTreatments = [];
  visibleEdges = [];
  visibleVertices = [];
  hoveredEdge = undefined;
  selectedEdge = undefined;
  hoveredVertex = undefined;
  selectedVertex = undefined;
  suggestedSelector = undefined;
  resolvedTargets.clear();
  viewport.clearPart();
  // Nothing measured is left to report, so the panel goes away rather than
  // standing empty — its border and backdrop are visible with no text in them.
  // No placeholder either: the error beside it already says why there is no part.
  reportEl.innerHTML = "";
  reportEl.hidden = true;
}

function clearError() {
  errorEl.hidden = true;
  errorEl.textContent = "";
}

// ------------------------------------------------------------------- chrome

depthInput.addEventListener("input", () => {
  depthValue.textContent = depthInput.value;
  schedule();
});

// ------------------------------------------------------------------ section

/** The part's extent, so the plane can only travel where there is material. */
let sectionBounds: { min: Vec3; max: Vec3 } | undefined;
/** Which half survives. Chosen from the camera when an axis is picked; the flip
 *  button is the override, and it sticks until the axis changes again. */
let sectionKeep: "below" | "above" = "below";

/**
 * Re-fit the slider to the current part, keeping the plane where it was.
 *
 * Both halves matter. Re-fitting is what makes one slider work for a 6 mm part
 * and a 600 mm one; keeping the position is what stops a section jumping to the
 * middle of the part on every keystroke, which is the difference between a
 * usable section and one you have to re-aim after every edit.
 */
function retuneSection() {
  const axis = sectionAxis.value as "" | "x" | "y" | "z";
  const enabled = axis !== "" && sectionBounds !== undefined;

  sectionAt.disabled = !enabled;
  sectionFlip.disabled = !enabled;
  if (!enabled) {
    sectionAtValue.textContent = "";
    viewport.setSection(undefined);
    return;
  }

  const min = sectionBounds!.min[axis];
  const max = sectionBounds!.max[axis];
  sectionAt.min = String(min);
  sectionAt.max = String(max);
  // A hundred steps across the part: fine enough to walk a plane through a
  // 2 mm wall, coarse enough that dragging it is not a slideshow.
  sectionAt.step = String(Math.max((max - min) / 100, 1e-4));

  const at = Math.min(Math.max(Number(sectionAt.value), min), max);
  sectionAt.value = String(at);
  sectionAtValue.textContent = `${at.toFixed(1)} mm`;

  const plane: SectionPlane = { axis, atMm: at, keep: sectionKeep };
  viewport.setSection(plane);
}

sectionAxis.addEventListener("change", () => {
  // A fresh axis starts in the middle of the part, where a section is most
  // likely to cross something worth seeing — the same default the kernel picks
  // when an agent names an axis and no position.
  if (sectionBounds && sectionAxis.value !== "") {
    const axis = sectionAxis.value as "x" | "y" | "z";
    sectionAt.value = String((sectionBounds.min[axis] + sectionBounds.max[axis]) / 2);
    // Open it facing the camera. Keeping the near half instead puts the cut on
    // the far side of the material, which looks exactly like no section at all.
    sectionKeep = viewport.keepFacingCamera(axis);
  }
  retuneSection();
});
sectionAt.addEventListener("input", retuneSection);
sectionFlip.addEventListener("click", () => {
  sectionKeep = sectionKeep === "below" ? "above" : "below";
  retuneSection();
});

backendSelect.addEventListener("change", () => {
  syncBackendUi();
  // A backend swap changes the geometry, not the part, so the camera stays.
  schedule();
});

/** B-rep meshes to a fixed deflection; its solid and triangle views have no grid. */
function syncBackendUi() {
  const brepMesh = backendSelect.value === "brep" || backendSelect.value === "preview";
  depthInput.disabled = brepMesh;
  // `aria-disabled` rather than a class: the label is dimmed *because* the
  // control under it is off, and one attribute says both to the stylesheet and
  // to a screen reader.
  depthInput.parentElement!.ariaDisabled = String(brepMesh);
  depthInput.parentElement!.title = brepMesh
    ? "B-rep meshes to a fixed 0.01 mm deflection; there is no grid to coarsen"
    : "";
}
syncBackendUi();

// ---------------------------------------------------------------- MCP status

/**
 * Whether a model is on the third transport, refreshed on a timer.
 *
 * An agent reaches the same `service.rs` this window does and writes to the
 * same project folder, and nothing on screen would otherwise say so: the part
 * you are looking at can be replaced under you by a caller you cannot see.
 *
 * Everything shown here is measured — a request that arrived, a tool that was
 * called — which is why an idle client is reported with the age of its last
 * call rather than as a flat "connected". A client that was killed cannot say
 * goodbye, and claiming it is still there would be the confident wrong answer
 * this codebase refuses everywhere else.
 */
const MCP_POLL_MS = 4000;
/** Below this, the last call is recent enough to call the agent active. */
const MCP_ACTIVE_SECS = 20;

async function pollMcp() {
  let mcp: backend.McpStatus;
  try {
    mcp = await backend.mcpStatus();
  } catch {
    // The host answers this window's every other call too, so a failure here is
    // not an MCP fact and must not be shown as one.
    mcpEl.hidden = true;
    return;
  }

  const chip = mcpChip(mcp);
  mcpEl.hidden = false;
  mcpEl.className = `${MCP_CHIP} ${chip.tone}`;
  mcpEl.textContent = chip.text;
  mcpEl.title = chip.detail;
}

/**
 * The chip's shape, and the dot in front of it.
 *
 * The dot is `bg-current`, so saying the chip is green says the dot is green
 * once. Only its opacity changes with the tone below — dim when nobody is
 * there, solid when somebody is.
 */
const MCP_CHIP =
  "flex items-center gap-1.5 mr-3.5 font-mono text-small cursor-default " +
  "before:content-[''] before:size-[7px] before:rounded-full before:bg-current";
const MCP_TONE = {
  live: "text-good before:opacity-100",
  busy: "text-accent before:opacity-100",
  idle: "text-ink-dim before:opacity-50",
} as const;

/** One status, as the three things the chip shows. */
function mcpChip(mcp: backend.McpStatus): { text: string; tone: string; detail: string } {
  const idle = mcp.idle_secs;
  const working = idle !== null && idle < MCP_ACTIVE_SECS;

  // The chip says connected or not; the session count stays in the tooltip,
  // where there is room to say what it means. A client that reconnects opens a
  // second session and the endpoint cannot tell that from a second client, so
  // "3 sessions" on the chip would read as three agents.
  let text = "MCP";
  let tone: string = MCP_TONE.idle;
  if (mcp.clients > 0) {
    text = working ? "MCP connected · working" : `MCP connected · idle ${age(idle!)}`;
    tone = working ? MCP_TONE.busy : MCP_TONE.live;
  } else if (idle !== null) {
    text = `MCP last call ${age(idle)} ago`;
  }

  const lines = [
    mcp.clients > 0
      ? `${mcp.clients} open session${mcp.clients === 1 ? "" : "s"} — a client that reconnects opens another`
      : "no agent connected",
    `endpoint ${mcp.url}`,
  ];
  if (mcp.client) lines.push(`client ${mcp.client}`);
  if (mcp.tool_calls === 0) {
    lines.push("no tool calls yet");
  } else {
    const calls = `${mcp.tool_calls} tool call${mcp.tool_calls === 1 ? "" : "s"}`;
    lines.push(mcp.last_tool ? `${calls}, last ${mcp.last_tool}` : calls);
  }
  lines.push("An agent writes to the same project folder this window reads.");

  return { text, tone, detail: lines.join("\n") };
}

function age(seconds: number): string {
  if (seconds < 60) return `${Math.round(seconds)}s`;
  if (seconds < 3600) return `${Math.round(seconds / 60)}m`;
  return `${Math.round(seconds / 3600)}h`;
}

pollMcp();
window.setInterval(pollMcp, MCP_POLL_MS);

// --------------------------------------------------------------- the part

/**
 * Which project is open, and whether the editor still matches what is on disk.
 *
 * The project folder is shared with the user's filesystem and with agents over
 * MCP, so "the file I opened" and "the text in front of me" genuinely can
 * disagree without anybody typing. The titlebar says which.
 */
let openPath: string | undefined;
/** The source as last read from or written to disk, to tell dirty from clean. */
let savedSource = "";

const projectButton = $<HTMLButtonElement>("project");
const projectName = $("project-name");
const saveButton = $<HTMLButtonElement>("save");

const browser = mountProjectBrowser({
  open: openProject,
  current: () => openPath,
  changed: (path) => {
    openPath = path;
    showOpenPart();
  },
});

projectButton.addEventListener("click", () => void browser.show());
saveButton.addEventListener("click", () => void saveOpenPart());

/** Load a part into the editor, replacing whatever is there. */
async function openProject(path: string) {
  const source = await backend.readProject(path);
  editor.dispatch({ changes: { from: 0, to: editor.state.doc.length, insert: source } });
  openPath = path;
  savedSource = source;
  framed = false;
  clearError();
  showOpenPart();
}

/** The titlebar: which part, and whether it is saved. */
function showOpenPart() {
  const part = openPath ? partAt(browser.known()?.tree ?? [], openPath) : undefined;
  const label = part?.title ?? (openPath ? projectLabel(openPath) : "no part");
  const changed = openPath !== undefined && editor.state.doc.toString() !== savedSource;

  projectName.textContent = label;
  projectButton.title = openPath
    ? `${openPath} — click to browse parts (⌘O)`
    : "Browse parts (⌘O)";
  saveButton.disabled = openPath === undefined || !changed;
  saveButton.textContent = changed ? "save •" : "saved";
}

/**
 * Write the part, and the two files that describe it, together.
 *
 * The description is built from the *measured* report rather than from the
 * script, and says which kernel measured it — a README claiming dimensions
 * nobody evaluated is the confident wrong answer this project refuses. If the
 * current source has not evaluated cleanly, the script is still saved and the
 * description is left alone rather than being rewritten from stale numbers.
 */
async function saveOpenPart() {
  if (!openPath) return;
  const source = editor.state.doc.toString();
  const clean = source === lastSource && lastSnapshot !== undefined;

  setStatus("saving", "busy");
  try {
    await backend.saveProject(openPath, source, {
      readme: clean ? readmeFor(openPath, source) : undefined,
      preview: clean ? viewport.snapshot() || undefined : undefined,
    });
    savedSource = source;
    await browser.reload();
    showOpenPart();
    setStatus(clean ? "saved" : "saved — description left as it was");
  } catch (e) {
    showError(e);
    setStatus("could not save", "failed");
  }
}

/**
 * Give a part its first thumbnail, once, from the part as it is on disk.
 *
 * Without this a picker of thumbnails shows nothing until each part has been
 * edited and saved, which is backwards: the parts worth seeing are the ones
 * nobody has touched yet. Only when the editor still matches the file — a
 * picture of a half-typed edit would be a picture of something that is not
 * there — and only when the bundle has none, so it never fights a saved one.
 */
async function captureFirstThumbnail() {
  if (!openPath || editor.state.doc.toString() !== savedSource) return;
  const part = partAt(browser.known()?.tree ?? [], openPath);
  if (!part?.bundle || part.thumbnail) return;

  const png = viewport.snapshot();
  if (!png) return;
  try {
    await backend.saveProjectPreview(openPath, png);
    await browser.reload();
  } catch {
    // A thumbnail nobody asked for must not become an error anybody sees.
  }
}

/** What a reader of the folder finds beside the script. */
function readmeFor(path: string, source: string): string {
  const snapshot = lastSnapshot!;
  const [sx, sy, sz] = snapshot.size;
  // The author's own opening comment says what the part is for; nothing
  // generated here could say it better. Only the *leading* block: comments
  // further down explain one step and read as non-sequitur out of context.
  const lines = source.split("\n");
  const intro: string[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed && intro.length === 0) continue;
    if (!trimmed.startsWith("//")) break;
    intro.push(trimmed.replace(/^\/+\s?/, ""));
  }

  const kernel =
    snapshot.backend === "brep" ? "the exact B-rep kernel" : "the implicit backend";
  return [
    `# ${partAt(browser.known()?.tree ?? [], path)?.title ?? projectLabel(path)}`,
    "",
    ...(intro.length ? [intro.join("\n"), ""] : []),
    "## Measured",
    "",
    `- **${fmt(sx)} × ${fmt(sy)} × ${fmt(sz)} mm**`,
    `- volume ${fmt(snapshot.volume_mm3)} mm³, area ${fmt(snapshot.area_mm2)} mm²`,
    ...(snapshot.faces !== undefined
      ? [`- ${snapshot.faces} faces, ${snapshot.topological_edges} edges`]
      : []),
    `- mesh ${snapshot.triangles.toLocaleString()} triangles, ` +
      (snapshot.watertight
        ? "watertight"
        : `NOT watertight — ${snapshot.non_manifold_edges} bad edges`),
    ...(snapshot.tags.length ? [`- tags: ${snapshot.tags.join(", ")}`] : []),
    "",
    `Measured by ${kernel} when this part was last saved, not read off the ` +
      "script. `part.js` beside this file is the source and the only thing here " +
      "that is authoritative — rebuild it rather than trusting these numbers if " +
      "it has been edited since.",
    "",
  ].join("\n");
}

/**
 * Fill the titlebar and open a part.
 *
 * Evaluation is deliberately not started before this resolves: running the
 * empty document would report "the script must return a shape", which is true
 * and useless as a first impression.
 */
async function start() {
  setStatus("loading projects", "busy");
  let projects;
  try {
    projects = describeProjects(await backend.listProjects());
    await browser.reload();
  } catch (e) {
    showError(e);
    setStatus("failed", "failed");
    return;
  }

  if (!projects.initial) {
    setStatus("no projects");
    showOpenPart();
    showError(
      new Error(
        `parcad's project folder is empty:\n  ${projects.directory}\n` +
          "Use New part in the picker, or put a .js file in that folder.",
      ),
    );
    return;
  }

  await openProject(projects.initial);
  run();
}

// ------------------------------------------------------------- live session

/**
 * This window's identity in the shared session, minted fresh per load.
 *
 * Its one job is to break the echo loop: every change this window pushes
 * carries it, and the handler below drops any broadcast carrying it back. Two
 * tabs and the desktop window each apply the others' changes and never their
 * own reflection. An agent's edits carry "agent", which no window owns, so
 * they are applied everywhere — which is the point of the session.
 *
 * Not `crypto.randomUUID()`: that only exists in a secure context, and whether
 * a Tauri webview's origin counts as one is a platform detail this constant
 * must not depend on. A module-level throw here would take the whole editor
 * down, in the desktop window only, with nothing on screen to say why.
 */
const viewerId = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;

backend.subscribeSession((session) => {
  if (session.origin === viewerId) return;

  const current = editor.state.doc.toString();
  const opened = (session.name ?? undefined) !== openPath;
  if (opened) {
    openPath = session.name ?? undefined;
    // A name change means someone opened a project, so the script beside it is
    // what the disk had at that moment — the saved text, not a dirty edit.
    savedSource = session.script;
    framed = false;
    clearError();
  }

  if (current !== session.script) {
    // An ordinary edit, deliberately: dispatched like typing, it lands in the
    // normal undo history and Cmd-Z takes an agent's change back exactly like
    // the user's own. Only the differing span is replaced, so a cursor outside
    // it stays put while the user keeps typing. The dispatch triggers the same
    // docChanged path as a keystroke — titlebar, debounce, push — and the push
    // of an applied change is a no-op on the host, which ends the ripple.
    let from = 0;
    const next = session.script;
    while (from < current.length && from < next.length && current[from] === next[from]) from++;
    let toCurrent = current.length;
    let toNext = next.length;
    while (toCurrent > from && toNext > from && current[toCurrent - 1] === next[toNext - 1]) {
      toCurrent--;
      toNext--;
    }
    editor.dispatch({ changes: { from, to: toCurrent, insert: next.slice(from, toNext) } });
  } else if (opened) {
    // Same text, different part — a rename-shaped case the dispatch above
    // would otherwise cover. The titlebar and evaluation still need to follow.
    showOpenPart();
    schedule();
  }
});

// Draggable split between editor and viewport.
{
  const splitter = $("splitter");
  const pane = $("editor-pane");
  let dragging = false;

  splitter.addEventListener("pointerdown", (e) => {
    dragging = true;
    splitter.setPointerCapture(e.pointerId);
  });
  splitter.addEventListener("pointermove", (e) => {
    if (!dragging) return;
    const pct = (e.clientX / window.innerWidth) * 100;
    pane.style.width = `${Math.min(75, Math.max(15, pct))}%`;
  });
  splitter.addEventListener("pointerup", (e) => {
    dragging = false;
    splitter.releasePointerCapture(e.pointerId);
  });
}

/**
 * Keys.
 *
 * ⌘S saves the part. It used to export STL, from when there was nothing on
 * disk to save and the only file the app could produce was a mesh; now that a
 * part is a project the conventional meaning is the right one, and exports
 * moved to ⌘E. ⇧ picks the exact format: STEP needs the B-rep kernel whatever
 * the viewport happens to be showing, because a mesh cannot be turned back into
 * exact surfaces after the fact.
 */
window.addEventListener("keydown", async (e) => {
  if (!(e.metaKey || e.ctrlKey)) return;
  const key = e.key.toLowerCase();

  if (key === "o") {
    e.preventDefault();
    void browser.show();
    return;
  }
  if (key === "s") {
    e.preventDefault();
    await saveOpenPart();
    return;
  }
  if (key !== "e") return;

  e.preventDefault();
  if (!lastGraph) return;
  const step = e.shiftKey;
  setStatus(step ? "exporting STEP" : "exporting STL", "busy");
  try {
    const name = step
      ? await backend.exportStep(lastGraph)
      : await backend.exportStl(lastGraph, Number(depthInput.value), backendSelect.value);
    setStatus(`exported ${name}`);
    clearError();
  } catch (err) {
    showError(err);
    setStatus("export failed", "failed");
  }
});

start();
