/**
 * Everything the window shares, as signals.
 *
 * The choice worth explaining is signals rather than component state, because
 * the obvious React shape would be wrong here. This app has one document and
 * one evaluation of it, and about eight places that need to read them: the
 * report, the titlebar's saved mark, the inspector, the section's travel, the
 * editor's own decorations, the exporter. Threading that through props would
 * put the whole application state in a root component and re-render the
 * viewport pane every time a hover changed a caption.
 *
 * More to the point, the evaluation cycle is not a render. It is a small state
 * machine — running, dirty, coalesce, re-enter — that predates this file and
 * has a debounce, an in-flight guard and an echo-breaking viewer id in it.
 * Signals let that machine stay exactly what it was and simply be *observed*,
 * which is the whole reason the port to Preact could be mechanical instead of a
 * rewrite of the part that is easiest to break quietly.
 *
 * The rule that keeps it honest: **nothing here computes a measurement.** Every
 * number a person reads comes out of `snapshot`, which is the object
 * `service.rs` built and every transport serialises. A signal in this file may
 * hold it, select it or say it is stale. It may not derive one.
 */

import { computed, signal } from "@preact/signals";
import type { EditorView } from "codemirror";
import type * as dsl from "./dsl";
import type { McpStatus } from "./backend";
import type { VertexPoint } from "./entities";
import type { Projects } from "./projects";
import type { Viewport } from "./viewport";

/**
 * One evaluation, as the host measured it.
 *
 * The same object, field for field, that an agent gets back from MCP's
 * `evaluate_part`: `service.rs` builds exactly one of these per evaluation and
 * every transport serialises it. Nothing in the frontend may compute a
 * measurement of its own — this window and a model looking at the same part
 * have to be reading the same numbers, and the only way to guarantee that is to
 * have one producer.
 *
 * Millimetres throughout. Triples are `[x, y, z]`.
 */
export interface EvaluationSnapshot {
  units: string;
  size: [number, number, number];
  bounds_min: [number, number, number];
  bounds_max: [number, number, number];
  volume_mm3: number;
  area_mm2: number;
  centroid: [number, number, number];
  /** Exact-kernel counts. Absent for the implicit backend and for a mesh
   *  preview, where the question does not apply — different from zero. */
  faces?: number;
  topological_edges?: number;
  triangles: number;
  resolution_mm: number;
  watertight: boolean;
  non_manifold_edges: number;
  /** Free-standing pieces of surface; one for a part. */
  bodies: number;
  /** Closed surfaces inside another: a shell's cavity. */
  voids: number;
  /** The surface in the part's lowest plane and how many patches it is in;
   *  what a printed part rests on. Absent only for an empty mesh. */
  stands_on?: {
    z_mm: number;
    area_mm2: number;
    patches: number;
    footprint_fraction: number;
    tolerance_mm: number;
  };
  tags: string[];
  treatments: { node: number; op: string; amount_mm: number; continuity?: string }[];
  /** Shapes the root never reaches. Absent when there are none. */
  unused_nodes?: number;
  backend: "implicit" | "brep";
  kernel_ms: number;
}

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

export type Bounds = { min: Vec3; max: Vec3 };

/** A visible B-rep edge. `id` is valid only for this evaluated result. */
export interface EdgeCurve {
  id: string;
  points: number[][];
  center: [number, number, number];
  direction: [number, number, number] | null;
  length_mm: number;
  /** Ephemeral source node when this final edge was generated by a treatment. */
  treatment_node?: number;
}

/**
 * One face's triangles, as a span of the shared index buffer.
 *
 * `start` and `count` are in triangles, not indices. `face` is the face's
 * position in the kernel's own face traversal — the order `snapshot.faces`
 * counts — and deliberately not this run's position in the list: a face
 * carrying no triangulation contributes no run, so the two disagree exactly
 * where using the wrong one would still add up to a plausible total.
 */
export interface FaceRun {
  face: number;
  start: number;
  count: number;
}

/**
 * What one face is, measured off the B-rep rather than off its triangles.
 *
 * Position in `Evaluated.faces` is the face's own number — the same one
 * `FaceRun.face` carries — so the face under the pointer and the face described
 * here are the same face.
 */
export interface FaceSummary {
  area_mm2: number;
  centroid: [number, number, number];
  /** Faces sharing an edge with this one, by the same numbering. */
  adjacent: number[];
  surface: {
    /** `plane`, `cylinder`, `cone`, `sphere`, `torus`, `nurbs`, `other`. */
    kind: string;
    /** A plane's outward normal, or the axis of anything turned about one. */
    direction?: [number, number, number];
    radius?: number;
  };
}

export interface Evaluated {
  positions: number[];
  normals: number[];
  indices: number[];
  /** Logical edge curves. Omitted in mesh-preview mode. */
  edges: EdgeCurve[];
  /**
   * Where each face's triangles sit in `indices`, and which face each run is.
   *
   * Absent for the implicit backend and for a mesh preview, which have no faces
   * to attribute a triangle to — the viewport treats that as "faces are not
   * pickable here" rather than guessing at one.
   */
  face_runs?: FaceRun[];
  /** What each face is. Indexed by the kernel's own face number. */
  faces?: FaceSummary[];
  snapshot: EvaluationSnapshot;
  /** The implicit path's two halves. Kernel time is in the snapshot. */
  timings: {
    lower_and_mesh_ms: number;
    normals_ms: number;
  };
}

export interface TargetPreview {
  node: number;
  edges: EdgeCurve[];
  vertices: { id: string; point: [number, number, number]; degree: number }[];
  /** Tags whose live edge set is exactly this target, from the kernel. */
  provenance?: string[];
}

// ------------------------------------------------------------------ the part

/**
 * Which project is open, and whether the editor still matches what is on disk.
 *
 * The project folder is shared with the user's filesystem and with agents over
 * MCP, so "the file I opened" and "the text in front of me" genuinely can
 * disagree without anybody typing. The titlebar says which.
 */
export const openPath = signal<string | undefined>(undefined);
/** The source as last read from or written to disk, to tell dirty from clean. */
export const savedSource = signal("");
/** What is in the editor right now, updated on the keystroke. */
export const docSource = signal("");
/** The parts on disk, as of the last read. */
export const projects = signal<Projects | undefined>(undefined);

export const isDirty = computed(
  () => openPath.value !== undefined && docSource.value !== savedSource.value,
);

// ------------------------------------------------------------ the evaluation

/** The last measurements, kept so a save can describe the part it saved. */
export const snapshot = signal<EvaluationSnapshot | undefined>(undefined);
/** The last graph that evaluated cleanly, kept for export. */
export const lastGraph = signal<dsl.Doc | null>(null);
export const lastSource = signal("");
export const lastTreatments = signal<dsl.TreatmentSource[]>([]);
export const visibleEdges = signal<EdgeCurve[]>([]);
export const visibleVertices = signal<VertexPoint[]>([]);
/** How many final curves this evaluation traced back to an authored call. */
export const linkedEdgeCount = signal(0);
export const linkedMethods = signal<string[]>([]);

/** The part's own extent, so a section plane can only travel where there is
 *  material. Undefined once there is no part on screen. */
export const bounds = signal<Bounds | undefined>(undefined);

// -------------------------------------------------------------- the chrome

export type Tone = "" | "busy" | "failed";
export const status = signal<{ text: string; tone: Tone }>({ text: "ready", tone: "" });
export const errorText = signal("");

/** Whether a model is on the third transport. Undefined until first answered. */
export const mcp = signal<McpStatus | undefined>(undefined);

// ------------------------------------------------------------- the selection

/**
 * The face under the pointer, when the exact kernel attributed one.
 *
 * `face` is the kernel's own face number, which is ephemeral in exactly the way
 * `edge@7` is — it is shown as a position within a count, never offered as
 * something to write into a script.
 */
export const hoveredFace = signal<{ face: number; triangles: number } | undefined>(undefined);

/** What the hovered face is, when the kernel described it. */
export const hoveredFaceSummary = computed(() =>
  hoveredFace.value ? lastFaces.value?.[hoveredFace.value.face] : undefined,
);

/**
 * The face descriptions of the part on screen.
 *
 * Kept beside the viewport's own copy rather than read back out of it: the
 * viewport owns triangles, and this is the measurement of what those triangles
 * are. See the island rule in CLAUDE.md.
 */
export const lastFaces = signal<FaceSummary[] | undefined>(undefined);

export const hoveredEdge = signal<EdgeCurve | undefined>(undefined);
export const selectedEdge = signal<EdgeCurve | undefined>(undefined);
export const hoveredVertex = signal<VertexPoint | undefined>(undefined);
export const selectedVertex = signal<VertexPoint | undefined>(undefined);

/** What the caret's treatment resolves to, once the kernel has answered. */
export const targetPreview = signal<
  { method: string; detail: string; resolved: boolean } | undefined
>(undefined);

// ------------------------------------------------------------- the view

/** Which kernel evaluates the graph, in the spelling `backend.evaluate` wants. */
export const kernel = signal("brep");

/**
 * The sampling depth the evaluate call still carries, and why it is a constant.
 *
 * `service.rs` takes a depth because its *implicit* backend samples a distance
 * field on a grid. This window never selects that backend: both of the kernels
 * it offers — `brep` and `preview` — mesh an exact solid, which the host states
 * itself in `Backend::is_exact`, "no grid to coarsen and no use for a requested
 * depth". Preview meshes the B-rep on purpose, so the window cannot invent or
 * omit geometry relative to the solid model.
 *
 * There used to be a detail slider in the titlebar wired to this. It moved a
 * number that nothing read, in either mode, every time it was dragged — the
 * exact shape of confident wrongness this project refuses everywhere else — so
 * it is gone rather than dimmed. If the implicit backend is ever offered here
 * again, this becomes a signal again and the control comes back with it.
 */
export const DEPTH = 7;
export const sectionAxis = signal<"" | "x" | "y" | "z">("");
export const sectionAt = signal(0);
export const sectionKeep = signal<"below" | "above">("below");

// -------------------------------------------------------------- the editor

/**
 * The live CodeMirror view.
 *
 * Not a signal: it is an identity rather than a value, nothing re-renders when
 * it changes, and it is set exactly once when the editor island mounts. A box
 * rather than a bare `let` so importers see the assignment.
 */
export const editorRef: { current: EditorView | undefined } = { current: undefined };

/** The editor, or a loud failure. Called only from paths that need one. */
export function editor(): EditorView {
  if (!editorRef.current) throw new Error("the editor is not mounted yet");
  return editorRef.current;
}

/**
 * The live three.js scene, for the same reason and on the same terms.
 *
 * Both islands own DOM that a virtual DOM must not touch: CodeMirror maintains
 * its own view of the document, and three.js owns a canvas. They are mounted by
 * components, which is where the element comes from, and reached from the
 * machinery below through these boxes.
 */
export const viewportRef: { current: Viewport | undefined } = { current: undefined };

/** Whether the parts picker is open. */
export const browserOpen = signal(false);

export function setStatus(text: string, tone: Tone = "") {
  status.value = { text, tone };
}
