/**
 * The 3D viewport.
 *
 * This is a different renderer from the one the agent looks through, on purpose.
 * The agent's renders are CPU raymarched at a fixed small size for a vision
 * model; this one is GPU triangles at native display resolution, and its job is
 * to be smooth under the mouse. Sharing one renderer between the two would make
 * both worse.
 */

import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";
import { verticesFromEdges, type VertexPoint } from "./entities";
import { OutlineRenderer } from "./outline";

export interface Geometry {
  positions: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
  /**
   * Logical edges as polylines, when the backend knows what they are.
   *
   * The implicit backend cannot supply these, and the difference is visible: a
   * screen-space pass can only ever *guess* where an edge is from the pixels
   * around it, while these are the curve itself.
   */
  edges?: EdgeCurve[];
}

/** A logical B-rep edge returned by the exact backend. */
export interface EdgeCurve {
  /** Ephemeral identifier for this evaluated model, for inspection only. */
  id: string;
  points: number[][];
  center: [number, number, number];
  direction: [number, number, number] | null;
  length_mm: number;
  /** Ephemeral source node for a final edge generated by a treatment. */
  treatment_node?: number;
}

/** An exact corner selected by a source-to-viewport target preview. */
export interface TargetVertex {
  /** Ephemeral ID for this preview only; never a modelling-language input. */
  id: string;
  point: [number, number, number];
}

export interface EdgeCallbacks {
  onHover?: (edge: EdgeCurve | undefined) => void;
  onSelect?: (edge: EdgeCurve | undefined) => void;
  onVertexHover?: (vertex: VertexPoint | undefined) => void;
  onVertexSelect?: (vertex: VertexPoint | undefined) => void;
}

export interface Bounds {
  min: { x: number; y: number; z: number };
  max: { x: number; y: number; z: number };
}

/** Fusion-style light canvas: dark chrome, bright work area. */
const BG_TOP = "#e8ecf1";
const BG_BOTTOM = "#c3ccd8";

/**
 * Diagnostic modes, via `?debug=` in the URL.
 *
 * `normals` paints the raw normal field, which separates "the normals are noisy"
 * from "the surface is bumpy" — the two look alike once shaded.
 */
const DEBUG = new URLSearchParams(location.search).get("debug") ?? "";

/** How far the pointer may travel between down and up and still be a click. */
const DRAG_SLOP_PX = 4;

export class Viewport {
  private readonly renderer: THREE.WebGLRenderer;
  private readonly scene = new THREE.Scene();
  private readonly camera: THREE.PerspectiveCamera;
  private readonly controls: OrbitControls;
  private readonly partGroup = new THREE.Group();
  private readonly sun: THREE.DirectionalLight;
  private ambient!: THREE.HemisphereLight;
  private outline!: OutlineRenderer;
  /** @internal exposed for debugging */
  readonly debugScene = () => this.scene;
  private grid?: THREE.GridHelper;
  private ground?: THREE.Mesh;
  private frame = 0;
  /** True while showing a mesh preview rather than a solid with real edges. */
  private preview = false;
  private readonly edgeRaycaster = new THREE.Raycaster();
  private readonly edgeLines: THREE.LineSegments[] = [];
  private readonly vertexRaycaster = new THREE.Raycaster();
  private readonly vertexMarkers: THREE.Points[] = [];
  /** Gold source-selected entities, separate from the pickable final topology. */
  private targetPreview?: THREE.Group;
  private hoveredEdge?: THREE.LineSegments;
  private selectedEdge?: THREE.LineSegments;
  private hoveredVertex?: THREE.Points;
  private selectedVertex?: THREE.Points;
  /** Where the pointer went down, to tell a click apart from an orbit drag. */
  private pointerDownAt?: { x: number; y: number };
  /** Set by the ResizeObserver; applied by the frame that then draws. */
  private pendingResize = false;

  constructor(
    private readonly container: HTMLElement,
    private readonly edgeCallbacks: EdgeCallbacks = {},
  ) {
    this.renderer = new THREE.WebGLRenderer({ antialias: true });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    this.renderer.shadowMap.enabled = true;
    this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    // Without tone mapping, anything approaching full brightness clips to a flat
    // white patch and the shape reads as a silhouette with a hole in it.
    this.renderer.toneMapping = THREE.ACESFilmicToneMapping;
    this.renderer.toneMappingExposure = 1.0;
    container.appendChild(this.renderer.domElement);

    this.scene.background = gradientTexture();

    this.camera = new THREE.PerspectiveCamera(38, 1, 0.1, 100000);
    // Z is up, as everywhere else in this project.
    this.camera.up.set(0, 0, 1);
    this.camera.position.set(120, -160, 110);

    this.controls = new OrbitControls(this.camera, this.renderer.domElement);
    this.controls.enableDamping = true;
    this.controls.dampingFactor = 0.12;

    this.renderer.domElement.addEventListener("pointermove", this.pickEntity);
    // WKWebView's WebDriver endpoint currently emits mouse events for an
    // automated hover. Handling both keeps the real pointer interaction intact
    // while making that native desktop path inspectable in regression tests.
    // `setHovered…` is idempotent, so browsers that emit both do no extra work.
    this.renderer.domElement.addEventListener("mousemove", this.pickEntity);
    this.renderer.domElement.addEventListener("pointerleave", () => {
      this.setHoveredEdge();
      this.setHoveredVertex();
    });
    // A click selects, and a selection outlives the pointer leaving the entity —
    // otherwise the only way to look at an edge is to keep the mouse on it.
    // An orbit drag ends in a `click` on the canvas as well, and that click
    // lands wherever the pointer stopped: without the distance test, rotating
    // the view to see the selected edge from behind is what deselects it.
    this.renderer.domElement.addEventListener("pointerdown", (event) => {
      this.pointerDownAt = { x: event.clientX, y: event.clientY };
    });
    this.renderer.domElement.addEventListener("click", (event) => {
      const down = this.pointerDownAt;
      this.pointerDownAt = undefined;
      if (down && Math.hypot(event.clientX - down.x, event.clientY - down.y) > DRAG_SLOP_PX) return;
      this.setSelectedVertex(this.hoveredVertex);
      this.setSelectedEdge(this.hoveredVertex ? undefined : this.hoveredEdge);
    });

    this.scene.add(this.partGroup);
    this.scene.add(this.camera);

    // Image-based lighting does most of the work. A standard material with no
    // environment to reflect has nothing to shade *with*, which is what makes
    // untouched three.js scenes look like flat grey plastic.
    const pmrem = new THREE.PMREMGenerator(this.renderer);
    pmrem.compileEquirectangularShader();
    this.scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
    this.scene.environmentIntensity = 0.62;

    // One fixed sun for directional definition and the cast shadow. Fixed rather
    // than camera-attached: a shadow that swings around as you orbit reads as the
    // part moving, not the camera.
    this.sun = new THREE.DirectionalLight(0xffffff, 1.9);
    this.sun.position.set(-0.5, -0.9, 1.4);
    this.sun.castShadow = true;
    this.sun.shadow.mapSize.set(2048, 2048);
    this.sun.shadow.bias = -0.0012;
    this.scene.add(this.sun);
    this.scene.add(this.sun.target);

    // A weak fill that rides with the camera, so faces turned away from the sun
    // stay readable instead of going black when you orbit behind them.
    const fill = new THREE.DirectionalLight(0xc9d6ee, 0.45);
    fill.position.set(0, 0, 1);
    this.camera.add(fill);
    // A DirectionalLight aims from its position at its *target*, and the target
    // defaults to the world origin — so parenting only the light to the camera
    // leaves it pointing at the scene centre and the fill stops being a fill.
    // The target has to travel with it.
    fill.target.position.set(0, 0, -1);
    this.camera.add(fill.target);

    // Ambient sky/ground light, on only for the preview. The finished view gets
    // its ambient from the environment map, but that is a physically-based
    // feature the preview's cheap material cannot see — without this, any face
    // turned away from the sun goes almost black.
    this.ambient = new THREE.HemisphereLight(0xdfe7f2, 0x6c7382, 2.1);
    this.ambient.visible = false;
    this.scene.add(this.ambient);

    this.outline = new OutlineRenderer(this.renderer, this.scene, this.camera);

    // Resizing is *recorded* here and applied by the frame that draws next.
    // Doing it inline leaves the canvas and the composer's render targets
    // reallocated and empty until the next animation frame, which is the flash
    // of background you see while dragging the splitter or the window edge —
    // and during a drag the observer fires many times per frame, so the same
    // flash repeats. One resize per frame, immediately followed by the render
    // that fills it.
    const ro = new ResizeObserver(() => {
      this.pendingResize = true;
    });
    ro.observe(container);
    this.resize();

    this.tick();
  }

  private resize() {
    const w = this.container.clientWidth;
    const h = this.container.clientHeight;
    // A pane with no size yet stays pending rather than being marked done.
    if (w === 0 || h === 0) return;
    this.pendingResize = false;
    // Let three set the CSS size as well as the drawing buffer. Passing
    // `false` here sizes the buffer to w * devicePixelRatio but leaves the
    // element's layout size alone, so on a retina display the canvas lays out at
    // twice its pane and spills off the bottom-right corner.
    this.renderer.setSize(w, h);
    this.camera.aspect = w / h;
    this.camera.updateProjectionMatrix();
    this.outline?.setSize(w, h);
  }

  private tick = () => {
    this.frame = requestAnimationFrame(this.tick);
    if (this.pendingResize) this.resize();
    this.controls.update();
    if (this.preview || DEBUG === "noedge" || DEBUG === "normals") {
      // No edge pass in preview mode. Finding creases from neighbouring pixels
      // is guesswork, and on a dual-contoured mesh the guess lands on the
      // zigzag of vertices that stands in for a sharp edge — which is what made
      // this view look like a bad mesh instead of an honest one.
      this.renderer.render(this.scene, this.camera);
    } else {
      // Only the part gets edges; the grid is scenery, not geometry.
      this.outline.render([this.partGroup]);
    }
  };

  dispose() {
    cancelAnimationFrame(this.frame);
    this.renderer.domElement.removeEventListener("pointermove", this.pickEntity);
    this.renderer.domElement.removeEventListener("mousemove", this.pickEntity);
    this.outline.dispose();
    this.renderer.dispose();
  }

  /** Find the visible B-rep entity beneath the pointer. */
  private pickEntity = (event: PointerEvent | MouseEvent) => {
    if (this.preview || this.edgeLines.length === 0) return;

    const rect = this.renderer.domElement.getBoundingClientRect();
    const pointer = new THREE.Vector2(
      ((event.clientX - rect.left) / rect.width) * 2 - 1,
      -((event.clientY - rect.top) / rect.height) * 2 + 1,
    );
    this.edgeRaycaster.setFromCamera(pointer, this.camera);

    // A fixed world-space hit radius feels either tiny on a large part or huge
    // when zoomed in. Twelve screen pixels make a one-pixel CAD edge practical
    // to inspect without turning a nearby face click into a different feature.
    const distance = this.camera.position.distanceTo(this.controls.target);
    const visibleHeight = 2 * Math.tan((this.camera.fov * Math.PI) / 360) * distance;
    this.edgeRaycaster.params.Line!.threshold = (visibleHeight / rect.height) * 12;
    this.vertexRaycaster.params.Points!.threshold = (visibleHeight / rect.height) * 9;

    this.vertexRaycaster.setFromCamera(pointer, this.camera);
    const vertexHit = this.vertexRaycaster.intersectObjects(this.vertexMarkers, false)[0];
    const edgeHit = this.edgeRaycaster.intersectObjects(this.edgeLines, false)[0];
    const vertex = vertexHit?.object as THREE.Points | undefined;
    this.setHoveredVertex(vertex);
    this.setHoveredEdge(vertex ? undefined : edgeHit?.object as THREE.LineSegments | undefined);
  };

  private setHoveredEdge(next?: THREE.LineSegments) {
    if (next === this.hoveredEdge) return;
    const previous = this.hoveredEdge;
    this.hoveredEdge = next;
    this.paintEdge(previous);
    this.paintEdge(next);
    this.edgeCallbacks.onHover?.(next?.userData.edge as EdgeCurve | undefined);
  }

  private setSelectedEdge(next?: THREE.LineSegments) {
    if (next === this.selectedEdge) return;
    const previous = this.selectedEdge;
    this.selectedEdge = next;
    this.paintEdge(previous);
    this.paintEdge(next);
    this.edgeCallbacks.onSelect?.(next?.userData.edge as EdgeCurve | undefined);
  }

  private paintEdge(line?: THREE.LineSegments) {
    if (!line) return;
    const material = line.material as THREE.LineBasicMaterial;
    material.color.setHex(
      line === this.selectedEdge ? 0xf5b942 : line === this.hoveredEdge ? 0x4c91ff : 0x2b3440,
    );
    material.opacity = line === this.hoveredEdge || line === this.selectedEdge ? 1 : 0.85;
  }

  private setHoveredVertex(next?: THREE.Points) {
    if (next === this.hoveredVertex) return;
    const previous = this.hoveredVertex;
    this.hoveredVertex = next;
    this.paintVertex(previous);
    this.paintVertex(next);
    this.edgeCallbacks.onVertexHover?.(next?.userData.vertex as VertexPoint | undefined);
  }

  private setSelectedVertex(next?: THREE.Points) {
    if (next === this.selectedVertex) return;
    const previous = this.selectedVertex;
    this.selectedVertex = next;
    this.paintVertex(previous);
    this.paintVertex(next);
    this.edgeCallbacks.onVertexSelect?.(next?.userData.vertex as VertexPoint | undefined);
  }

  private paintVertex(marker?: THREE.Points) {
    if (!marker) return;
    const material = marker.material as THREE.PointsMaterial;
    material.color.setHex(
      marker === this.selectedVertex ? 0xf5b942 : marker === this.hoveredVertex ? 0x4c91ff : 0x5c6b7c,
    );
    material.size = marker === this.selectedVertex ? 9 : marker === this.hoveredVertex ? 8 : 5;
  }

  /** Replace the displayed part. */
  setGeometry(geo: Geometry, bounds: Bounds) {
    this.clearPart();

    const g = new THREE.BufferGeometry();
    g.setAttribute("position", new THREE.BufferAttribute(geo.positions, 3));
    g.setAttribute("normal", new THREE.BufferAttribute(geo.normals, 3));
    // Expanded triangles carry per-corner normals, so there is nothing to index.
    if (geo.indices.length > 0) {
      g.setIndex(new THREE.BufferAttribute(geo.indices, 1));
    }
    g.computeBoundingSphere();

    const hasRealEdges = !!geo.edges?.length;
    this.preview = !hasRealEdges;
    this.ambient.visible = this.preview;

    // Mesh preview has no logical edge curves, but it does provide
    // surface-aware normals for every triangle corner. Preserve those normals:
    // flat shading turns a smooth cylinder or fillet into visible facets even
    // when the sampled surface is otherwise accurate enough for previewing.
    const mesh = new THREE.Mesh(
      g,
      DEBUG === "normals"
        ? new THREE.MeshNormalMaterial()
        : this.preview
          ? new THREE.MeshLambertMaterial({
              color: 0x9aa6b6,
              emissive: 0x0c1018,
            })
          : new THREE.MeshStandardMaterial({
              color: 0xaeb8c6,
              roughness: 0.46,
              metalness: 0.1,
              envMapIntensity: 1.0,
              flatShading: DEBUG === "flat",
              // Push the shaded surface a hair away from the viewer so the edge
              // lines, which lie exactly on it, win the depth test instead of
              // stitching in and out of it.
              polygonOffset: true,
              polygonOffsetFactor: 1,
              polygonOffsetUnits: 1,
            }),
    );
    mesh.castShadow = true;
    // The part does not receive its own shadow. A hard shadow of the fin thrown
    // across the base plate is physically right and reads as a mark *on* the
    // plate — a discoloured patch, or a step that is not there. Fusion makes
    // the same call: cast onto the ground, never onto yourself. Crevices still
    // darken, but from ambient occlusion, which follows the geometry rather
    // than one arbitrary light direction.
    mesh.receiveShadow = false;
    this.partGroup.add(mesh);

    if (hasRealEdges) {
      // Note what is *not* here: `EdgesGeometry`. That finds an edge wherever
      // two adjacent triangles differ by more than a threshold, which assumes a
      // tidy triangulation. Dual contouring produces nothing of the sort. These
      // lines are not inferred from triangles at all; they are the kernel's own
      // curves, sampled. A straight edge is two points.
      const renderedEdges = edgeLines(geo.edges!);
      this.partGroup.add(renderedEdges.group);
      this.edgeLines.push(...renderedEdges.lines);
      const renderedVertices = vertexMarkers(verticesFromEdges(geo.edges!));
      this.partGroup.add(renderedVertices.group);
      this.vertexMarkers.push(...renderedVertices.markers);
    } else {
      // Show the sampling grid in a restrained weight: it identifies this as a
      // mesh preview while leaving the smoothed surface readable.
      this.partGroup.add(meshWireframe(g));
    }
    // Stop guessing at creases once we are being told where they are. The
    // silhouette half of the pass stays on regardless: the outline of a
    // cylinder is where the surface turns away from the camera, which is a
    // property of the view, not of the solid, so no kernel can supply it.
    this.outline.setCreases(false);

    const size = {
      x: bounds.max.x - bounds.min.x,
      y: bounds.max.y - bounds.min.y,
      z: bounds.max.z - bounds.min.z,
    };
    this.placeGround(bounds, size);
    this.aimSun(bounds, size);
  }

  /** Overlay exact pre-treatment entities selected from the editor source. */
  setTargetPreview(edges: EdgeCurve[], vertices: TargetVertex[] = []) {
    this.clearTargetPreview();
    if (edges.length === 0 && vertices.length === 0) return;

    const group = new THREE.Group();
    if (edges.length > 0) {
      const rendered = edgeLines(edges, 0xf5b942, 1);
      for (const line of rendered.lines) {
        const material = line.material as THREE.LineBasicMaterial;
        // Target curves can have been consumed by a fillet, so draw the exact
        // input over the finished surface instead of letting it disappear behind
        // the replacement faces. They are not added to the raycast set.
        material.depthTest = false;
        line.renderOrder = 2;
      }
      group.add(rendered.group);
    }
    if (vertices.length > 0) group.add(targetVertexMarkers(vertices));
    this.targetPreview = group;
    this.partGroup.add(group);
  }

  private clearTargetPreview() {
    if (!this.targetPreview) return;
    this.partGroup.remove(this.targetPreview);
    this.targetPreview.traverse((object) => {
      const drawable = object as THREE.LineSegments;
      drawable.geometry?.dispose();
      const material = drawable.material;
      if (Array.isArray(material)) material.forEach((entry) => entry.dispose());
      else material?.dispose();
    });
    this.targetPreview = undefined;
  }

  /** Show nothing, without disturbing the camera. */
  clearPart() {
    this.clearTargetPreview();
    this.hoveredEdge = undefined;
    this.selectedEdge = undefined;
    this.hoveredVertex = undefined;
    this.selectedVertex = undefined;
    this.edgeLines.length = 0;
    this.vertexMarkers.length = 0;
    this.edgeCallbacks.onHover?.(undefined);
    this.edgeCallbacks.onSelect?.(undefined);
    this.edgeCallbacks.onVertexHover?.(undefined);
    this.edgeCallbacks.onVertexSelect?.(undefined);
    for (const child of [...this.partGroup.children]) {
      this.partGroup.remove(child);
      child.traverse((o) => {
        const drawable = o as THREE.Mesh | THREE.LineSegments;
        drawable.geometry?.dispose();
        const material = drawable.material;
        if (Array.isArray(material)) material.forEach((m) => m.dispose());
        else material?.dispose();
      });
    }
  }

  /**
   * Grid and shadow-catcher, sitting on the bottom of the part.
   *
   * The shadow is the point. A part floating against a flat background has no
   * cue for where it sits or how far it stands off; a contact shadow supplies
   * both for almost nothing.
   */
  private placeGround(bounds: Bounds, size: { x: number; y: number; z: number }) {
    const extent = Math.max(size.x, size.y, size.z);
    const step = niceStep(extent / 10);
    const span = Math.max(step * 20, extent * 3);
    const z = bounds.min.z;

    if (this.grid) {
      this.scene.remove(this.grid);
      this.grid.dispose();
    }
    this.grid = new THREE.GridHelper(
      span,
      Math.max(2, Math.round(span / step)),
      0x8b96a6,
      0xb4bdc9,
    );
    // GridHelper lies in XZ; stand it up so it is the XY ground plane.
    this.grid.rotateX(Math.PI / 2);
    this.grid.position.z = z;
    this.scene.add(this.grid);

    if (this.ground) {
      this.scene.remove(this.ground);
      this.ground.geometry.dispose();
    }
    this.ground = new THREE.Mesh(
      new THREE.PlaneGeometry(span, span),
      new THREE.ShadowMaterial({ opacity: 0.22 }),
    );
    this.ground.position.z = z - 0.01;
    this.ground.receiveShadow = true;
    this.scene.add(this.ground);
  }

  /** Point the sun at the part and tighten its shadow frustum around it. */
  private aimSun(bounds: Bounds, size: { x: number; y: number; z: number }) {
    const radius = Math.max(1e-3, Math.hypot(size.x, size.y, size.z) / 2);
    const center = new THREE.Vector3(
      (bounds.min.x + bounds.max.x) / 2,
      (bounds.min.y + bounds.max.y) / 2,
      (bounds.min.z + bounds.max.z) / 2,
    );

    const dir = new THREE.Vector3(-0.5, -0.9, 1.4).normalize();
    this.sun.position.copy(center).addScaledVector(dir, radius * 4);
    this.sun.target.position.copy(center);
    this.sun.target.updateMatrixWorld();

    // A shadow camera much larger than the part spends all its resolution on
    // empty space, and the shadow turns to mush.
    const cam = this.sun.shadow.camera;
    cam.left = -radius * 1.6;
    cam.right = radius * 1.6;
    cam.top = radius * 1.6;
    cam.bottom = -radius * 1.6;
    cam.near = radius * 0.5;
    cam.far = radius * 9;
    cam.updateProjectionMatrix();
  }

  /** Frame the part, filling the view. */
  frameAll(bounds: Bounds) {
    const size = {
      x: bounds.max.x - bounds.min.x,
      y: bounds.max.y - bounds.min.y,
      z: bounds.max.z - bounds.min.z,
    };
    const center = new THREE.Vector3(
      (bounds.min.x + bounds.max.x) / 2,
      (bounds.min.y + bounds.max.y) / 2,
      (bounds.min.z + bounds.max.z) / 2,
    );

    const radius = Math.max(1e-3, Math.hypot(size.x, size.y, size.z) / 2);

    // Fit against whichever field of view is *narrower*. `camera.fov` is the
    // vertical one, so on a tall narrow pane — which is exactly what a
    // side-by-side editor leaves — fitting to it alone crops the part off both
    // sides.
    const vFov = (this.camera.fov * Math.PI) / 180;
    const hFov = 2 * Math.atan(Math.tan(vFov / 2) * this.camera.aspect);
    const fov = Math.min(vFov, hFov);
    const distance = (radius / Math.sin(fov / 2)) * 1.06;

    const dir = new THREE.Vector3(0.72, -1, 0.62).normalize();
    this.camera.position.copy(center).addScaledVector(dir, distance);
    // Hug the part. A frustum spanning five orders of magnitude leaves the
    // depth buffer with almost no precision across the part itself, and the
    // outline pass reads that buffer.
    this.camera.near = Math.max(distance - radius * 3, distance * 0.02);
    this.camera.far = distance + radius * 6;
    this.camera.updateProjectionMatrix();

    this.controls.target.copy(center);
    this.controls.update();
  }
}

/**
 * Turn logical edges into independently pickable drawables.
 *
 * Parts currently expose tens or low hundreds of B-rep edges. That keeps a
 * separate line primitive per edge much simpler and more useful than colour-ID
 * GPU picking, while still being negligible beside the shaded part.
 */
function edgeLines(
  edges: EdgeCurve[],
  color = 0x2b3440,
  opacity = 0.85,
): { group: THREE.Group; lines: THREE.LineSegments[] } {
  const group = new THREE.Group();
  const lines: THREE.LineSegments[] = [];
  for (const edge of edges) {
    const pts: number[] = [];
    for (let i = 0; i + 1 < edge.points.length; i++) {
      pts.push(...edge.points[i], ...edge.points[i + 1]);
    }
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(pts, 3));
    const line = new THREE.LineSegments(
      geometry,
      new THREE.LineBasicMaterial({ color, transparent: true, opacity }),
    );
    line.userData.edge = edge;
    // Edges are annotation, not geometry to be lit or to cast shadows.
    line.castShadow = false;
    line.receiveShadow = false;
    // Depth-tested, so far-side edges stay hidden and the model reads solid.
    line.renderOrder = 1;
    group.add(line);
    lines.push(line);
  }
  return { group, lines };
}

/** Turn exact edge endpoints into small pickable corner markers. */
function vertexMarkers(vertices: VertexPoint[]): { group: THREE.Group; markers: THREE.Points[] } {
  const group = new THREE.Group();
  const markers: THREE.Points[] = [];
  for (const vertex of vertices) {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertex.point, 3));
    const marker = new THREE.Points(
      geometry,
      new THREE.PointsMaterial({ color: 0x5c6b7c, size: 5, sizeAttenuation: false, transparent: true, opacity: 0.9 }),
    );
    marker.userData.vertex = vertex;
    marker.castShadow = false;
    marker.receiveShadow = false;
    marker.renderOrder = 2;
    group.add(marker);
    markers.push(marker);
  }
  return { group, markers };
}

/** Gold exact corner targets, intentionally visible through their replacement patch. */
function targetVertexMarkers(vertices: TargetVertex[]): THREE.Group {
  const group = new THREE.Group();
  for (const vertex of vertices) {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertex.point, 3));
    const marker = new THREE.Points(
      geometry,
      new THREE.PointsMaterial({
        color: 0xf5b942,
        size: 12,
        sizeAttenuation: false,
        depthTest: false,
        transparent: true,
        opacity: 1,
      }),
    );
    marker.renderOrder = 3;
    group.add(marker);
  }
  return group;
}

/**
 * The triangle edges of a mesh, drawn faintly over it.
 *
 * Only for the mesh preview. It shows where the mesher sampled densely or
 * sparsely without overpowering the smoothed surface.
 */
function meshWireframe(g: THREE.BufferGeometry): THREE.LineSegments {
  const lines = new THREE.LineSegments(
    new THREE.WireframeGeometry(g),
    // Faint: at fifty thousand triangles a solid wireframe is a grey wall.
    // Low opacity lets density itself carry the information — dense where the
    // mesher subdivided, sparse where it did not.
    new THREE.LineBasicMaterial({ color: 0x2b3440, transparent: true, opacity: 0.45 }),
  );
  lines.castShadow = false;
  lines.receiveShadow = false;
  return lines;
}

/** Round to 1, 2 or 5 times a power of ten. */
function niceStep(v: number): number {
  if (!(v > 0) || !Number.isFinite(v)) return 1;
  const decade = 10 ** Math.floor(Math.log10(v));
  const n = v / decade;
  const snapped = n < 1.5 ? 1 : n < 3.5 ? 2 : n < 7.5 ? 5 : 10;
  return snapped * decade;
}


/** Vertical gradient used as the canvas backdrop. */
function gradientTexture(): THREE.Texture {
  const c = document.createElement("canvas");
  c.width = 2;
  c.height = 256;
  const ctx = c.getContext("2d")!;
  const g = ctx.createLinearGradient(0, 0, 0, 256);
  g.addColorStop(0, BG_TOP);
  g.addColorStop(1, BG_BOTTOM);
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 2, 256);

  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  return tex;
}
