/**
 * The 3D viewport: GPU triangles at display resolution, deliberately a separate
 * renderer from the CPU raymarcher the agent looks through (`render.rs`).
 */

import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { Line2 } from "three/examples/jsm/lines/Line2.js";
import { LineGeometry } from "three/examples/jsm/lines/LineGeometry.js";
import { LineMaterial } from "three/examples/jsm/lines/LineMaterial.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";
import { verticesFromEdges, type VertexPoint } from "./entities";
import { OutlineRenderer } from "./outline";

export interface Geometry {
  positions: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
  /** Logical edges as polylines. Absent for the implicit backend, which can only guess at them. */
  edges?: EdgeCurve[];
  /** Where each face's triangles sit in `indices`. Absent means faces are unpickable, not mispicked. */
  faceRuns?: FaceRun[];
}

/** One face's triangles, as a span of the index buffer. See `state.ts`. */
export interface FaceRun {
  face: number;
  start: number;
  count: number;
}

/** A face of the solid, as the viewport can pick it. */
export interface FacePick {
  /** The kernel's own face number, not this run's position in the list. */
  face: number;
  /** Its triangles, as a span of the index buffer. */
  run: FaceRun;
  triangles: number;
}

/** A logical B-rep edge returned by the exact backend. */
export interface EdgeCurve {
  /** Ephemeral identifier for this evaluated model, for inspection only. */
  id: string;
  points: number[][];
  center: [number, number, number];
  direction: [number, number, number] | null;
  length_mm: number;
  /** Ephemeral source node for a final edge generated by a treatment. */
  treatment_node?: number;
}

/** An exact corner selected by a source-to-viewport target preview. */
export interface TargetVertex {
  /** Ephemeral ID for this preview only; never a modelling-language input. */
  id: string;
  point: [number, number, number];
}

export interface EdgeCallbacks {
  onFaceHover?: (face: FacePick | undefined) => void;
  onHover?: (edge: EdgeCurve | undefined) => void;
  onSelect?: (edge: EdgeCurve | undefined) => void;
  onVertexHover?: (vertex: VertexPoint | undefined) => void;
  onVertexSelect?: (vertex: VertexPoint | undefined) => void;
}

export interface Bounds {
  min: { x: number; y: number; z: number };
  max: { x: number; y: number; z: number };
}

/** A cutting plane, in the same three fields as `parcad_core::view::Section`. */
export interface SectionPlane {
  axis: "x" | "y" | "z";
  atMm: number;
  keep: "below" | "above";
}

/** The cut face, in the raster's own colour. See `CUT_FACE` in render.rs. */
const CUT_FACE = 0xc99454;

/**
 * `--color-gold` from the stylesheet rather than a second copy of it.
 *
 * Gold means the same thing in the scene as it does in the DOM — *this is the
 * one you are pointing at* — and the editor's treatment mark and the target
 * preview already read it from the theme. Every other colour in this file is
 * the scene's own shading palette and is deliberately not a token: nothing in
 * the DOM wears them.
 *
 * Read lazily, because a custom property does not resolve until the CSS is in.
 */
let goldCache: string | undefined;
function gold(): string {
  if (goldCache === undefined) {
    goldCache = getComputedStyle(document.documentElement).getPropertyValue("--color-gold").trim();
    if (!/^#[0-9a-f]{6}$/i.test(goldCache)) {
      throw new Error(
        `--color-gold read as ${goldCache || "nothing"}. The viewport takes it from ` +
          `the @theme block in app/src/style.css; a renamed or removed token lands here.`,
      );
    }
  }
  return goldCache;
}

const goldHex = () => Number.parseInt(gold().slice(1), 16);

/** The highlight's two colours: neither survives alone against both a bright background and dark material. */
const INK = 0x0b0e13;
const HALO = 0xffffff;
/** The highlight's three widths, in CSS pixels. See `resize` for the conversion. */
const GLOW_PX = 4;
const RING_PX = 2.8;
const CORE_PX = 1.4;
/** The source-selected preview. A fat line for the same reason the hover mark
 *  is one: `linewidth` on a plain `THREE.Line` is ignored by every WebGL
 *  driver, so it drew one hairline pixel however wide it asked to be. */
const TARGET_PX = 2.6;

/** Fusion-style light canvas: dark chrome, bright work area. */
const BG_TOP = "#e8ecf1";
const BG_BOTTOM = "#c3ccd8";

/** Diagnostic modes, via `?debug=` in the URL: `normals`, `flat`, `noedge`. */
const DEBUG = new URLSearchParams(location.search).get("debug") ?? "";

/** How far the pointer may travel between down and up and still be a click. */
const DRAG_SLOP_PX = 4;

export class Viewport {
  private readonly renderer: THREE.WebGLRenderer;
  private readonly scene = new THREE.Scene();
  private readonly camera: THREE.PerspectiveCamera;
  private readonly controls: OrbitControls;
  private readonly partGroup = new THREE.Group();
  private readonly sun: THREE.DirectionalLight;
  private ambient!: THREE.HemisphereLight;
  private outline!: OutlineRenderer;
  private grid?: THREE.GridHelper;
  private ground?: THREE.Mesh;
  private frame = 0;
  /** True while showing a mesh preview rather than a solid with real edges. */
  private preview = false;
  private readonly edgeRaycaster = new THREE.Raycaster();
  private readonly edgeLines: THREE.LineSegments[] = [];
  private readonly vertexRaycaster = new THREE.Raycaster();
  private readonly vertexMarkers: THREE.Points[] = [];
  /** Gold source-selected entities, separate from the pickable final topology. */
  private targetPreview?: THREE.Group;
  /** Their fat lines, which carry a screen-space width a resize invalidates. */
  private targetLines: Line2[] = [];
  private hoveredEdge?: THREE.LineSegments;
  private selectedEdge?: THREE.LineSegments;
  /**
   * The hover highlight: white core, ink ring, white glow, as `cornerSprite`
   * draws for corners. `THREE.Line` cannot do it — `linewidth` is ignored by
   * every WebGL driver that matters, so the layers would come out equal width.
   */
  private hoverGlow!: Line2;
  private hoverRing!: Line2;
  private hoverCore!: Line2;
  /** Where each face's triangles sit, when the kernel said. */
  private faceRuns: FaceRun[] = [];
  private hoveredFace?: FacePick;
  /** The lit patch over the hovered face: additive, so shading still reads through it. */
  private faceHighlight?: THREE.Mesh;
  private hoveredVertex?: THREE.Points;
  private selectedVertex?: THREE.Points;
  /** Where the pointer went down, to tell a click apart from an orbit drag. */
  private pointerDownAt?: { x: number; y: number };
  /** The section plane, or none. At most one — see `setSection`. */
  private readonly clipPlanes: THREE.Plane[] = [];
  /** Stencil helpers and the cap quad. Kept out of `partGroup` on purpose. */
  private sectionGroup?: THREE.Group;
  private partMesh?: THREE.Mesh;
  private partBounds?: Bounds;
  /** Set by the ResizeObserver; applied by the frame that then draws. */
  private pendingResize = false;

  constructor(
    private readonly container: HTMLElement,
    private readonly edgeCallbacks: EdgeCallbacks = {},
  ) {
    // `stencil` defaults to false since three r163, and the cap's stencil test
    // does not fail safe without a buffer: it passes over the whole viewport.
    this.renderer = new THREE.WebGLRenderer({ antialias: true, stencil: true });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    this.renderer.shadowMap.enabled = true;
    this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    // Without it, near-white clips flat and the shape reads as a hole.
    this.renderer.toneMapping = THREE.ACESFilmicToneMapping;
    this.renderer.toneMappingExposure = 1.0;
    // Per-material, not renderer-wide: a global plane would clip the cap that
    // lies *on* it.
    this.renderer.localClippingEnabled = true;
    container.appendChild(this.renderer.domElement);

    this.scene.background = gradientTexture();

    this.camera = new THREE.PerspectiveCamera(38, 1, 0.1, 100000);
    // Z is up, as everywhere else in this project.
    this.camera.up.set(0, 0, 1);
    this.camera.position.set(120, -160, 110);

    this.controls = new OrbitControls(this.camera, this.renderer.domElement);
    this.controls.enableDamping = true;
    this.controls.dampingFactor = 0.12;

    this.renderer.domElement.addEventListener("pointermove", this.pickEntity);
    // WKWebView's WebDriver hover emits mouse events, not pointer ones.
    // `setHovered…` is idempotent, so a browser emitting both does no extra work.
    this.renderer.domElement.addEventListener("mousemove", this.pickEntity);
    this.renderer.domElement.addEventListener("pointerleave", () => {
      this.setHoveredEdge();
      this.setHoveredVertex();
    });
    // An orbit drag also ends in a `click`, wherever the pointer stopped, so
    // without the distance test orbiting to see the selection is what clears it.
    this.renderer.domElement.addEventListener("pointerdown", (event) => {
      this.pointerDownAt = { x: event.clientX, y: event.clientY };
    });
    this.renderer.domElement.addEventListener("click", (event) => {
      const down = this.pointerDownAt;
      this.pointerDownAt = undefined;
      if (down && Math.hypot(event.clientX - down.x, event.clientY - down.y) > DRAG_SLOP_PX) return;
      this.setSelectedVertex(this.hoveredVertex);
      this.setSelectedEdge(this.hoveredVertex ? undefined : this.hoveredEdge);
    });

    this.scene.add(this.partGroup);
    this.scene.add(this.camera);

    // Image-based lighting does most of the work: a standard material with no
    // environment to reflect has nothing to shade *with*.
    const pmrem = new THREE.PMREMGenerator(this.renderer);
    pmrem.compileEquirectangularShader();
    this.scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
    this.scene.environmentIntensity = 0.62;

    // Fixed rather than camera-attached: a shadow that swings as you orbit reads
    // as the part moving.
    this.sun = new THREE.DirectionalLight(0xffffff, 1.9);
    this.sun.position.set(-0.5, -0.9, 1.4);
    this.sun.castShadow = true;
    this.sun.shadow.mapSize.set(2048, 2048);
    this.sun.shadow.bias = -0.0012;
    this.scene.add(this.sun);
    this.scene.add(this.sun.target);

    // A weak fill riding with the camera, so faces away from the sun stay readable.
    const fill = new THREE.DirectionalLight(0xc9d6ee, 0.45);
    fill.position.set(0, 0, 1);
    this.camera.add(fill);
    // A DirectionalLight aims at its *target*, which defaults to the world
    // origin — parent only the light and it goes on lighting the scene centre.
    fill.target.position.set(0, 0, -1);
    this.camera.add(fill.target);

    // Preview only: its cheap material cannot see the environment map the
    // finished view takes its ambient from.
    this.ambient = new THREE.HemisphereLight(0xdfe7f2, 0x6c7382, 2.1);
    this.ambient.visible = false;
    this.scene.add(this.ambient);

    this.outline = new OutlineRenderer(this.renderer, this.scene, this.camera);

    const highlight = (color: number, width: number, order: number, opacity = 1) => {
      const line = new Line2(
        new LineGeometry(),
        new LineMaterial({
          color,
          linewidth: width,
          transparent: true,
          opacity,
          depthTest: false,
          depthWrite: false,
        }),
      );
      line.visible = false;
      line.renderOrder = order;
      // Never a pick target: a broad raycast would select the mark, not the edge.
      line.raycast = () => {};
      line.castShadow = false;
      line.receiveShadow = false;
      this.scene.add(line);
      return line;
    };
    this.hoverGlow = highlight(HALO, GLOW_PX, 4, 0.55);
    this.hoverRing = highlight(INK, RING_PX, 5);
    this.hoverCore = highlight(HALO, CORE_PX, 6);

    // Recorded, not applied: resizing inline leaves the render targets empty
    // until the next frame, which is the flash while dragging the splitter.
    const ro = new ResizeObserver(() => {
      this.pendingResize = true;
    });
    ro.observe(container);
    this.resize();

    this.tick();
  }

  private resize() {
    const w = this.container.clientWidth;
    const h = this.container.clientHeight;
    // A pane with no size yet stays pending rather than being marked done.
    if (w === 0 || h === 0) return;
    this.pendingResize = false;
    // Let three set the CSS size too: passing `false` lays the canvas out at
    // twice its pane on a retina display.
    this.renderer.setSize(w, h);
    this.camera.aspect = w / h;
    this.camera.updateProjectionMatrix();
    this.outline?.setSize(w, h);

    // A fat line is a screen-space quad, sized against the *drawing buffer* and
    // not the CSS box — and its width is then in device pixels, hence the ratio.
    const buffer = this.renderer.getDrawingBufferSize(new THREE.Vector2());
    const ratio = this.renderer.getPixelRatio();
    for (const [line, width] of [
      [this.hoverGlow, GLOW_PX],
      [this.hoverRing, RING_PX],
      [this.hoverCore, CORE_PX],
    ] as const) {
      const material = line?.material as LineMaterial | undefined;
      if (!material) continue;
      material.resolution.set(buffer.x, buffer.y);
      material.linewidth = width * ratio;
    }
    for (const line of this.targetLines) this.fitFatLine(line.material, TARGET_PX);
  }

  /**
   * A fat line is a screen-space quad: it needs the drawing buffer's size, and
   * a width in device pixels. Both callers go through here so a preview built
   * between two resizes is not sized by a second, slightly different sum.
   */
  private fitFatLine(material: LineMaterial, widthPx: number) {
    const buffer = this.renderer.getDrawingBufferSize(new THREE.Vector2());
    material.resolution.set(buffer.x, buffer.y);
    material.linewidth = widthPx * this.renderer.getPixelRatio();
  }

  private tick = () => {
    this.frame = requestAnimationFrame(this.tick);
    if (this.pendingResize) this.resize();
    this.controls.update();
    if (this.preview || DEBUG === "noedge" || DEBUG === "normals") {
      // No edge pass in preview: on a dual-contoured mesh the crease guess lands
      // on the zigzag of vertices that stands in for a sharp edge.
      this.renderer.render(this.scene, this.camera);
    } else {
      // Only the part gets edges; the grid is scenery, not geometry.
      this.outline.render([this.partGroup]);
    }
  };

  /**
   * A PNG of what is on screen right now, scaled to fit `size`. Without
   * `preserveDrawingBuffer` the canvas is empty once a frame is presented, so
   * the draw and the copy have to be synchronous and adjacent.
   */
  snapshot(size = 512): string {
    this.tickOnce();
    const canvas = this.renderer.domElement;
    if (!canvas.width || !canvas.height) return "";

    const scale = Math.min(1, size / Math.max(canvas.width, canvas.height));
    const out = document.createElement("canvas");
    out.width = Math.max(1, Math.round(canvas.width * scale));
    out.height = Math.max(1, Math.round(canvas.height * scale));
    const context = out.getContext("2d");
    if (!context) return "";
    context.drawImage(canvas, 0, 0, out.width, out.height);
    return out.toDataURL("image/png");
  }

  /** One frame, outside the animation loop, for `snapshot` to read. */
  private tickOnce() {
    if (this.pendingResize) this.resize();
    if (this.preview || DEBUG === "noedge" || DEBUG === "normals") {
      this.renderer.render(this.scene, this.camera);
    } else {
      this.outline.render([this.partGroup]);
    }
  }

  dispose() {
    cancelAnimationFrame(this.frame);
    this.renderer.domElement.removeEventListener("pointermove", this.pickEntity);
    this.renderer.domElement.removeEventListener("mousemove", this.pickEntity);
    this.outline.dispose();
    this.renderer.dispose();
  }

  /** Find the visible B-rep entity beneath the pointer. */
  private pickEntity = (event: PointerEvent | MouseEvent) => {
    if (this.preview || this.edgeLines.length === 0) return;

    const rect = this.renderer.domElement.getBoundingClientRect();
    const pointer = new THREE.Vector2(
      ((event.clientX - rect.left) / rect.width) * 2 - 1,
      -((event.clientY - rect.top) / rect.height) * 2 + 1,
    );
    this.edgeRaycaster.setFromCamera(pointer, this.camera);

    // The hit radius is in screen pixels, not world units, so it means the same
    // on a large part and a small one.
    const distance = this.camera.position.distanceTo(this.controls.target);
    const visibleHeight = 2 * Math.tan((this.camera.fov * Math.PI) / 360) * distance;
    this.edgeRaycaster.params.Line!.threshold = (visibleHeight / rect.height) * 12;
    this.vertexRaycaster.params.Points!.threshold = (visibleHeight / rect.height) * 9;

    this.vertexRaycaster.setFromCamera(pointer, this.camera);

    // Only what is visible is pickable: the lists cover the far side too, and
    // the marks are drawn without a depth test, so nothing else enforces it.
    const surface = this.visibleSurface(this.edgeRaycaster);
    const near = (surface?.distance ?? Infinity) + (visibleHeight / rect.height) * 12;
    const visible = <T extends THREE.Intersection>(hit?: T) =>
      hit && hit.distance <= near ? hit : undefined;

    const vertexHit = visible(this.vertexRaycaster.intersectObjects(this.vertexMarkers, false)[0]);
    const edgeHit = visible(this.edgeRaycaster.intersectObjects(this.edgeLines, false)[0]);
    const vertex = vertexHit?.object as THREE.Points | undefined;
    this.setHoveredVertex(vertex);
    const edge = vertex ? undefined : (edgeHit?.object as THREE.LineSegments | undefined);
    this.setHoveredEdge(edge);

    // Corners beat edges beat faces: the smaller the entity, the more specific
    // the thing you meant by pointing at it.
    if (vertex || edge || !this.partMesh || this.faceRuns.length === 0) {
      this.setHoveredFace(undefined);
      return;
    }
    const triangle = surface?.faceIndex;
    this.setHoveredFace(
      triangle === undefined || triangle === null ? undefined : this.faceAt(triangle),
    );
  };

  /** A raycaster ignores clipping planes, so skip hits a section has cut away. */
  private visibleSurface(raycaster: THREE.Raycaster): THREE.Intersection | undefined {
    if (!this.partMesh) return undefined;
    for (const hit of raycaster.intersectObject(this.partMesh, false)) {
      if (this.clipPlanes.every((plane) => plane.distanceToPoint(hit.point) >= 0)) return hit;
    }
    return undefined;
  }

  /** Which face a triangle belongs to, by the runs the kernel reported. */
  private faceAt(triangle: number): FacePick | undefined {
    for (const run of this.faceRuns) {
      if (triangle >= run.start && triangle < run.start + run.count) {
        return { face: run.face, run, triangles: run.count };
      }
    }
    return undefined;
  }

  private setHoveredFace(next?: FacePick) {
    if (next?.face === this.hoveredFace?.face) return;
    this.hoveredFace = next;
    this.showFaceHighlight(next);
    this.edgeCallbacks.onFaceHover?.(next);
  }

  /** Lay a lit patch over the hovered face: a copy of its triangles, not a second material on the part. */
  private showFaceHighlight(face?: FacePick) {
    if (this.faceHighlight) {
      this.faceHighlight.parent?.remove(this.faceHighlight);
      this.faceHighlight.geometry.dispose();
      this.faceHighlight = undefined;
    }
    if (!face || !this.partMesh) return;

    const source = this.partMesh.geometry;
    const index = source.getIndex();
    if (!index) return;

    const patch = new THREE.BufferGeometry();
    patch.setAttribute("position", source.getAttribute("position"));
    patch.setIndex(
      new THREE.Uint32BufferAttribute(
        Array.from(index.array).slice(face.run.start * 3, (face.run.start + face.run.count) * 3),
        1,
      ),
    );

    const mesh = new THREE.Mesh(
      patch,
      new THREE.MeshBasicMaterial({
        color: HALO,
        transparent: true,
        opacity: 0.22,
        blending: THREE.AdditiveBlending,
        depthWrite: false,
        // Coplanar with the face it covers, so it z-fights without this.
        polygonOffset: true,
        polygonOffsetFactor: -4,
        polygonOffsetUnits: -4,
        side: THREE.DoubleSide,
        clippingPlanes: this.clipPlanes.length > 0 ? this.clipPlanes : null,
      }),
    );
    mesh.renderOrder = 3;
    mesh.castShadow = false;
    mesh.receiveShadow = false;
    mesh.raycast = () => {};

    // `EdgesGeometry` drops near-coplanar edges, which is what leaves the
    // patch boundary — except onto a *tangent* neighbour, where there is no
    // angle to find and the tint alone has to carry the highlight.
    const outline = new THREE.LineSegments(
      new THREE.EdgesGeometry(patch, 25),
      new THREE.LineBasicMaterial({
        color: HALO,
        transparent: true,
        opacity: 0.85,
        depthWrite: false,
        clippingPlanes: this.clipPlanes.length > 0 ? this.clipPlanes : null,
      }),
    );
    outline.renderOrder = 4;
    outline.raycast = () => {};
    mesh.add(outline);

    this.faceHighlight = mesh;
    this.partMesh.add(mesh);
  }

  private setHoveredEdge(next?: THREE.LineSegments) {
    if (next === this.hoveredEdge) return;
    const previous = this.hoveredEdge;
    this.hoveredEdge = next;
    this.paintEdge(previous);
    this.paintEdge(next);
    this.showEdgeHighlight(next);
    this.edgeCallbacks.onHover?.(next?.userData.edge as EdgeCurve | undefined);
  }

  private setSelectedEdge(next?: THREE.LineSegments) {
    if (next === this.selectedEdge) return;
    const previous = this.selectedEdge;
    this.selectedEdge = next;
    this.paintEdge(previous);
    this.paintEdge(next);
    this.edgeCallbacks.onSelect?.(next?.userData.edge as EdgeCurve | undefined);
  }

  /** Gold when pinned. Hover is drawn by the highlight instead, so the edge keeps looking like an edge. */
  private paintEdge(line?: THREE.LineSegments) {
    if (!line) return;
    const material = line.material as THREE.LineBasicMaterial;
    material.color.setHex(line === this.selectedEdge ? goldHex() : 0x2b3440);
    material.opacity = line === this.selectedEdge ? 1 : 0.85;
  }

  /** Lay the three layers over the hovered edge. Rebuilt per hover, not kept per edge. */
  private showEdgeHighlight(line?: THREE.LineSegments) {
    const edge = line?.userData.edge as EdgeCurve | undefined;
    if (!edge || edge.points.length < 2) {
      for (const target of [this.hoverGlow, this.hoverRing, this.hoverCore]) {
        target.visible = false;
      }
      return;
    }
    const flat = edge.points.flat();
    for (const target of [this.hoverGlow, this.hoverRing, this.hoverCore]) {
      const geometry = new LineGeometry();
      geometry.setPositions(flat);
      target.geometry.dispose();
      target.geometry = geometry;
      target.computeLineDistances();
      target.visible = true;
    }
  }

  private setHoveredVertex(next?: THREE.Points) {
    if (next === this.hoveredVertex) return;
    const previous = this.hoveredVertex;
    this.hoveredVertex = next;
    this.paintVertex(previous);
    this.paintVertex(next);
    this.edgeCallbacks.onVertexHover?.(next?.userData.vertex as VertexPoint | undefined);
  }

  private setSelectedVertex(next?: THREE.Points) {
    if (next === this.selectedVertex) return;
    const previous = this.selectedVertex;
    this.selectedVertex = next;
    this.paintVertex(previous);
    this.paintVertex(next);
    this.edgeCallbacks.onVertexSelect?.(next?.userData.vertex as VertexPoint | undefined);
  }

  /**
   * A corner is drawn only while it is pointed at. `material.visible` rather
   * than `object.visible`: the raycaster still sees the object, so a corner you
   * cannot see is still a corner you can hover.
   */
  private paintVertex(marker?: THREE.Points) {
    if (!marker) return;
    const shown = marker === this.hoveredVertex || marker === this.selectedVertex;
    marker.material =
      marker === this.selectedVertex
        ? vertexMaterial("selected")
        : shown
          ? vertexMaterial("hover")
          : vertexMaterial("hidden");
  }

  /** Replace the displayed part. */
  setGeometry(geo: Geometry, bounds: Bounds) {
    this.clearPart();

    const g = new THREE.BufferGeometry();
    g.setAttribute("position", new THREE.BufferAttribute(geo.positions, 3));
    g.setAttribute("normal", new THREE.BufferAttribute(geo.normals, 3));
    // Expanded triangles carry per-corner normals, so there is nothing to index.
    if (geo.indices.length > 0) {
      g.setIndex(new THREE.BufferAttribute(geo.indices, 1));
    }
    g.computeBoundingSphere();

    const hasRealEdges = !!geo.edges?.length;
    this.preview = !hasRealEdges;
    this.ambient.visible = this.preview;

    // Smooth shading even in preview: the mesher's normals are surface-aware,
    // and flat shading would facet a cylinder the sampling got right.
    const mesh = new THREE.Mesh(
      g,
      DEBUG === "normals"
        ? new THREE.MeshNormalMaterial()
        : this.preview
          ? new THREE.MeshLambertMaterial({
              color: 0x9aa6b6,
              emissive: 0x0c1018,
            })
          : new THREE.MeshStandardMaterial({
              color: 0xaeb8c6,
              roughness: 0.46,
              metalness: 0.1,
              envMapIntensity: 1.0,
              flatShading: DEBUG === "flat",
              // Pushed back a hair so the edge lines lying on it win the depth test.
              polygonOffset: true,
              polygonOffsetFactor: 1,
              polygonOffsetUnits: 1,
            }),
    );
    mesh.castShadow = true;
    // Cast onto the ground, never onto itself: a hard shadow of a fin across
    // its own base plate reads as a step that is not there. Fusion does likewise.
    mesh.receiveShadow = false;
    this.partGroup.add(mesh);
    this.partMesh = mesh;
    this.partBounds = bounds;

    if (hasRealEdges) {
      // Not `EdgesGeometry`: these are the kernel's own curves, sampled, and
      // inferring them from triangles assumes a tidy triangulation that dual
      // contouring never produces.
      const renderedEdges = edgeLines(geo.edges!);
      this.partGroup.add(renderedEdges.group);
      this.edgeLines.push(...renderedEdges.lines);
      const renderedVertices = vertexMarkers(verticesFromEdges(geo.edges!));
      this.partGroup.add(renderedVertices.group);
      this.vertexMarkers.push(...renderedVertices.markers);
      // Only the exact kernel attributes a triangle to a face; empty otherwise.
      this.faceRuns = geo.faceRuns ?? [];
    } else {
      this.partGroup.add(meshWireframe(g));
    }
    // Stop guessing at creases once told where they are. The silhouette half of
    // the pass stays on: it is a property of the view, so no kernel supplies it.
    this.outline.setCreases(false);

    const size = {
      x: bounds.max.x - bounds.min.x,
      y: bounds.max.y - bounds.min.y,
      z: bounds.max.z - bounds.min.z,
    };
    this.placeGround(bounds, size);
    this.aimSun(bounds, size);

    // A new part keeps the plane the last one was cut on: the reason the
    // section is open is to watch one internal feature change.
    this.applyClipping();
    this.buildCap(this.section);
  }

  /** The plane currently cut, if any — `setSection`'s argument, remembered. */
  private section?: SectionPlane;

  /** Cut the part open on a plane, or stop. The window's half of `evaluate_part`'s `section`. */
  setSection(section?: SectionPlane) {
    this.section = section;
    this.clipPlanes.length = 0;
    if (section) {
      // three keeps dot(normal, p) + constant > 0, so the normal points *into*
      // the material that survives.
      const sign = section.keep === "below" ? -1 : 1;
      const normal = new THREE.Vector3(
        section.axis === "x" ? sign : 0,
        section.axis === "y" ? sign : 0,
        section.axis === "z" ? sign : 0,
      );
      this.clipPlanes.push(new THREE.Plane(normal, -sign * section.atMm));
    }

    this.applyClipping();
    this.buildCap(section);
    this.outline.setClippingPlanes(this.clipPlanes);
  }

  /** Which half to keep so the cut faces the camera. `Section::resolve`, with an orbiting camera. */
  keepFacingCamera(axis: "x" | "y" | "z"): "below" | "above" {
    const toward = this.camera.position.clone().sub(this.controls.target);
    return toward[axis] > 0 ? "below" : "above";
  }

  /** Hand the current plane to everything the part is drawn with. */
  private applyClipping() {
    const planes = this.clipPlanes.length > 0 ? this.clipPlanes : null;
    this.partGroup.traverse((object) => {
      const drawable = object as THREE.Mesh | THREE.LineSegments;
      const material = drawable.material;
      if (!material) return;
      for (const m of Array.isArray(material) ? material : [material]) {
        const before = m.clippingPlanes?.length ?? 0;
        m.clippingPlanes = planes;
        // Shadow the half that is left, not the half that went.
        m.clipShadows = true;
        // The plane count is compiled *into* the shader, so without this an
        // existing program keeps its clip-free version and the section quietly
        // does not cut.
        if (before !== (planes?.length ?? 0)) m.needsUpdate = true;
      }
    });
  }

  /**
   * Fill the cut with a flat face, or clipping leaves a hollow shell that reads
   * as a thin cup. Back faces increment the stencil and front faces decrement
   * it, both invisible and both clipped, so a count that does not cancel means
   * the ray crossed the plane inside material — and the quad paints there.
   */
  private buildCap(section?: SectionPlane) {
    if (this.sectionGroup) {
      this.scene.remove(this.sectionGroup);
      disposeTree(this.sectionGroup);
      this.sectionGroup = undefined;
    }
    if (!section || !this.partMesh || !this.partBounds) return;

    const group = new THREE.Group();
    const geometry = this.partMesh.geometry;

    for (const [side, op] of [
      [THREE.BackSide, THREE.IncrementWrapStencilOp],
      [THREE.FrontSide, THREE.DecrementWrapStencilOp],
    ] as const) {
      const material = new THREE.MeshBasicMaterial({
        side,
        clippingPlanes: this.clipPlanes,
        // Counting, not drawing: a crossing counts wherever it is, not only
        // where it is nearest.
        colorWrite: false,
        depthWrite: false,
        depthTest: false,
        stencilWrite: true,
        stencilFunc: THREE.AlwaysStencilFunc,
        stencilFail: op,
        stencilZFail: op,
        stencilZPass: op,
      });
      const counter = new THREE.Mesh(geometry, material);
      counter.renderOrder = -2;
      group.add(counter);
    }

    const size = Math.max(
      this.partBounds.max.x - this.partBounds.min.x,
      this.partBounds.max.y - this.partBounds.min.y,
      this.partBounds.max.z - this.partBounds.min.z,
    );
    const cap = new THREE.Mesh(
      new THREE.PlaneGeometry(size * 3, size * 3),
      new THREE.MeshBasicMaterial({
        color: CUT_FACE,
        side: THREE.DoubleSide,
        stencilWrite: true,
        stencilRef: 0,
        stencilFunc: THREE.NotEqualStencilFunc,
        // Reset as it draws, so the next frame starts from a clean buffer.
        stencilFail: THREE.ReplaceStencilOp,
        stencilZFail: THREE.ReplaceStencilOp,
        stencilZPass: THREE.ReplaceStencilOp,
      }),
    );
    // A quad in XY facing +Z, turned to face along the section axis.
    if (section.axis === "x") cap.rotateY(Math.PI / 2);
    if (section.axis === "y") cap.rotateX(Math.PI / 2);
    const centre = {
      x: (this.partBounds.min.x + this.partBounds.max.x) / 2,
      y: (this.partBounds.min.y + this.partBounds.max.y) / 2,
      z: (this.partBounds.min.z + this.partBounds.max.z) / 2,
    };
    cap.position.set(centre.x, centre.y, centre.z);
    cap.position[section.axis] = section.atMm;
    cap.renderOrder = -1;
    cap.castShadow = false;
    cap.receiveShadow = false;
    group.add(cap);

    // In the scene, not `partGroup`: the outline pass hides meshes it was not
    // asked to outline, and these are the *unclipped* part.
    this.sectionGroup = group;
    this.scene.add(group);
  }

  /** Overlay exact pre-treatment entities selected from the editor source. */
  setTargetPreview(edges: EdgeCurve[], vertices: TargetVertex[] = []) {
    this.clearTargetPreview();
    if (edges.length === 0 && vertices.length === 0) return;

    const group = new THREE.Group();
    for (const edge of edges) {
      const geometry = new LineGeometry();
      geometry.setPositions(edge.points.flat());
      const line = new Line2(
        geometry,
        new LineMaterial({
          color: goldHex(),
          depthTest: false,
          depthWrite: false,
        }),
      );
      this.fitFatLine(line.material, TARGET_PX);
      // Never a pick target: this is the source's selection, not the topology.
      line.raycast = () => {};
      line.renderOrder = 2;
      this.targetLines.push(line);
      group.add(line);
    }

    if (vertices.length > 0) group.add(targetVertexMarkers(vertices));
    this.targetPreview = group;
    this.partGroup.add(group);
  }

  private clearTargetPreview() {
    // Emptied first: `resize` walks this list, and a disposed material is not
    // one to be setting a resolution on.
    this.targetLines.length = 0;
    if (!this.targetPreview) return;
    this.partGroup.remove(this.targetPreview);
    disposeTree(this.targetPreview);
    this.targetPreview = undefined;
  }

  /** Show nothing, without disturbing the camera. */
  clearPart() {
    this.clearTargetPreview();
    if (this.sectionGroup) {
      this.scene.remove(this.sectionGroup);
      disposeTree(this.sectionGroup);
      this.sectionGroup = undefined;
    }
    this.partMesh = undefined;
    this.hoveredEdge = undefined;
    this.selectedEdge = undefined;
    this.hoveredVertex = undefined;
    this.selectedVertex = undefined;
    this.edgeLines.length = 0;
    this.vertexMarkers.length = 0;
    this.faceRuns = [];
    this.hoveredFace = undefined;
    this.faceHighlight = undefined;
    // The highlight lives on the scene, not in the part group, so it survives
    // the sweep below and has to be put away by hand.
    this.showEdgeHighlight(undefined);
    this.edgeCallbacks.onHover?.(undefined);
    this.edgeCallbacks.onSelect?.(undefined);
    this.edgeCallbacks.onVertexHover?.(undefined);
    this.edgeCallbacks.onVertexSelect?.(undefined);
    for (const child of [...this.partGroup.children]) {
      this.partGroup.remove(child);
      child.traverse((o) => {
        const drawable = o as THREE.Mesh | THREE.LineSegments;
        drawable.geometry?.dispose();
        releaseMaterial(drawable.material);
      });
    }
  }

  /** Grid and shadow-catcher at the bottom of the part: the contact shadow is what says where it sits. */
  private placeGround(bounds: Bounds, size: { x: number; y: number; z: number }) {
    const extent = Math.max(size.x, size.y, size.z);
    const step = niceStep(extent / 10);
    const span = Math.max(step * 20, extent * 3);
    const z = bounds.min.z;

    if (this.grid) {
      this.scene.remove(this.grid);
      this.grid.dispose();
    }
    this.grid = new THREE.GridHelper(
      span,
      Math.max(2, Math.round(span / step)),
      0x8b96a6,
      0xb4bdc9,
    );
    // GridHelper lies in XZ; stand it up so it is the XY ground plane.
    this.grid.rotateX(Math.PI / 2);
    this.grid.position.z = z;
    this.scene.add(this.grid);

    if (this.ground) {
      this.scene.remove(this.ground);
      this.ground.geometry.dispose();
    }
    this.ground = new THREE.Mesh(
      new THREE.PlaneGeometry(span, span),
      new THREE.ShadowMaterial({ opacity: 0.22 }),
    );
    this.ground.position.z = z - 0.01;
    this.ground.receiveShadow = true;
    this.scene.add(this.ground);
  }

  /** Point the sun at the part and tighten its shadow frustum around it. */
  private aimSun(bounds: Bounds, size: { x: number; y: number; z: number }) {
    const radius = Math.max(1e-3, Math.hypot(size.x, size.y, size.z) / 2);
    const center = new THREE.Vector3(
      (bounds.min.x + bounds.max.x) / 2,
      (bounds.min.y + bounds.max.y) / 2,
      (bounds.min.z + bounds.max.z) / 2,
    );

    const dir = new THREE.Vector3(-0.5, -0.9, 1.4).normalize();
    this.sun.position.copy(center).addScaledVector(dir, radius * 4);
    this.sun.target.position.copy(center);
    this.sun.target.updateMatrixWorld();

    // A shadow camera much larger than the part spends its resolution on empty space.
    const cam = this.sun.shadow.camera;
    cam.left = -radius * 1.6;
    cam.right = radius * 1.6;
    cam.top = radius * 1.6;
    cam.bottom = -radius * 1.6;
    cam.near = radius * 0.5;
    cam.far = radius * 9;
    cam.updateProjectionMatrix();
  }

  /** Frame the part, filling the view. */
  frameAll(bounds: Bounds) {
    const size = {
      x: bounds.max.x - bounds.min.x,
      y: bounds.max.y - bounds.min.y,
      z: bounds.max.z - bounds.min.z,
    };
    const center = new THREE.Vector3(
      (bounds.min.x + bounds.max.x) / 2,
      (bounds.min.y + bounds.max.y) / 2,
      (bounds.min.z + bounds.max.z) / 2,
    );

    const radius = Math.max(1e-3, Math.hypot(size.x, size.y, size.z) / 2);

    // Fit the *narrower* field of view: `camera.fov` is the vertical one, and
    // fitting to it alone crops the sides off in the pane an editor leaves.
    const vFov = (this.camera.fov * Math.PI) / 180;
    const hFov = 2 * Math.atan(Math.tan(vFov / 2) * this.camera.aspect);
    const fov = Math.min(vFov, hFov);
    const distance = (radius / Math.sin(fov / 2)) * 1.06;

    const dir = new THREE.Vector3(0.72, -1, 0.62).normalize();
    this.camera.position.copy(center).addScaledVector(dir, distance);
    // Hug the part: a frustum spanning five orders of magnitude leaves the
    // depth buffer, which the outline pass reads, no precision across it.
    this.camera.near = Math.max(distance - radius * 3, distance * 0.02);
    this.camera.far = distance + radius * 6;
    this.camera.updateProjectionMatrix();

    this.controls.target.copy(center);
    this.controls.update();
  }
}

/** Turn logical edges into independently pickable drawables — one primitive each, at these counts. */
function edgeLines(edges: EdgeCurve[]): { group: THREE.Group; lines: THREE.LineSegments[] } {
  const color = 0x2b3440;
  const opacity = 0.85;
  const group = new THREE.Group();
  const lines: THREE.LineSegments[] = [];
  for (const edge of edges) {
    const pts: number[] = [];
    for (let i = 0; i + 1 < edge.points.length; i++) {
      pts.push(...edge.points[i], ...edge.points[i + 1]);
    }
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(pts, 3));
    const line = new THREE.LineSegments(
      geometry,
      new THREE.LineBasicMaterial({ color, transparent: true, opacity }),
    );
    line.userData.edge = edge;
    line.castShadow = false;
    line.receiveShadow = false;
    line.renderOrder = 1;
    group.add(line);
    lines.push(line);
  }
  return { group, lines };
}

/** The corner sprite: white disc, ink ring, white glow — a shape a plain `PointsMaterial` cannot be. */
function cornerSprite(fill: string, ring: string): THREE.Texture {
  const size = 64;
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext("2d")!;
  const centre = size / 2;

  // The glow first, and wider than the ring, or it is a smudge under the mark.
  ctx.shadowColor = "rgba(255,255,255,0.95)";
  ctx.shadowBlur = 9;
  ctx.fillStyle = "rgba(255,255,255,0.9)";
  ctx.beginPath();
  ctx.arc(centre, centre, 19, 0, Math.PI * 2);
  ctx.fill();
  ctx.shadowBlur = 0;

  ctx.beginPath();
  ctx.arc(centre, centre, 14, 0, Math.PI * 2);
  ctx.fillStyle = fill;
  ctx.fill();
  ctx.lineWidth = 5;
  ctx.strokeStyle = ring;
  ctx.stroke();

  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
}

/** One material per state, shared by every corner. Lazy, so importing needs no DOM. */
const VERTEX_MATERIALS: Partial<Record<"hidden" | "hover" | "selected", THREE.PointsMaterial>> = {};

function vertexMaterial(state: "hidden" | "hover" | "selected"): THREE.PointsMaterial {
  const existing = VERTEX_MATERIALS[state];
  if (existing) return existing;

  const made =
    state === "hidden"
      ? // Not drawn, but still raycast — see `paintVertex`.
        new THREE.PointsMaterial({ visible: false })
      : new THREE.PointsMaterial({
          map: cornerSprite(state === "selected" ? gold() : "#ffffff", "#0b0e13"),
          size: state === "selected" ? 15 : 13,
          sizeAttenuation: false,
          transparent: true,
          depthWrite: false,
          depthTest: false,
        });
  made.userData.shared = true;
  VERTEX_MATERIALS[state] = made;
  return made;
}

/** Turn exact edge endpoints into pickable corners, drawn only when pointed at. */
function vertexMarkers(vertices: VertexPoint[]): { group: THREE.Group; markers: THREE.Points[] } {
  const group = new THREE.Group();
  const markers: THREE.Points[] = [];
  for (const vertex of vertices) {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertex.point, 3));
    const marker = new THREE.Points(geometry, vertexMaterial("hidden"));
    marker.userData.vertex = vertex;
    marker.castShadow = false;
    marker.receiveShadow = false;
    marker.renderOrder = 7;
    group.add(marker);
    markers.push(marker);
  }
  return { group, markers };
}

/** Gold exact corner targets, intentionally visible through their replacement patch. */
function targetVertexMarkers(vertices: TargetVertex[]): THREE.Group {
  const group = new THREE.Group();
  for (const vertex of vertices) {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertex.point, 3));
    const marker = new THREE.Points(
      geometry,
      new THREE.PointsMaterial({
        color: goldHex(),
        size: 12,
        sizeAttenuation: false,
        depthTest: false,
        transparent: true,
        opacity: 1,
      }),
    );
    marker.renderOrder = 3;
    group.add(marker);
  }
  return group;
}

/** Where the mesher sampled densely or sparsely. Preview only. */
function meshWireframe(g: THREE.BufferGeometry): THREE.LineSegments {
  const lines = new THREE.LineSegments(
    new THREE.WireframeGeometry(g),
    // Faint: at fifty thousand triangles a solid wireframe is a grey wall.
    new THREE.LineBasicMaterial({ color: 0x2b3440, transparent: true, opacity: 0.45 }),
  );
  lines.castShadow = false;
  lines.receiveShadow = false;
  return lines;
}

/** Free a material unless it is shared — the corner materials outlive any one part. */
function releaseMaterial(material: THREE.Material | THREE.Material[] | undefined) {
  if (!material) return;
  if (Array.isArray(material)) {
    material.forEach(releaseMaterial);
    return;
  }
  if (material.userData.shared) return;
  material.dispose();
}

/** Drop everything under an object. Not geometry: the stencil helpers share the part's buffers. */
function disposeTree(root: THREE.Object3D) {
  root.traverse((object) => {
    const drawable = object as THREE.Mesh | THREE.LineSegments;
    releaseMaterial(drawable.material);
  });
}

/** Round to 1, 2 or 5 times a power of ten. */
function niceStep(v: number): number {
  if (!(v > 0) || !Number.isFinite(v)) return 1;
  const decade = 10 ** Math.floor(Math.log10(v));
  const n = v / decade;
  const snapped = n < 1.5 ? 1 : n < 3.5 ? 2 : n < 7.5 ? 5 : 10;
  return snapped * decade;
}


/** Vertical gradient used as the canvas backdrop. */
function gradientTexture(): THREE.Texture {
  const c = document.createElement("canvas");
  c.width = 2;
  c.height = 256;
  const ctx = c.getContext("2d")!;
  const g = ctx.createLinearGradient(0, 0, 0, 256);
  g.addColorStop(0, BG_TOP);
  g.addColorStop(1, BG_BOTTOM);
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 2, 256);

  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  return tex;
}
