/**
 * The 3D viewport.
 *
 * This is a different renderer from the one the agent looks through, on purpose.
 * The agent's renders are CPU raymarched at a fixed small size for a vision
 * model; this one is GPU triangles at native display resolution, and its job is
 * to be smooth under the mouse. Sharing one renderer between the two would make
 * both worse.
 */

import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { Line2 } from "three/examples/jsm/lines/Line2.js";
import { LineGeometry } from "three/examples/jsm/lines/LineGeometry.js";
import { LineMaterial } from "three/examples/jsm/lines/LineMaterial.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";
import { verticesFromEdges, type VertexPoint } from "./entities";
import { OutlineRenderer } from "./outline";

export interface Geometry {
  positions: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
  /**
   * Logical edges as polylines, when the backend knows what they are.
   *
   * The implicit backend cannot supply these, and the difference is visible: a
   * screen-space pass can only ever *guess* where an edge is from the pixels
   * around it, while these are the curve itself.
   */
  edges?: EdgeCurve[];
  /**
   * Where each face's triangles sit in `indices`, and which face each run is.
   *
   * Absent for the implicit backend and for a mesh preview. Without it a
   * triangle under the pointer belongs to the solid and to nothing smaller, so
   * faces simply are not pickable — which is the honest behaviour, rather than
   * highlighting a patch of triangles and calling it a face.
   */
  faceRuns?: FaceRun[];
}

/** One face's triangles, as a span of the index buffer. See `state.ts`. */
export interface FaceRun {
  face: number;
  start: number;
  count: number;
}

/** A face of the solid, as the viewport can pick it. */
export interface FacePick {
  /** The kernel's own face number, not this run's position in the list. */
  face: number;
  /** Its triangles, as a span of the index buffer. */
  run: FaceRun;
  triangles: number;
}

/** A logical B-rep edge returned by the exact backend. */
export interface EdgeCurve {
  /** Ephemeral identifier for this evaluated model, for inspection only. */
  id: string;
  points: number[][];
  center: [number, number, number];
  direction: [number, number, number] | null;
  length_mm: number;
  /** Ephemeral source node for a final edge generated by a treatment. */
  treatment_node?: number;
}

/** An exact corner selected by a source-to-viewport target preview. */
export interface TargetVertex {
  /** Ephemeral ID for this preview only; never a modelling-language input. */
  id: string;
  point: [number, number, number];
}

export interface EdgeCallbacks {
  onFaceHover?: (face: FacePick | undefined) => void;
  onHover?: (edge: EdgeCurve | undefined) => void;
  onSelect?: (edge: EdgeCurve | undefined) => void;
  onVertexHover?: (vertex: VertexPoint | undefined) => void;
  onVertexSelect?: (vertex: VertexPoint | undefined) => void;
}

export interface Bounds {
  min: { x: number; y: number; z: number };
  max: { x: number; y: number; z: number };
}

/**
 * A cutting plane, in the same terms the kernel and MCP use.
 *
 * Deliberately the same three fields as `parcad_core::view::Section`, so "cut it
 * on Y at 5, keep above" means one thing whether it is typed here or asked for
 * over MCP. The window resolves nothing — an axis with no position is not a
 * section yet — because here there is a slider to say it with.
 */
export interface SectionPlane {
  axis: "x" | "y" | "z";
  atMm: number;
  keep: "below" | "above";
}

/** The cut face, in the raster's own colour. See `CUT_FACE` in render.rs. */
const CUT_FACE = 0xc99454;

/**
 * The hover highlight, in the two colours it needs to be legible anywhere.
 *
 * The work area is deliberately bright and the part is a mid grey that goes
 * dark where it turns away from the light, so neither a black mark nor a white
 * one survives on its own. A near-black core inside a white halo does: the halo
 * separates it from dark material, the core from the pale background. Vertices
 * invert it — a white disc with a near-black ring — for the same reason, since
 * a filled dot needs its contrast the other way round.
 */
const INK = 0x0b0e13;
const HALO = 0xffffff;
/** The highlight's two widths, in CSS pixels. See `resize` for the conversion. */
const HALO_PX = 5.5;
const CORE_PX = 2.2;

/** Fusion-style light canvas: dark chrome, bright work area. */
const BG_TOP = "#e8ecf1";
const BG_BOTTOM = "#c3ccd8";

/**
 * Diagnostic modes, via `?debug=` in the URL.
 *
 * `normals` paints the raw normal field, which separates "the normals are noisy"
 * from "the surface is bumpy" — the two look alike once shaded.
 */
const DEBUG = new URLSearchParams(location.search).get("debug") ?? "";

/** How far the pointer may travel between down and up and still be a click. */
const DRAG_SLOP_PX = 4;

export class Viewport {
  private readonly renderer: THREE.WebGLRenderer;
  private readonly scene = new THREE.Scene();
  private readonly camera: THREE.PerspectiveCamera;
  private readonly controls: OrbitControls;
  private readonly partGroup = new THREE.Group();
  private readonly sun: THREE.DirectionalLight;
  private ambient!: THREE.HemisphereLight;
  private outline!: OutlineRenderer;
  /** @internal exposed for debugging */
  readonly debugScene = () => this.scene;
  private grid?: THREE.GridHelper;
  private ground?: THREE.Mesh;
  private frame = 0;
  /** True while showing a mesh preview rather than a solid with real edges. */
  private preview = false;
  private readonly edgeRaycaster = new THREE.Raycaster();
  private readonly edgeLines: THREE.LineSegments[] = [];
  private readonly vertexRaycaster = new THREE.Raycaster();
  private readonly vertexMarkers: THREE.Points[] = [];
  /** Gold source-selected entities, separate from the pickable final topology. */
  private targetPreview?: THREE.Group;
  private hoveredEdge?: THREE.LineSegments;
  private selectedEdge?: THREE.LineSegments;
  /**
   * The hover highlight, built once and re-pointed at whatever is under the
   * cursor.
   *
   * Two fat lines rather than one: a white halo under a near-black core. A
   * plain black line is invisible against the part's own dark edges and a
   * plain white one is invisible against the light background, so a highlight
   * that has to read on both needs both. This is the shape every mechanical
   * CAD package draws for the same reason.
   *
   * `THREE.Line` cannot do it — `linewidth` is ignored by every WebGL driver
   * that matters, so a halo drawn with it would be exactly as wide as the line
   * it is meant to surround.
   */
  private hoverHalo!: Line2;
  private hoverCore!: Line2;
  /** Where each face's triangles sit, when the kernel said. */
  private faceRuns: FaceRun[] = [];
  private hoveredFace?: FacePick;
  /**
   * The lit patch over the hovered face.
   *
   * Its geometry is the face's own triangles copied out of the part, so it is
   * the face exactly rather than a box around it. Additive, so it *lightens*
   * whatever it lies on instead of painting a flat colour over shading the eye
   * uses to read the shape.
   */
  private faceHighlight?: THREE.Mesh;
  private hoveredVertex?: THREE.Points;
  private selectedVertex?: THREE.Points;
  /** Where the pointer went down, to tell a click apart from an orbit drag. */
  private pointerDownAt?: { x: number; y: number };
  /** The section plane, or none. At most one — see `setSection`. */
  private readonly clipPlanes: THREE.Plane[] = [];
  /** Stencil helpers and the cap quad. Kept out of `partGroup` on purpose. */
  private sectionGroup?: THREE.Group;
  private partMesh?: THREE.Mesh;
  private partBounds?: Bounds;
  /** Set by the ResizeObserver; applied by the frame that then draws. */
  private pendingResize = false;

  constructor(
    private readonly container: HTMLElement,
    private readonly edgeCallbacks: EdgeCallbacks = {},
  ) {
    // `stencil` has defaulted to false since three r163, and the section cap is
    // drawn with a stencil test. Without a stencil buffer that test does not
    // fail safe — it passes everywhere, and the cap covers the entire viewport.
    // The composed path renders into its own target and would not have noticed;
    // the mesh preview draws straight to this canvas and does.
    this.renderer = new THREE.WebGLRenderer({ antialias: true, stencil: true });
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    this.renderer.shadowMap.enabled = true;
    this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    // Without tone mapping, anything approaching full brightness clips to a flat
    // white patch and the shape reads as a silhouette with a hole in it.
    this.renderer.toneMapping = THREE.ACESFilmicToneMapping;
    this.renderer.toneMappingExposure = 1.0;
    // Per-material clipping rather than the renderer-wide kind: the cap that
    // fills the cut is a quad lying *on* the section plane, and a global plane
    // would clip the cap along with everything else — coplanar, so it would
    // flicker in and out as the camera moved.
    this.renderer.localClippingEnabled = true;
    container.appendChild(this.renderer.domElement);

    this.scene.background = gradientTexture();

    this.camera = new THREE.PerspectiveCamera(38, 1, 0.1, 100000);
    // Z is up, as everywhere else in this project.
    this.camera.up.set(0, 0, 1);
    this.camera.position.set(120, -160, 110);

    this.controls = new OrbitControls(this.camera, this.renderer.domElement);
    this.controls.enableDamping = true;
    this.controls.dampingFactor = 0.12;

    this.renderer.domElement.addEventListener("pointermove", this.pickEntity);
    // WKWebView's WebDriver endpoint currently emits mouse events for an
    // automated hover. Handling both keeps the real pointer interaction intact
    // while making that native desktop path inspectable in regression tests.
    // `setHovered…` is idempotent, so browsers that emit both do no extra work.
    this.renderer.domElement.addEventListener("mousemove", this.pickEntity);
    this.renderer.domElement.addEventListener("pointerleave", () => {
      this.setHoveredEdge();
      this.setHoveredVertex();
    });
    // A click selects, and a selection outlives the pointer leaving the entity —
    // otherwise the only way to look at an edge is to keep the mouse on it.
    // An orbit drag ends in a `click` on the canvas as well, and that click
    // lands wherever the pointer stopped: without the distance test, rotating
    // the view to see the selected edge from behind is what deselects it.
    this.renderer.domElement.addEventListener("pointerdown", (event) => {
      this.pointerDownAt = { x: event.clientX, y: event.clientY };
    });
    this.renderer.domElement.addEventListener("click", (event) => {
      const down = this.pointerDownAt;
      this.pointerDownAt = undefined;
      if (down && Math.hypot(event.clientX - down.x, event.clientY - down.y) > DRAG_SLOP_PX) return;
      this.setSelectedVertex(this.hoveredVertex);
      this.setSelectedEdge(this.hoveredVertex ? undefined : this.hoveredEdge);
    });

    this.scene.add(this.partGroup);
    this.scene.add(this.camera);

    // Image-based lighting does most of the work. A standard material with no
    // environment to reflect has nothing to shade *with*, which is what makes
    // untouched three.js scenes look like flat grey plastic.
    const pmrem = new THREE.PMREMGenerator(this.renderer);
    pmrem.compileEquirectangularShader();
    this.scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
    this.scene.environmentIntensity = 0.62;

    // One fixed sun for directional definition and the cast shadow. Fixed rather
    // than camera-attached: a shadow that swings around as you orbit reads as the
    // part moving, not the camera.
    this.sun = new THREE.DirectionalLight(0xffffff, 1.9);
    this.sun.position.set(-0.5, -0.9, 1.4);
    this.sun.castShadow = true;
    this.sun.shadow.mapSize.set(2048, 2048);
    this.sun.shadow.bias = -0.0012;
    this.scene.add(this.sun);
    this.scene.add(this.sun.target);

    // A weak fill that rides with the camera, so faces turned away from the sun
    // stay readable instead of going black when you orbit behind them.
    const fill = new THREE.DirectionalLight(0xc9d6ee, 0.45);
    fill.position.set(0, 0, 1);
    this.camera.add(fill);
    // A DirectionalLight aims from its position at its *target*, and the target
    // defaults to the world origin — so parenting only the light to the camera
    // leaves it pointing at the scene centre and the fill stops being a fill.
    // The target has to travel with it.
    fill.target.position.set(0, 0, -1);
    this.camera.add(fill.target);

    // Ambient sky/ground light, on only for the preview. The finished view gets
    // its ambient from the environment map, but that is a physically-based
    // feature the preview's cheap material cannot see — without this, any face
    // turned away from the sun goes almost black.
    this.ambient = new THREE.HemisphereLight(0xdfe7f2, 0x6c7382, 2.1);
    this.ambient.visible = false;
    this.scene.add(this.ambient);

    this.outline = new OutlineRenderer(this.renderer, this.scene, this.camera);

    // Depth-tested like the ordinary edges, so a highlight on the far side of
    // the part stays hidden and the solid still reads as solid. Pulled a little
    // toward the camera so it wins against the base edge it is drawn over
    // rather than z-fighting with it.
    const highlight = (color: number, width: number, order: number) => {
      const line = new Line2(
        new LineGeometry(),
        new LineMaterial({
          color,
          linewidth: width,
          transparent: true,
          polygonOffset: true,
          polygonOffsetFactor: -6,
          polygonOffsetUnits: -6,
        }),
      );
      line.visible = false;
      line.renderOrder = order;
      // A highlight is never a pick target. Picking runs against the edge and
      // vertex lists explicitly, so nothing in the app would hit this — but it
      // sits in the scene, and anything that ever raycasts the scene broadly
      // would otherwise select the mark instead of the edge it is marking.
      line.raycast = () => {};
      // Never a shadow caster: this is annotation about the part, not part of it.
      line.castShadow = false;
      line.receiveShadow = false;
      this.scene.add(line);
      return line;
    };
    this.hoverHalo = highlight(HALO, HALO_PX, 4);
    this.hoverCore = highlight(INK, CORE_PX, 5);

    // Resizing is *recorded* here and applied by the frame that draws next.
    // Doing it inline leaves the canvas and the composer's render targets
    // reallocated and empty until the next animation frame, which is the flash
    // of background you see while dragging the splitter or the window edge —
    // and during a drag the observer fires many times per frame, so the same
    // flash repeats. One resize per frame, immediately followed by the render
    // that fills it.
    const ro = new ResizeObserver(() => {
      this.pendingResize = true;
    });
    ro.observe(container);
    this.resize();

    this.tick();
  }

  private resize() {
    const w = this.container.clientWidth;
    const h = this.container.clientHeight;
    // A pane with no size yet stays pending rather than being marked done.
    if (w === 0 || h === 0) return;
    this.pendingResize = false;
    // Let three set the CSS size as well as the drawing buffer. Passing
    // `false` here sizes the buffer to w * devicePixelRatio but leaves the
    // element's layout size alone, so on a retina display the canvas lays out at
    // twice its pane and spills off the bottom-right corner.
    this.renderer.setSize(w, h);
    this.camera.aspect = w / h;
    this.camera.updateProjectionMatrix();
    this.outline?.setSize(w, h);

    // A fat line is a screen-space quad, so its material has to be told how big
    // the screen is or its width means nothing. The *drawing buffer*, not the
    // CSS box: they differ by the device pixel ratio, and passing the CSS size
    // on a retina display draws every highlight at twice its nominal width.
    // The widths are then in device pixels, so they are scaled by the same
    // ratio to keep the highlight the same size to the eye on any display.
    const buffer = this.renderer.getDrawingBufferSize(new THREE.Vector2());
    const ratio = this.renderer.getPixelRatio();
    for (const [line, width] of [
      [this.hoverHalo, HALO_PX],
      [this.hoverCore, CORE_PX],
    ] as const) {
      const material = line?.material as LineMaterial | undefined;
      if (!material) continue;
      material.resolution.set(buffer.x, buffer.y);
      material.linewidth = width * ratio;
    }
  }

  private tick = () => {
    this.frame = requestAnimationFrame(this.tick);
    if (this.pendingResize) this.resize();
    this.controls.update();
    if (this.preview || DEBUG === "noedge" || DEBUG === "normals") {
      // No edge pass in preview mode. Finding creases from neighbouring pixels
      // is guesswork, and on a dual-contoured mesh the guess lands on the
      // zigzag of vertices that stands in for a sharp edge — which is what made
      // this view look like a bad mesh instead of an honest one.
      this.renderer.render(this.scene, this.camera);
    } else {
      // Only the part gets edges; the grid is scenery, not geometry.
      this.outline.render([this.partGroup]);
    }
  };

  /**
   * A PNG of what is on screen right now, scaled to fit `size`.
   *
   * The renderer has no `preserveDrawingBuffer`, so the canvas is empty by the
   * time anything reads it — the buffer is cleared after each frame is
   * presented. Drawing once here, synchronously, and copying immediately is
   * what makes the read return the picture rather than a transparent
   * rectangle; turning the flag on instead would cost every frame of every
   * session for a picture taken on save.
   */
  snapshot(size = 512): string {
    this.tickOnce();
    const canvas = this.renderer.domElement;
    if (!canvas.width || !canvas.height) return "";

    const scale = Math.min(1, size / Math.max(canvas.width, canvas.height));
    const out = document.createElement("canvas");
    out.width = Math.max(1, Math.round(canvas.width * scale));
    out.height = Math.max(1, Math.round(canvas.height * scale));
    const context = out.getContext("2d");
    if (!context) return "";
    context.drawImage(canvas, 0, 0, out.width, out.height);
    return out.toDataURL("image/png");
  }

  /** One frame, outside the animation loop, for `snapshot` to read. */
  private tickOnce() {
    if (this.pendingResize) this.resize();
    if (this.preview || DEBUG === "noedge" || DEBUG === "normals") {
      this.renderer.render(this.scene, this.camera);
    } else {
      this.outline.render([this.partGroup]);
    }
  }

  dispose() {
    cancelAnimationFrame(this.frame);
    this.renderer.domElement.removeEventListener("pointermove", this.pickEntity);
    this.renderer.domElement.removeEventListener("mousemove", this.pickEntity);
    this.outline.dispose();
    this.renderer.dispose();
  }

  /** Find the visible B-rep entity beneath the pointer. */
  private pickEntity = (event: PointerEvent | MouseEvent) => {
    if (this.preview || this.edgeLines.length === 0) return;

    const rect = this.renderer.domElement.getBoundingClientRect();
    const pointer = new THREE.Vector2(
      ((event.clientX - rect.left) / rect.width) * 2 - 1,
      -((event.clientY - rect.top) / rect.height) * 2 + 1,
    );
    this.edgeRaycaster.setFromCamera(pointer, this.camera);

    // A fixed world-space hit radius feels either tiny on a large part or huge
    // when zoomed in. Twelve screen pixels make a one-pixel CAD edge practical
    // to inspect without turning a nearby face click into a different feature.
    const distance = this.camera.position.distanceTo(this.controls.target);
    const visibleHeight = 2 * Math.tan((this.camera.fov * Math.PI) / 360) * distance;
    this.edgeRaycaster.params.Line!.threshold = (visibleHeight / rect.height) * 12;
    this.vertexRaycaster.params.Points!.threshold = (visibleHeight / rect.height) * 9;

    this.vertexRaycaster.setFromCamera(pointer, this.camera);
    const vertexHit = this.vertexRaycaster.intersectObjects(this.vertexMarkers, false)[0];
    const edgeHit = this.edgeRaycaster.intersectObjects(this.edgeLines, false)[0];
    const vertex = vertexHit?.object as THREE.Points | undefined;
    this.setHoveredVertex(vertex);
    const edge = vertex ? undefined : (edgeHit?.object as THREE.LineSegments | undefined);
    this.setHoveredEdge(edge);

    // A face is what you get when you are not on anything smaller. Corners beat
    // edges and edges beat faces, because the smaller the entity the harder it
    // is to put a pointer on and the more specific the thing you meant.
    if (vertex || edge || !this.partMesh || this.faceRuns.length === 0) {
      this.setHoveredFace(undefined);
      return;
    }
    this.edgeRaycaster.setFromCamera(pointer, this.camera);
    const surface = this.edgeRaycaster.intersectObject(this.partMesh, false)[0];
    const triangle = surface?.faceIndex;
    this.setHoveredFace(
      triangle === undefined || triangle === null ? undefined : this.faceAt(triangle),
    );
  };

  /** Which face a triangle belongs to, by the runs the kernel reported. */
  private faceAt(triangle: number): FacePick | undefined {
    for (const run of this.faceRuns) {
      if (triangle >= run.start && triangle < run.start + run.count) {
        return { face: run.face, run, triangles: run.count };
      }
    }
    return undefined;
  }

  private setHoveredFace(next?: FacePick) {
    if (next?.face === this.hoveredFace?.face) return;
    this.hoveredFace = next;
    this.showFaceHighlight(next);
    this.edgeCallbacks.onFaceHover?.(next);
  }

  /**
   * Lay a lit patch over the hovered face, or take it away.
   *
   * The patch is a copy of the face's triangles rather than a re-render of the
   * part with a second material: the part is one mesh with one material, and
   * splitting it into a group per face to colour one of them would change what
   * the renderer draws for every frame in order to change what one hover looks
   * like.
   */
  private showFaceHighlight(face?: FacePick) {
    if (this.faceHighlight) {
      this.faceHighlight.parent?.remove(this.faceHighlight);
      this.faceHighlight.geometry.dispose();
      this.faceHighlight = undefined;
    }
    if (!face || !this.partMesh) return;

    const source = this.partMesh.geometry;
    const index = source.getIndex();
    if (!index) return;

    const patch = new THREE.BufferGeometry();
    patch.setAttribute("position", source.getAttribute("position"));
    patch.setIndex(
      new THREE.Uint32BufferAttribute(
        Array.from(index.array).slice(face.run.start * 3, (face.run.start + face.run.count) * 3),
        1,
      ),
    );

    const mesh = new THREE.Mesh(
      patch,
      new THREE.MeshBasicMaterial({
        color: HALO,
        transparent: true,
        opacity: 0.22,
        blending: THREE.AdditiveBlending,
        depthWrite: false,
        // Coplanar with the face it covers, so it needs pulling forward or the
        // two z-fight into a shimmer as the camera moves.
        polygonOffset: true,
        polygonOffsetFactor: -4,
        polygonOffsetUnits: -4,
        side: THREE.DoubleSide,
        clippingPlanes: this.clipPlanes.length > 0 ? this.clipPlanes : null,
      }),
    );
    mesh.renderOrder = 3;
    mesh.castShadow = false;
    mesh.receiveShadow = false;
    mesh.raycast = () => {};

    // The white edge around the patch — the same job the halo does for an edge,
    // separating the lit face from whatever it sits against. `EdgesGeometry`
    // drops every edge between two near-coplanar triangles, so on a flat face
    // the tessellation disappears and only the boundary survives. On a curved
    // one some internal edges remain, which reads as the shading it is drawn
    // over rather than as noise; and a boundary onto a *tangent* neighbour —
    // a fillet running out into its wall — has no angle to find and is not
    // drawn. That is a real limit, and the tint is what carries the highlight
    // there.
    const outline = new THREE.LineSegments(
      new THREE.EdgesGeometry(patch, 25),
      new THREE.LineBasicMaterial({
        color: HALO,
        transparent: true,
        opacity: 0.85,
        depthWrite: false,
        clippingPlanes: this.clipPlanes.length > 0 ? this.clipPlanes : null,
      }),
    );
    outline.renderOrder = 4;
    outline.raycast = () => {};
    mesh.add(outline);

    this.faceHighlight = mesh;
    this.partMesh.add(mesh);
  }

  private setHoveredEdge(next?: THREE.LineSegments) {
    if (next === this.hoveredEdge) return;
    const previous = this.hoveredEdge;
    this.hoveredEdge = next;
    this.paintEdge(previous);
    this.paintEdge(next);
    this.showEdgeHighlight(next);
    this.edgeCallbacks.onHover?.(next?.userData.edge as EdgeCurve | undefined);
  }

  private setSelectedEdge(next?: THREE.LineSegments) {
    if (next === this.selectedEdge) return;
    const previous = this.selectedEdge;
    this.selectedEdge = next;
    this.paintEdge(previous);
    this.paintEdge(next);
    this.edgeCallbacks.onSelect?.(next?.userData.edge as EdgeCurve | undefined);
  }

  /**
   * The base edge's own colour. Gold when it is the pinned selection, otherwise
   * the ordinary edge grey — the *hover* is drawn by the halo below rather than
   * by recolouring the line, so an edge under the cursor keeps looking like the
   * part's edge instead of turning into a different one.
   */
  private paintEdge(line?: THREE.LineSegments) {
    if (!line) return;
    const material = line.material as THREE.LineBasicMaterial;
    material.color.setHex(line === this.selectedEdge ? 0xf5b942 : 0x2b3440);
    material.opacity = line === this.selectedEdge ? 1 : 0.85;
  }

  /**
   * Lay the halo and core over the hovered edge, or put them away.
   *
   * The polyline is rebuilt rather than a per-edge highlight being kept for
   * every edge: a part with a hundred edges would otherwise carry two hundred
   * fat lines that are invisible almost all of the time.
   */
  private showEdgeHighlight(line?: THREE.LineSegments) {
    const edge = line?.userData.edge as EdgeCurve | undefined;
    if (!edge || edge.points.length < 2) {
      this.hoverHalo.visible = false;
      this.hoverCore.visible = false;
      return;
    }
    const flat = edge.points.flat();
    for (const target of [this.hoverHalo, this.hoverCore]) {
      const geometry = new LineGeometry();
      geometry.setPositions(flat);
      target.geometry.dispose();
      target.geometry = geometry;
      target.computeLineDistances();
      target.visible = true;
    }
  }

  private setHoveredVertex(next?: THREE.Points) {
    if (next === this.hoveredVertex) return;
    const previous = this.hoveredVertex;
    this.hoveredVertex = next;
    this.paintVertex(previous);
    this.paintVertex(next);
    this.edgeCallbacks.onVertexHover?.(next?.userData.vertex as VertexPoint | undefined);
  }

  private setSelectedVertex(next?: THREE.Points) {
    if (next === this.selectedVertex) return;
    const previous = this.selectedVertex;
    this.selectedVertex = next;
    this.paintVertex(previous);
    this.paintVertex(next);
    this.edgeCallbacks.onVertexSelect?.(next?.userData.vertex as VertexPoint | undefined);
  }

  /**
   * A corner is drawn only while it is being pointed at.
   *
   * Every edge endpoint is a pickable corner, so showing them all put a grey
   * dot on every vertex of the model at all times — dozens of marks about
   * nothing, over the one thing the window is for looking at. `material.visible`
   * rather than `object.visible`, because the renderer skips the first and the
   * raycaster still sees the object: a corner you cannot see is still a corner
   * you can hover.
   */
  private paintVertex(marker?: THREE.Points) {
    if (!marker) return;
    const shown = marker === this.hoveredVertex || marker === this.selectedVertex;
    marker.material =
      marker === this.selectedVertex
        ? vertexMaterial("selected")
        : shown
          ? vertexMaterial("hover")
          : vertexMaterial("hidden");
  }

  /** Replace the displayed part. */
  setGeometry(geo: Geometry, bounds: Bounds) {
    this.clearPart();

    const g = new THREE.BufferGeometry();
    g.setAttribute("position", new THREE.BufferAttribute(geo.positions, 3));
    g.setAttribute("normal", new THREE.BufferAttribute(geo.normals, 3));
    // Expanded triangles carry per-corner normals, so there is nothing to index.
    if (geo.indices.length > 0) {
      g.setIndex(new THREE.BufferAttribute(geo.indices, 1));
    }
    g.computeBoundingSphere();

    const hasRealEdges = !!geo.edges?.length;
    this.preview = !hasRealEdges;
    this.ambient.visible = this.preview;

    // Mesh preview has no logical edge curves, but it does provide
    // surface-aware normals for every triangle corner. Preserve those normals:
    // flat shading turns a smooth cylinder or fillet into visible facets even
    // when the sampled surface is otherwise accurate enough for previewing.
    const mesh = new THREE.Mesh(
      g,
      DEBUG === "normals"
        ? new THREE.MeshNormalMaterial()
        : this.preview
          ? new THREE.MeshLambertMaterial({
              color: 0x9aa6b6,
              emissive: 0x0c1018,
            })
          : new THREE.MeshStandardMaterial({
              color: 0xaeb8c6,
              roughness: 0.46,
              metalness: 0.1,
              envMapIntensity: 1.0,
              flatShading: DEBUG === "flat",
              // Push the shaded surface a hair away from the viewer so the edge
              // lines, which lie exactly on it, win the depth test instead of
              // stitching in and out of it.
              polygonOffset: true,
              polygonOffsetFactor: 1,
              polygonOffsetUnits: 1,
            }),
    );
    mesh.castShadow = true;
    // The part does not receive its own shadow. A hard shadow of the fin thrown
    // across the base plate is physically right and reads as a mark *on* the
    // plate — a discoloured patch, or a step that is not there. Fusion makes
    // the same call: cast onto the ground, never onto yourself. Crevices still
    // darken, but from ambient occlusion, which follows the geometry rather
    // than one arbitrary light direction.
    mesh.receiveShadow = false;
    this.partGroup.add(mesh);
    this.partMesh = mesh;
    this.partBounds = bounds;

    if (hasRealEdges) {
      // Note what is *not* here: `EdgesGeometry`. That finds an edge wherever
      // two adjacent triangles differ by more than a threshold, which assumes a
      // tidy triangulation. Dual contouring produces nothing of the sort. These
      // lines are not inferred from triangles at all; they are the kernel's own
      // curves, sampled. A straight edge is two points.
      const renderedEdges = edgeLines(geo.edges!);
      this.partGroup.add(renderedEdges.group);
      this.edgeLines.push(...renderedEdges.lines);
      const renderedVertices = vertexMarkers(verticesFromEdges(geo.edges!));
      this.partGroup.add(renderedVertices.group);
      this.vertexMarkers.push(...renderedVertices.markers);
      // Only the exact kernel attributes a triangle to a face. Left empty
      // otherwise, which is what makes faces unpickable rather than wrongly
      // picked — see `faceRuns` on `Geometry`.
      this.faceRuns = geo.faceRuns ?? [];
    } else {
      // Show the sampling grid in a restrained weight: it identifies this as a
      // mesh preview while leaving the smoothed surface readable.
      this.partGroup.add(meshWireframe(g));
    }
    // Stop guessing at creases once we are being told where they are. The
    // silhouette half of the pass stays on regardless: the outline of a
    // cylinder is where the surface turns away from the camera, which is a
    // property of the view, not of the solid, so no kernel can supply it.
    this.outline.setCreases(false);

    const size = {
      x: bounds.max.x - bounds.min.x,
      y: bounds.max.y - bounds.min.y,
      z: bounds.max.z - bounds.min.z,
    };
    this.placeGround(bounds, size);
    this.aimSun(bounds, size);

    // A new part keeps the plane the last one was cut on. Editing a script and
    // having the section silently close is worse than either alternative: the
    // whole reason it is open is to watch one internal feature change.
    this.applyClipping();
    this.buildCap(this.section);
  }

  /** The plane currently cut, if any — `setSection`'s argument, remembered. */
  private section?: SectionPlane;

  /**
   * Cut the part open on a plane, or stop.
   *
   * The same feature the agent gets through `evaluate_part`'s `section`, and for
   * the same reason: a bore that stops short, a rib inside a boss, the wall
   * between two pockets are in no view of the outside. What differs is only the
   * means — there the raster counts the crossings it clipped away and caps where
   * the count is odd, here the GPU does the identical parity count in its
   * stencil buffer while drawing the part's own back and front faces.
   */
  setSection(section?: SectionPlane) {
    this.section = section;
    this.clipPlanes.length = 0;
    if (section) {
      // three.js keeps the half-space where dot(normal, p) + constant > 0, so
      // the normal points *into* the material that survives.
      const sign = section.keep === "below" ? -1 : 1;
      const normal = new THREE.Vector3(
        section.axis === "x" ? sign : 0,
        section.axis === "y" ? sign : 0,
        section.axis === "z" ? sign : 0,
      );
      this.clipPlanes.push(new THREE.Plane(normal, -sign * section.atMm));
    }

    this.applyClipping();
    this.buildCap(section);
    this.outline.setClippingPlanes(this.clipPlanes);
  }

  /**
   * Which half to keep so the cut faces the camera.
   *
   * `Section::resolve` in the kernel, with an orbiting camera in place of a
   * fixed view: the half that has to go is the one between the plane and the
   * viewer. Keep the other one and the section is behind the material that
   * survives — a part that looks entirely uncut, which is the one way a section
   * can be wrong without looking wrong.
   */
  keepFacingCamera(axis: "x" | "y" | "z"): "below" | "above" {
    const toward = this.camera.position.clone().sub(this.controls.target);
    return toward[axis] > 0 ? "below" : "above";
  }

  /** Hand the current plane to everything the part is drawn with. */
  private applyClipping() {
    const planes = this.clipPlanes.length > 0 ? this.clipPlanes : null;
    this.partGroup.traverse((object) => {
      const drawable = object as THREE.Mesh | THREE.LineSegments;
      const material = drawable.material;
      if (!material) return;
      for (const m of Array.isArray(material) ? material : [material]) {
        const before = m.clippingPlanes?.length ?? 0;
        m.clippingPlanes = planes;
        // The part still casts a shadow of the half that is left, not of the
        // half that went.
        m.clipShadows = true;
        // How many clipping planes there are is compiled *into* the shader, so
        // a material that already has a program keeps using one with no clip
        // test in it. Nothing errors; the plane is simply ignored, which is a
        // section that quietly does not cut.
        if (before !== (planes?.length ?? 0)) m.needsUpdate = true;
      }
    });
  }

  /**
   * Fill the cut with a flat face, so a section reads as solid material.
   *
   * Without this the part is a hollow shell: clipping removes the near half of
   * the *surface* and leaves you looking at the inside of the far half, which is
   * exactly as misleading as it sounds — an agent reading the same picture would
   * call a solid boss a thin cup.
   *
   * The trick is the standard one. Draw the part's back faces incrementing the
   * stencil and its front faces decrementing it, both invisibly and both clipped
   * by the same plane; where the counts do not cancel, the ray was inside
   * material when it crossed the plane. Then paint a quad on the plane wherever
   * the stencil is non-zero.
   */
  private buildCap(section?: SectionPlane) {
    if (this.sectionGroup) {
      this.scene.remove(this.sectionGroup);
      disposeTree(this.sectionGroup);
      this.sectionGroup = undefined;
    }
    if (!section || !this.partMesh || !this.partBounds) return;

    const group = new THREE.Group();
    const geometry = this.partMesh.geometry;

    for (const [side, op] of [
      [THREE.BackSide, THREE.IncrementWrapStencilOp],
      [THREE.FrontSide, THREE.DecrementWrapStencilOp],
    ] as const) {
      const material = new THREE.MeshBasicMaterial({
        side,
        clippingPlanes: this.clipPlanes,
        // Counting, not drawing: no colour, no depth, and no depth test, so a
        // crossing is counted wherever it is rather than only where it is
        // nearest.
        colorWrite: false,
        depthWrite: false,
        depthTest: false,
        stencilWrite: true,
        stencilFunc: THREE.AlwaysStencilFunc,
        stencilFail: op,
        stencilZFail: op,
        stencilZPass: op,
      });
      const counter = new THREE.Mesh(geometry, material);
      counter.renderOrder = -2;
      group.add(counter);
    }

    const size = Math.max(
      this.partBounds.max.x - this.partBounds.min.x,
      this.partBounds.max.y - this.partBounds.min.y,
      this.partBounds.max.z - this.partBounds.min.z,
    );
    const cap = new THREE.Mesh(
      new THREE.PlaneGeometry(size * 3, size * 3),
      new THREE.MeshBasicMaterial({
        color: CUT_FACE,
        side: THREE.DoubleSide,
        stencilWrite: true,
        stencilRef: 0,
        stencilFunc: THREE.NotEqualStencilFunc,
        // Reset as it draws, so the next frame starts from a clean buffer.
        stencilFail: THREE.ReplaceStencilOp,
        stencilZFail: THREE.ReplaceStencilOp,
        stencilZPass: THREE.ReplaceStencilOp,
      }),
    );
    // A quad in XY facing +Z, turned to face along the section axis.
    if (section.axis === "x") cap.rotateY(Math.PI / 2);
    if (section.axis === "y") cap.rotateX(Math.PI / 2);
    const centre = {
      x: (this.partBounds.min.x + this.partBounds.max.x) / 2,
      y: (this.partBounds.min.y + this.partBounds.max.y) / 2,
      z: (this.partBounds.min.z + this.partBounds.max.z) / 2,
    };
    cap.position.set(centre.x, centre.y, centre.z);
    cap.position[section.axis] = section.atMm;
    cap.renderOrder = -1;
    cap.castShadow = false;
    cap.receiveShadow = false;
    group.add(cap);

    // In the scene rather than in `partGroup`: the outline pass hides every
    // mesh that is not part of what it was asked to outline, which is exactly
    // what these need — the stencil helpers are the *unclipped* part, and left
    // visible they would fill the normal buffer with the shape that was cut
    // away.
    this.sectionGroup = group;
    this.scene.add(group);
  }

  /** Overlay exact pre-treatment entities selected from the editor source. */
  setTargetPreview(edges: EdgeCurve[], vertices: TargetVertex[] = []) {
    this.clearTargetPreview();
    if (edges.length === 0 && vertices.length === 0) return;

    const group = new THREE.Group();
    if (edges.length > 0) {
      const rendered = edgeLines(edges, 0xf5b942, 1);
      for (const line of rendered.lines) {
        const material = line.material as THREE.LineBasicMaterial;
        // Target curves can have been consumed by a fillet, so draw the exact
        // input over the finished surface instead of letting it disappear behind
        // the replacement faces. They are not added to the raycast set.
        material.depthTest = false;
        line.renderOrder = 2;
      }
      group.add(rendered.group);
    }
    if (vertices.length > 0) group.add(targetVertexMarkers(vertices));
    this.targetPreview = group;
    this.partGroup.add(group);
  }

  private clearTargetPreview() {
    if (!this.targetPreview) return;
    this.partGroup.remove(this.targetPreview);
    disposeTree(this.targetPreview);
    this.targetPreview = undefined;
  }

  /** Show nothing, without disturbing the camera. */
  clearPart() {
    this.clearTargetPreview();
    if (this.sectionGroup) {
      this.scene.remove(this.sectionGroup);
      disposeTree(this.sectionGroup);
      this.sectionGroup = undefined;
    }
    this.partMesh = undefined;
    this.hoveredEdge = undefined;
    this.selectedEdge = undefined;
    this.hoveredVertex = undefined;
    this.selectedVertex = undefined;
    this.edgeLines.length = 0;
    this.vertexMarkers.length = 0;
    this.faceRuns = [];
    this.hoveredFace = undefined;
    this.faceHighlight = undefined;
    // The highlight lives on the scene rather than in the part group, so it has
    // to be put away by hand — a halo left tracing an edge of the part that was
    // just replaced is a mark about geometry that is no longer there.
    this.showEdgeHighlight(undefined);
    this.edgeCallbacks.onHover?.(undefined);
    this.edgeCallbacks.onSelect?.(undefined);
    this.edgeCallbacks.onVertexHover?.(undefined);
    this.edgeCallbacks.onVertexSelect?.(undefined);
    for (const child of [...this.partGroup.children]) {
      this.partGroup.remove(child);
      child.traverse((o) => {
        const drawable = o as THREE.Mesh | THREE.LineSegments;
        drawable.geometry?.dispose();
        releaseMaterial(drawable.material);
      });
    }
  }

  /**
   * Grid and shadow-catcher, sitting on the bottom of the part.
   *
   * The shadow is the point. A part floating against a flat background has no
   * cue for where it sits or how far it stands off; a contact shadow supplies
   * both for almost nothing.
   */
  private placeGround(bounds: Bounds, size: { x: number; y: number; z: number }) {
    const extent = Math.max(size.x, size.y, size.z);
    const step = niceStep(extent / 10);
    const span = Math.max(step * 20, extent * 3);
    const z = bounds.min.z;

    if (this.grid) {
      this.scene.remove(this.grid);
      this.grid.dispose();
    }
    this.grid = new THREE.GridHelper(
      span,
      Math.max(2, Math.round(span / step)),
      0x8b96a6,
      0xb4bdc9,
    );
    // GridHelper lies in XZ; stand it up so it is the XY ground plane.
    this.grid.rotateX(Math.PI / 2);
    this.grid.position.z = z;
    this.scene.add(this.grid);

    if (this.ground) {
      this.scene.remove(this.ground);
      this.ground.geometry.dispose();
    }
    this.ground = new THREE.Mesh(
      new THREE.PlaneGeometry(span, span),
      new THREE.ShadowMaterial({ opacity: 0.22 }),
    );
    this.ground.position.z = z - 0.01;
    this.ground.receiveShadow = true;
    this.scene.add(this.ground);
  }

  /** Point the sun at the part and tighten its shadow frustum around it. */
  private aimSun(bounds: Bounds, size: { x: number; y: number; z: number }) {
    const radius = Math.max(1e-3, Math.hypot(size.x, size.y, size.z) / 2);
    const center = new THREE.Vector3(
      (bounds.min.x + bounds.max.x) / 2,
      (bounds.min.y + bounds.max.y) / 2,
      (bounds.min.z + bounds.max.z) / 2,
    );

    const dir = new THREE.Vector3(-0.5, -0.9, 1.4).normalize();
    this.sun.position.copy(center).addScaledVector(dir, radius * 4);
    this.sun.target.position.copy(center);
    this.sun.target.updateMatrixWorld();

    // A shadow camera much larger than the part spends all its resolution on
    // empty space, and the shadow turns to mush.
    const cam = this.sun.shadow.camera;
    cam.left = -radius * 1.6;
    cam.right = radius * 1.6;
    cam.top = radius * 1.6;
    cam.bottom = -radius * 1.6;
    cam.near = radius * 0.5;
    cam.far = radius * 9;
    cam.updateProjectionMatrix();
  }

  /** Frame the part, filling the view. */
  frameAll(bounds: Bounds) {
    const size = {
      x: bounds.max.x - bounds.min.x,
      y: bounds.max.y - bounds.min.y,
      z: bounds.max.z - bounds.min.z,
    };
    const center = new THREE.Vector3(
      (bounds.min.x + bounds.max.x) / 2,
      (bounds.min.y + bounds.max.y) / 2,
      (bounds.min.z + bounds.max.z) / 2,
    );

    const radius = Math.max(1e-3, Math.hypot(size.x, size.y, size.z) / 2);

    // Fit against whichever field of view is *narrower*. `camera.fov` is the
    // vertical one, so on a tall narrow pane — which is exactly what a
    // side-by-side editor leaves — fitting to it alone crops the part off both
    // sides.
    const vFov = (this.camera.fov * Math.PI) / 180;
    const hFov = 2 * Math.atan(Math.tan(vFov / 2) * this.camera.aspect);
    const fov = Math.min(vFov, hFov);
    const distance = (radius / Math.sin(fov / 2)) * 1.06;

    const dir = new THREE.Vector3(0.72, -1, 0.62).normalize();
    this.camera.position.copy(center).addScaledVector(dir, distance);
    // Hug the part. A frustum spanning five orders of magnitude leaves the
    // depth buffer with almost no precision across the part itself, and the
    // outline pass reads that buffer.
    this.camera.near = Math.max(distance - radius * 3, distance * 0.02);
    this.camera.far = distance + radius * 6;
    this.camera.updateProjectionMatrix();

    this.controls.target.copy(center);
    this.controls.update();
  }
}

/**
 * Turn logical edges into independently pickable drawables.
 *
 * Parts currently expose tens or low hundreds of B-rep edges. That keeps a
 * separate line primitive per edge much simpler and more useful than colour-ID
 * GPU picking, while still being negligible beside the shaded part.
 */
function edgeLines(
  edges: EdgeCurve[],
  color = 0x2b3440,
  opacity = 0.85,
): { group: THREE.Group; lines: THREE.LineSegments[] } {
  const group = new THREE.Group();
  const lines: THREE.LineSegments[] = [];
  for (const edge of edges) {
    const pts: number[] = [];
    for (let i = 0; i + 1 < edge.points.length; i++) {
      pts.push(...edge.points[i], ...edge.points[i + 1]);
    }
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(pts, 3));
    const line = new THREE.LineSegments(
      geometry,
      new THREE.LineBasicMaterial({ color, transparent: true, opacity }),
    );
    line.userData.edge = edge;
    // Edges are annotation, not geometry to be lit or to cast shadows.
    line.castShadow = false;
    line.receiveShadow = false;
    // Depth-tested, so far-side edges stay hidden and the model reads solid.
    line.renderOrder = 1;
    group.add(line);
    lines.push(line);
  }
  return { group, lines };
}

/**
 * The corner sprite: a white disc, a near-black ring, and a white glow outside
 * it — drawn once into a canvas and shared by every marker.
 *
 * A `PointsMaterial` square with a colour cannot be this shape, and the glow in
 * particular has no other cheap route: it is what keeps the marker readable
 * where a corner sits against the bright background rather than against the
 * part.
 */
function cornerSprite(fill: string, ring: string): THREE.Texture {
  const size = 64;
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext("2d")!;
  const centre = size / 2;

  // The glow first, and wider than the ring, so it reads as a halo around the
  // whole mark rather than as a smudge under it.
  ctx.shadowColor = "rgba(255,255,255,0.95)";
  ctx.shadowBlur = 9;
  ctx.fillStyle = "rgba(255,255,255,0.9)";
  ctx.beginPath();
  ctx.arc(centre, centre, 19, 0, Math.PI * 2);
  ctx.fill();
  ctx.shadowBlur = 0;

  ctx.beginPath();
  ctx.arc(centre, centre, 14, 0, Math.PI * 2);
  ctx.fillStyle = fill;
  ctx.fill();
  ctx.lineWidth = 5;
  ctx.strokeStyle = ring;
  ctx.stroke();

  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
}

/**
 * The three states a corner can be in, as three shared materials.
 *
 * Shared rather than one per marker: a part has as many corners as it has edge
 * endpoints, and every one of them would otherwise carry its own texture.
 * Built lazily so a module import does not need a DOM.
 */
const VERTEX_MATERIALS: Partial<Record<"hidden" | "hover" | "selected", THREE.PointsMaterial>> = {};

function vertexMaterial(state: "hidden" | "hover" | "selected"): THREE.PointsMaterial {
  const existing = VERTEX_MATERIALS[state];
  if (existing) return existing;

  const made =
    state === "hidden"
      ? // Not drawn, but still raycast — see `paintVertex`.
        new THREE.PointsMaterial({ visible: false })
      : new THREE.PointsMaterial({
          map: cornerSprite(state === "selected" ? "#f5b942" : "#ffffff", "#0b0e13"),
          size: state === "selected" ? 15 : 13,
          sizeAttenuation: false,
          transparent: true,
          depthWrite: false,
        });
  made.userData.shared = true;
  VERTEX_MATERIALS[state] = made;
  return made;
}

/** Turn exact edge endpoints into pickable corners, drawn only when pointed at. */
function vertexMarkers(vertices: VertexPoint[]): { group: THREE.Group; markers: THREE.Points[] } {
  const group = new THREE.Group();
  const markers: THREE.Points[] = [];
  for (const vertex of vertices) {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertex.point, 3));
    const marker = new THREE.Points(geometry, vertexMaterial("hidden"));
    marker.userData.vertex = vertex;
    marker.castShadow = false;
    marker.receiveShadow = false;
    marker.renderOrder = 2;
    group.add(marker);
    markers.push(marker);
  }
  return { group, markers };
}

/** Gold exact corner targets, intentionally visible through their replacement patch. */
function targetVertexMarkers(vertices: TargetVertex[]): THREE.Group {
  const group = new THREE.Group();
  for (const vertex of vertices) {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertex.point, 3));
    const marker = new THREE.Points(
      geometry,
      new THREE.PointsMaterial({
        color: 0xf5b942,
        size: 12,
        sizeAttenuation: false,
        depthTest: false,
        transparent: true,
        opacity: 1,
      }),
    );
    marker.renderOrder = 3;
    group.add(marker);
  }
  return group;
}

/**
 * The triangle edges of a mesh, drawn faintly over it.
 *
 * Only for the mesh preview. It shows where the mesher sampled densely or
 * sparsely without overpowering the smoothed surface.
 */
function meshWireframe(g: THREE.BufferGeometry): THREE.LineSegments {
  const lines = new THREE.LineSegments(
    new THREE.WireframeGeometry(g),
    // Faint: at fifty thousand triangles a solid wireframe is a grey wall.
    // Low opacity lets density itself carry the information — dense where the
    // mesher subdivided, sparse where it did not.
    new THREE.LineBasicMaterial({ color: 0x2b3440, transparent: true, opacity: 0.45 }),
  );
  lines.castShadow = false;
  lines.receiveShadow = false;
  return lines;
}

/**
 * Drop everything under an object.
 *
 * Geometry is *not* disposed here: the stencil helpers share the part's own
 * buffers, and disposing those with the cap would take the part with it.
 */
/**
 * Free a material unless it is one of the shared ones.
 *
 * The corner materials below are deliberately shared by every marker on the
 * part, so the ordinary "dispose everything under this object" sweep would free
 * them on the first rebuild and every later part would be drawing with a
 * material whose GPU program had been thrown away. Sharing them and freeing
 * them per-object are both reasonable; doing both is not.
 */
function releaseMaterial(material: THREE.Material | THREE.Material[] | undefined) {
  if (!material) return;
  if (Array.isArray(material)) {
    material.forEach(releaseMaterial);
    return;
  }
  if (material.userData.shared) return;
  material.dispose();
}

function disposeTree(root: THREE.Object3D) {
  root.traverse((object) => {
    const drawable = object as THREE.Mesh | THREE.LineSegments;
    releaseMaterial(drawable.material);
  });
}

/** Round to 1, 2 or 5 times a power of ten. */
function niceStep(v: number): number {
  if (!(v > 0) || !Number.isFinite(v)) return 1;
  const decade = 10 ** Math.floor(Math.log10(v));
  const n = v / decade;
  const snapped = n < 1.5 ? 1 : n < 3.5 ? 2 : n < 7.5 ? 5 : 10;
  return snapped * decade;
}


/** Vertical gradient used as the canvas backdrop. */
function gradientTexture(): THREE.Texture {
  const c = document.createElement("canvas");
  c.width = 2;
  c.height = 256;
  const ctx = c.getContext("2d")!;
  const g = ctx.createLinearGradient(0, 0, 0, 256);
  g.addColorStop(0, BG_TOP);
  g.addColorStop(1, BG_BOTTOM);
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 2, 256);

  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  return tex;
}
