#!/usr/bin/env bun
/**
 * Turn a section fuzz run into the checked-in corpus: one outline for each
 * family, verdict pattern and kind of message, with every layer's verdict.
 *
 *   tools/section-fuzz.sh --keep DIR
 *   bun tools/section-promote.ts DIR/verdicts.jsonl [more.jsonl ...] > eval/sections.json
 *
 * A verdict whose id starts `pinned/` is always kept, and the generator reads
 * those back out of the corpus: that is how an outline found in a real part
 * stays in the corpus.
 *
 * `eval/sections.json` is then what the three layers are held to: the DSL by
 * `app/src/section-corpus.test.ts`, the core by `agrees_with_the_shared_section_corpus`
 * in `section_crossing.rs`, the kernel by the test of the same name in
 * `crates/parcad-occt/src/backend.rs`. A change to one layer's verdict turns
 * its test red; rerun this to accept it, and read the diff.
 */

import { readFileSync } from "node:fs";

type Verdict = { ok: true } | { ok: false; message: string } | null;
interface Row {
  id: string;
  family: string;
  outline: unknown[];
  dsl: Verdict;
  core: Verdict;
  kernel: Verdict;
  kernel_alone?: boolean;
  crash?: string;
  ms?: number;
  why?: string;
}

/** A kernel case slower than this stays in the fuzz run and out of the gate. */
const KERNEL_BUDGET_MS = 150;

const shape = (message: string) => message.replace(/-?\d[\d.e-]*/g, "#").slice(0, 110);
/** The kernel's first sentence: its reason, without the measured numbers after it. */
const firstSentence = (message: string) => message.split(/\. /)[0];

const rows: Row[] = process.argv
  .slice(2)
  .flatMap((file) => readFileSync(file, "utf8").split("\n"))
  .filter((l) => l.trim())
  .map((l) => JSON.parse(l));

function expected(v: Verdict, whole: boolean) {
  if (v === null) return null;
  if (v.ok) return { ok: true };
  return { refuses: whole ? v.message : firstSentence(v.message) };
}

function why(row: Row): string {
  const ok = (v: Verdict) => (v === null ? null : v.ok);
  const [d, c, k] = [ok(row.dsl), ok(row.core), ok(row.kernel)];
  if (row.crash) return `${row.family}: the core refuses what would abort the kernel if it were asked alone`;
  if (d === false) return `${row.family}: the DSL refuses the entry before anything else sees it`;
  if (c === false && k === true) return `${row.family}: the core refuses what the kernel alone would build, and names where`;
  if (c === false && k === false) return `${row.family}: the core refuses what the kernel would refuse too, and says why sooner`;
  if (c === false) return `${row.family}: the core refuses what the DSL leaves to it`;
  if (k === false) return `${row.family}: only the kernel can refuse this, and it says why`;
  return `${row.family}: every layer builds it`;
}

const seen = new Set<string>();
const cases = [];
for (const row of rows) {
  // A pinned outline was chosen by hand, and is always kept.
  const pinned = row.id.startsWith("pinned/");
  const key = [pinned ? row.id : row.family, ...[row.dsl, row.core, row.kernel].map((v) => (v === null ? "-" : v.ok ? "ok" : shape(v.message)))].join("|");
  if (seen.has(key) || (!pinned && (row.ms ?? 0) > KERNEL_BUDGET_MS)) continue;
  seen.add(key);
  cases.push({
    why: row.why ?? why(row),
    from: row.id,
    outline: row.outline,
    dsl: expected(row.dsl, true),
    core: expected(row.core, true),
    kernel: row.crash ? { crashes: true } : expected(row.kernel, false),
    ...(row.kernel_alone ? { kernel_alone: true } : {}),
  });
}

const note =
  "Where the three layers that judge a section agree and disagree, recorded once. `dsl` is `checkSection` in app/src/dsl.ts, reached through extrude(); `core` is parsing the entries and Op::validate_outline; `kernel` is lowering an extrusion of the outline, or, with `kernel_alone`, the section's face built and checked with none of the core's checks in front of it. `refuses` is the whole message for the DSL and the core, and the first sentence for the kernel. `crashes` marks an outline the kernel alone aborts on, which the test does not ask. Generated by tools/section-promote.ts from a tools/section-fuzz.sh run; docs/SECTION_CHECKS.md says what the disagreements are and which are meant.";
// One case per line: the outlines are long, and a line each keeps a diff readable.
process.stdout.write(`{\n "note": ${JSON.stringify(note)},\n "cases": [\n${cases.map((c) => `  ${JSON.stringify(c)}`).join(",\n")}\n ]\n}\n`);
